// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend-go/internal/model/member"
)

func newMemberSignInRecord(db *gorm.DB, opts ...gen.DOOption) memberSignInRecord {
	_memberSignInRecord := memberSignInRecord{}

	_memberSignInRecord.memberSignInRecordDo.UseDB(db, opts...)
	_memberSignInRecord.memberSignInRecordDo.UseModel(&member.MemberSignInRecord{})

	tableName := _memberSignInRecord.memberSignInRecordDo.TableName()
	_memberSignInRecord.ALL = field.NewAsterisk(tableName)
	_memberSignInRecord.ID = field.NewInt64(tableName, "id")
	_memberSignInRecord.UserID = field.NewInt64(tableName, "user_id")
	_memberSignInRecord.Day = field.NewInt(tableName, "day")
	_memberSignInRecord.Point = field.NewInt(tableName, "point")
	_memberSignInRecord.Experience = field.NewInt(tableName, "experience")
	_memberSignInRecord.Creator = field.NewString(tableName, "creator")
	_memberSignInRecord.Updater = field.NewString(tableName, "updater")
	_memberSignInRecord.CreatedAt = field.NewTime(tableName, "create_time")
	_memberSignInRecord.UpdatedAt = field.NewTime(tableName, "update_time")
	_memberSignInRecord.Deleted = field.NewField(tableName, "deleted")

	_memberSignInRecord.fillFieldMap()

	return _memberSignInRecord
}

type memberSignInRecord struct {
	memberSignInRecordDo memberSignInRecordDo

	ALL        field.Asterisk
	ID         field.Int64  // 编号
	UserID     field.Int64  // 签到用户
	Day        field.Int    // 第几天签到
	Point      field.Int    // 签到的积分
	Experience field.Int    // 签到的经验
	Creator    field.String // 创建者
	Updater    field.String // 更新者
	CreatedAt  field.Time   // 创建时间
	UpdatedAt  field.Time   // 更新时间
	Deleted    field.Field  // 是否删除

	fieldMap map[string]field.Expr
}

func (m memberSignInRecord) Table(newTableName string) *memberSignInRecord {
	m.memberSignInRecordDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m memberSignInRecord) As(alias string) *memberSignInRecord {
	m.memberSignInRecordDo.DO = *(m.memberSignInRecordDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *memberSignInRecord) updateTableName(table string) *memberSignInRecord {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt64(table, "id")
	m.UserID = field.NewInt64(table, "user_id")
	m.Day = field.NewInt(table, "day")
	m.Point = field.NewInt(table, "point")
	m.Experience = field.NewInt(table, "experience")
	m.Creator = field.NewString(table, "creator")
	m.Updater = field.NewString(table, "updater")
	m.CreatedAt = field.NewTime(table, "create_time")
	m.UpdatedAt = field.NewTime(table, "update_time")
	m.Deleted = field.NewField(table, "deleted")

	m.fillFieldMap()

	return m
}

func (m *memberSignInRecord) WithContext(ctx context.Context) IMemberSignInRecordDo {
	return m.memberSignInRecordDo.WithContext(ctx)
}

func (m memberSignInRecord) TableName() string { return m.memberSignInRecordDo.TableName() }

func (m memberSignInRecord) Alias() string { return m.memberSignInRecordDo.Alias() }

func (m memberSignInRecord) Columns(cols ...field.Expr) gen.Columns {
	return m.memberSignInRecordDo.Columns(cols...)
}

func (m *memberSignInRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *memberSignInRecord) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 10)
	m.fieldMap["id"] = m.ID
	m.fieldMap["user_id"] = m.UserID
	m.fieldMap["day"] = m.Day
	m.fieldMap["point"] = m.Point
	m.fieldMap["experience"] = m.Experience
	m.fieldMap["creator"] = m.Creator
	m.fieldMap["updater"] = m.Updater
	m.fieldMap["create_time"] = m.CreatedAt
	m.fieldMap["update_time"] = m.UpdatedAt
	m.fieldMap["deleted"] = m.Deleted
}

func (m memberSignInRecord) clone(db *gorm.DB) memberSignInRecord {
	m.memberSignInRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m memberSignInRecord) replaceDB(db *gorm.DB) memberSignInRecord {
	m.memberSignInRecordDo.ReplaceDB(db)
	return m
}

type memberSignInRecordDo struct{ gen.DO }

type IMemberSignInRecordDo interface {
	gen.SubQuery
	Debug() IMemberSignInRecordDo
	WithContext(ctx context.Context) IMemberSignInRecordDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMemberSignInRecordDo
	WriteDB() IMemberSignInRecordDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMemberSignInRecordDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMemberSignInRecordDo
	Not(conds ...gen.Condition) IMemberSignInRecordDo
	Or(conds ...gen.Condition) IMemberSignInRecordDo
	Select(conds ...field.Expr) IMemberSignInRecordDo
	Where(conds ...gen.Condition) IMemberSignInRecordDo
	Order(conds ...field.Expr) IMemberSignInRecordDo
	Distinct(cols ...field.Expr) IMemberSignInRecordDo
	Omit(cols ...field.Expr) IMemberSignInRecordDo
	Join(table schema.Tabler, on ...field.Expr) IMemberSignInRecordDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMemberSignInRecordDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMemberSignInRecordDo
	Group(cols ...field.Expr) IMemberSignInRecordDo
	Having(conds ...gen.Condition) IMemberSignInRecordDo
	Limit(limit int) IMemberSignInRecordDo
	Offset(offset int) IMemberSignInRecordDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMemberSignInRecordDo
	Unscoped() IMemberSignInRecordDo
	Create(values ...*member.MemberSignInRecord) error
	CreateInBatches(values []*member.MemberSignInRecord, batchSize int) error
	Save(values ...*member.MemberSignInRecord) error
	First() (*member.MemberSignInRecord, error)
	Take() (*member.MemberSignInRecord, error)
	Last() (*member.MemberSignInRecord, error)
	Find() ([]*member.MemberSignInRecord, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*member.MemberSignInRecord, err error)
	FindInBatches(result *[]*member.MemberSignInRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*member.MemberSignInRecord) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMemberSignInRecordDo
	Assign(attrs ...field.AssignExpr) IMemberSignInRecordDo
	Joins(fields ...field.RelationField) IMemberSignInRecordDo
	Preload(fields ...field.RelationField) IMemberSignInRecordDo
	FirstOrInit() (*member.MemberSignInRecord, error)
	FirstOrCreate() (*member.MemberSignInRecord, error)
	FindByPage(offset int, limit int) (result []*member.MemberSignInRecord, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMemberSignInRecordDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m memberSignInRecordDo) Debug() IMemberSignInRecordDo {
	return m.withDO(m.DO.Debug())
}

func (m memberSignInRecordDo) WithContext(ctx context.Context) IMemberSignInRecordDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m memberSignInRecordDo) ReadDB() IMemberSignInRecordDo {
	return m.Clauses(dbresolver.Read)
}

func (m memberSignInRecordDo) WriteDB() IMemberSignInRecordDo {
	return m.Clauses(dbresolver.Write)
}

func (m memberSignInRecordDo) Session(config *gorm.Session) IMemberSignInRecordDo {
	return m.withDO(m.DO.Session(config))
}

func (m memberSignInRecordDo) Clauses(conds ...clause.Expression) IMemberSignInRecordDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m memberSignInRecordDo) Returning(value interface{}, columns ...string) IMemberSignInRecordDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m memberSignInRecordDo) Not(conds ...gen.Condition) IMemberSignInRecordDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m memberSignInRecordDo) Or(conds ...gen.Condition) IMemberSignInRecordDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m memberSignInRecordDo) Select(conds ...field.Expr) IMemberSignInRecordDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m memberSignInRecordDo) Where(conds ...gen.Condition) IMemberSignInRecordDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m memberSignInRecordDo) Order(conds ...field.Expr) IMemberSignInRecordDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m memberSignInRecordDo) Distinct(cols ...field.Expr) IMemberSignInRecordDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m memberSignInRecordDo) Omit(cols ...field.Expr) IMemberSignInRecordDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m memberSignInRecordDo) Join(table schema.Tabler, on ...field.Expr) IMemberSignInRecordDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m memberSignInRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMemberSignInRecordDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m memberSignInRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) IMemberSignInRecordDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m memberSignInRecordDo) Group(cols ...field.Expr) IMemberSignInRecordDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m memberSignInRecordDo) Having(conds ...gen.Condition) IMemberSignInRecordDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m memberSignInRecordDo) Limit(limit int) IMemberSignInRecordDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m memberSignInRecordDo) Offset(offset int) IMemberSignInRecordDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m memberSignInRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMemberSignInRecordDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m memberSignInRecordDo) Unscoped() IMemberSignInRecordDo {
	return m.withDO(m.DO.Unscoped())
}

func (m memberSignInRecordDo) Create(values ...*member.MemberSignInRecord) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m memberSignInRecordDo) CreateInBatches(values []*member.MemberSignInRecord, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m memberSignInRecordDo) Save(values ...*member.MemberSignInRecord) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m memberSignInRecordDo) First() (*member.MemberSignInRecord, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*member.MemberSignInRecord), nil
	}
}

func (m memberSignInRecordDo) Take() (*member.MemberSignInRecord, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*member.MemberSignInRecord), nil
	}
}

func (m memberSignInRecordDo) Last() (*member.MemberSignInRecord, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*member.MemberSignInRecord), nil
	}
}

func (m memberSignInRecordDo) Find() ([]*member.MemberSignInRecord, error) {
	result, err := m.DO.Find()
	return result.([]*member.MemberSignInRecord), err
}

func (m memberSignInRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*member.MemberSignInRecord, err error) {
	buf := make([]*member.MemberSignInRecord, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m memberSignInRecordDo) FindInBatches(result *[]*member.MemberSignInRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m memberSignInRecordDo) Attrs(attrs ...field.AssignExpr) IMemberSignInRecordDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m memberSignInRecordDo) Assign(attrs ...field.AssignExpr) IMemberSignInRecordDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m memberSignInRecordDo) Joins(fields ...field.RelationField) IMemberSignInRecordDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m memberSignInRecordDo) Preload(fields ...field.RelationField) IMemberSignInRecordDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m memberSignInRecordDo) FirstOrInit() (*member.MemberSignInRecord, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*member.MemberSignInRecord), nil
	}
}

func (m memberSignInRecordDo) FirstOrCreate() (*member.MemberSignInRecord, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*member.MemberSignInRecord), nil
	}
}

func (m memberSignInRecordDo) FindByPage(offset int, limit int) (result []*member.MemberSignInRecord, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m memberSignInRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m memberSignInRecordDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m memberSignInRecordDo) Delete(models ...*member.MemberSignInRecord) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *memberSignInRecordDo) withDO(do gen.Dao) *memberSignInRecordDo {
	m.DO = *do.(*gen.DO)
	return m
}
