// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend-go/internal/model/member"
)

func newMemberAddress(db *gorm.DB, opts ...gen.DOOption) memberAddress {
	_memberAddress := memberAddress{}

	_memberAddress.memberAddressDo.UseDB(db, opts...)
	_memberAddress.memberAddressDo.UseModel(&member.MemberAddress{})

	tableName := _memberAddress.memberAddressDo.TableName()
	_memberAddress.ALL = field.NewAsterisk(tableName)
	_memberAddress.ID = field.NewInt64(tableName, "id")
	_memberAddress.UserID = field.NewInt64(tableName, "user_id")
	_memberAddress.Name = field.NewString(tableName, "name")
	_memberAddress.Mobile = field.NewString(tableName, "mobile")
	_memberAddress.AreaID = field.NewInt64(tableName, "area_id")
	_memberAddress.DetailAddress = field.NewString(tableName, "detail_address")
	_memberAddress.DefaultStatus = field.NewField(tableName, "default_status")
	_memberAddress.Creator = field.NewString(tableName, "creator")
	_memberAddress.Updater = field.NewString(tableName, "updater")
	_memberAddress.CreatedAt = field.NewTime(tableName, "create_time")
	_memberAddress.UpdatedAt = field.NewTime(tableName, "update_time")
	_memberAddress.Deleted = field.NewField(tableName, "deleted")

	_memberAddress.fillFieldMap()

	return _memberAddress
}

type memberAddress struct {
	memberAddressDo memberAddressDo

	ALL           field.Asterisk
	ID            field.Int64  // 收件地址编号
	UserID        field.Int64  // 用户编号
	Name          field.String // 收件人名称
	Mobile        field.String // 手机号
	AreaID        field.Int64  // 地区编号
	DetailAddress field.String // 收件详细地址
	DefaultStatus field.Field  // 是否默认
	Creator       field.String // 创建者
	Updater       field.String // 更新者
	CreatedAt     field.Time   // 创建时间
	UpdatedAt     field.Time   // 更新时间
	Deleted       field.Field  // 是否删除

	fieldMap map[string]field.Expr
}

func (m memberAddress) Table(newTableName string) *memberAddress {
	m.memberAddressDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m memberAddress) As(alias string) *memberAddress {
	m.memberAddressDo.DO = *(m.memberAddressDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *memberAddress) updateTableName(table string) *memberAddress {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt64(table, "id")
	m.UserID = field.NewInt64(table, "user_id")
	m.Name = field.NewString(table, "name")
	m.Mobile = field.NewString(table, "mobile")
	m.AreaID = field.NewInt64(table, "area_id")
	m.DetailAddress = field.NewString(table, "detail_address")
	m.DefaultStatus = field.NewField(table, "default_status")
	m.Creator = field.NewString(table, "creator")
	m.Updater = field.NewString(table, "updater")
	m.CreatedAt = field.NewTime(table, "create_time")
	m.UpdatedAt = field.NewTime(table, "update_time")
	m.Deleted = field.NewField(table, "deleted")

	m.fillFieldMap()

	return m
}

func (m *memberAddress) WithContext(ctx context.Context) IMemberAddressDo {
	return m.memberAddressDo.WithContext(ctx)
}

func (m memberAddress) TableName() string { return m.memberAddressDo.TableName() }

func (m memberAddress) Alias() string { return m.memberAddressDo.Alias() }

func (m memberAddress) Columns(cols ...field.Expr) gen.Columns {
	return m.memberAddressDo.Columns(cols...)
}

func (m *memberAddress) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *memberAddress) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 12)
	m.fieldMap["id"] = m.ID
	m.fieldMap["user_id"] = m.UserID
	m.fieldMap["name"] = m.Name
	m.fieldMap["mobile"] = m.Mobile
	m.fieldMap["area_id"] = m.AreaID
	m.fieldMap["detail_address"] = m.DetailAddress
	m.fieldMap["default_status"] = m.DefaultStatus
	m.fieldMap["creator"] = m.Creator
	m.fieldMap["updater"] = m.Updater
	m.fieldMap["create_time"] = m.CreatedAt
	m.fieldMap["update_time"] = m.UpdatedAt
	m.fieldMap["deleted"] = m.Deleted
}

func (m memberAddress) clone(db *gorm.DB) memberAddress {
	m.memberAddressDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m memberAddress) replaceDB(db *gorm.DB) memberAddress {
	m.memberAddressDo.ReplaceDB(db)
	return m
}

type memberAddressDo struct{ gen.DO }

type IMemberAddressDo interface {
	gen.SubQuery
	Debug() IMemberAddressDo
	WithContext(ctx context.Context) IMemberAddressDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMemberAddressDo
	WriteDB() IMemberAddressDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMemberAddressDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMemberAddressDo
	Not(conds ...gen.Condition) IMemberAddressDo
	Or(conds ...gen.Condition) IMemberAddressDo
	Select(conds ...field.Expr) IMemberAddressDo
	Where(conds ...gen.Condition) IMemberAddressDo
	Order(conds ...field.Expr) IMemberAddressDo
	Distinct(cols ...field.Expr) IMemberAddressDo
	Omit(cols ...field.Expr) IMemberAddressDo
	Join(table schema.Tabler, on ...field.Expr) IMemberAddressDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMemberAddressDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMemberAddressDo
	Group(cols ...field.Expr) IMemberAddressDo
	Having(conds ...gen.Condition) IMemberAddressDo
	Limit(limit int) IMemberAddressDo
	Offset(offset int) IMemberAddressDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMemberAddressDo
	Unscoped() IMemberAddressDo
	Create(values ...*member.MemberAddress) error
	CreateInBatches(values []*member.MemberAddress, batchSize int) error
	Save(values ...*member.MemberAddress) error
	First() (*member.MemberAddress, error)
	Take() (*member.MemberAddress, error)
	Last() (*member.MemberAddress, error)
	Find() ([]*member.MemberAddress, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*member.MemberAddress, err error)
	FindInBatches(result *[]*member.MemberAddress, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*member.MemberAddress) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMemberAddressDo
	Assign(attrs ...field.AssignExpr) IMemberAddressDo
	Joins(fields ...field.RelationField) IMemberAddressDo
	Preload(fields ...field.RelationField) IMemberAddressDo
	FirstOrInit() (*member.MemberAddress, error)
	FirstOrCreate() (*member.MemberAddress, error)
	FindByPage(offset int, limit int) (result []*member.MemberAddress, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMemberAddressDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m memberAddressDo) Debug() IMemberAddressDo {
	return m.withDO(m.DO.Debug())
}

func (m memberAddressDo) WithContext(ctx context.Context) IMemberAddressDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m memberAddressDo) ReadDB() IMemberAddressDo {
	return m.Clauses(dbresolver.Read)
}

func (m memberAddressDo) WriteDB() IMemberAddressDo {
	return m.Clauses(dbresolver.Write)
}

func (m memberAddressDo) Session(config *gorm.Session) IMemberAddressDo {
	return m.withDO(m.DO.Session(config))
}

func (m memberAddressDo) Clauses(conds ...clause.Expression) IMemberAddressDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m memberAddressDo) Returning(value interface{}, columns ...string) IMemberAddressDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m memberAddressDo) Not(conds ...gen.Condition) IMemberAddressDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m memberAddressDo) Or(conds ...gen.Condition) IMemberAddressDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m memberAddressDo) Select(conds ...field.Expr) IMemberAddressDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m memberAddressDo) Where(conds ...gen.Condition) IMemberAddressDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m memberAddressDo) Order(conds ...field.Expr) IMemberAddressDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m memberAddressDo) Distinct(cols ...field.Expr) IMemberAddressDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m memberAddressDo) Omit(cols ...field.Expr) IMemberAddressDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m memberAddressDo) Join(table schema.Tabler, on ...field.Expr) IMemberAddressDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m memberAddressDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMemberAddressDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m memberAddressDo) RightJoin(table schema.Tabler, on ...field.Expr) IMemberAddressDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m memberAddressDo) Group(cols ...field.Expr) IMemberAddressDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m memberAddressDo) Having(conds ...gen.Condition) IMemberAddressDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m memberAddressDo) Limit(limit int) IMemberAddressDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m memberAddressDo) Offset(offset int) IMemberAddressDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m memberAddressDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMemberAddressDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m memberAddressDo) Unscoped() IMemberAddressDo {
	return m.withDO(m.DO.Unscoped())
}

func (m memberAddressDo) Create(values ...*member.MemberAddress) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m memberAddressDo) CreateInBatches(values []*member.MemberAddress, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m memberAddressDo) Save(values ...*member.MemberAddress) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m memberAddressDo) First() (*member.MemberAddress, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*member.MemberAddress), nil
	}
}

func (m memberAddressDo) Take() (*member.MemberAddress, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*member.MemberAddress), nil
	}
}

func (m memberAddressDo) Last() (*member.MemberAddress, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*member.MemberAddress), nil
	}
}

func (m memberAddressDo) Find() ([]*member.MemberAddress, error) {
	result, err := m.DO.Find()
	return result.([]*member.MemberAddress), err
}

func (m memberAddressDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*member.MemberAddress, err error) {
	buf := make([]*member.MemberAddress, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m memberAddressDo) FindInBatches(result *[]*member.MemberAddress, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m memberAddressDo) Attrs(attrs ...field.AssignExpr) IMemberAddressDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m memberAddressDo) Assign(attrs ...field.AssignExpr) IMemberAddressDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m memberAddressDo) Joins(fields ...field.RelationField) IMemberAddressDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m memberAddressDo) Preload(fields ...field.RelationField) IMemberAddressDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m memberAddressDo) FirstOrInit() (*member.MemberAddress, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*member.MemberAddress), nil
	}
}

func (m memberAddressDo) FirstOrCreate() (*member.MemberAddress, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*member.MemberAddress), nil
	}
}

func (m memberAddressDo) FindByPage(offset int, limit int) (result []*member.MemberAddress, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m memberAddressDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m memberAddressDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m memberAddressDo) Delete(models ...*member.MemberAddress) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *memberAddressDo) withDO(do gen.Dao) *memberAddressDo {
	m.DO = *do.(*gen.DO)
	return m
}
