// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend-go/internal/model/member"
)

func newMemberLevel(db *gorm.DB, opts ...gen.DOOption) memberLevel {
	_memberLevel := memberLevel{}

	_memberLevel.memberLevelDo.UseDB(db, opts...)
	_memberLevel.memberLevelDo.UseModel(&member.MemberLevel{})

	tableName := _memberLevel.memberLevelDo.TableName()
	_memberLevel.ALL = field.NewAsterisk(tableName)
	_memberLevel.ID = field.NewInt64(tableName, "id")
	_memberLevel.Name = field.NewString(tableName, "name")
	_memberLevel.Level = field.NewInt(tableName, "level")
	_memberLevel.Experience = field.NewInt(tableName, "experience")
	_memberLevel.DiscountPercent = field.NewInt(tableName, "discount_percent")
	_memberLevel.Icon = field.NewString(tableName, "icon")
	_memberLevel.BackgroundURL = field.NewString(tableName, "background_url")
	_memberLevel.Status = field.NewInt(tableName, "status")
	_memberLevel.Remark = field.NewString(tableName, "remark")
	_memberLevel.Creator = field.NewString(tableName, "creator")
	_memberLevel.Updater = field.NewString(tableName, "updater")
	_memberLevel.CreatedAt = field.NewTime(tableName, "create_time")
	_memberLevel.UpdatedAt = field.NewTime(tableName, "update_time")
	_memberLevel.DeletedAt = field.NewField(tableName, "deleted")
	_memberLevel.Deleted = field.NewBool(tableName, "deleted")

	_memberLevel.fillFieldMap()

	return _memberLevel
}

type memberLevel struct {
	memberLevelDo memberLevelDo

	ALL             field.Asterisk
	ID              field.Int64  // 编号
	Name            field.String // 等级名称
	Level           field.Int    // 等级
	Experience      field.Int    // 升级经验
	DiscountPercent field.Int    // 享受折扣
	Icon            field.String // 等级图标
	BackgroundURL   field.String // 等级背景图
	Status          field.Int    // 状态
	Remark          field.String // 备注
	Creator         field.String // 创建者
	Updater         field.String // 更新者
	CreatedAt       field.Time   // 创建时间
	UpdatedAt       field.Time   // 更新时间
	DeletedAt       field.Field  // 删除时间
	Deleted         field.Bool   // 是否删除

	fieldMap map[string]field.Expr
}

func (m memberLevel) Table(newTableName string) *memberLevel {
	m.memberLevelDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m memberLevel) As(alias string) *memberLevel {
	m.memberLevelDo.DO = *(m.memberLevelDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *memberLevel) updateTableName(table string) *memberLevel {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt64(table, "id")
	m.Name = field.NewString(table, "name")
	m.Level = field.NewInt(table, "level")
	m.Experience = field.NewInt(table, "experience")
	m.DiscountPercent = field.NewInt(table, "discount_percent")
	m.Icon = field.NewString(table, "icon")
	m.BackgroundURL = field.NewString(table, "background_url")
	m.Status = field.NewInt(table, "status")
	m.Remark = field.NewString(table, "remark")
	m.Creator = field.NewString(table, "creator")
	m.Updater = field.NewString(table, "updater")
	m.CreatedAt = field.NewTime(table, "create_time")
	m.UpdatedAt = field.NewTime(table, "update_time")
	m.DeletedAt = field.NewField(table, "deleted")
	m.Deleted = field.NewBool(table, "deleted")

	m.fillFieldMap()

	return m
}

func (m *memberLevel) WithContext(ctx context.Context) IMemberLevelDo {
	return m.memberLevelDo.WithContext(ctx)
}

func (m memberLevel) TableName() string { return m.memberLevelDo.TableName() }

func (m memberLevel) Alias() string { return m.memberLevelDo.Alias() }

func (m memberLevel) Columns(cols ...field.Expr) gen.Columns { return m.memberLevelDo.Columns(cols...) }

func (m *memberLevel) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *memberLevel) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 15)
	m.fieldMap["id"] = m.ID
	m.fieldMap["name"] = m.Name
	m.fieldMap["level"] = m.Level
	m.fieldMap["experience"] = m.Experience
	m.fieldMap["discount_percent"] = m.DiscountPercent
	m.fieldMap["icon"] = m.Icon
	m.fieldMap["background_url"] = m.BackgroundURL
	m.fieldMap["status"] = m.Status
	m.fieldMap["remark"] = m.Remark
	m.fieldMap["creator"] = m.Creator
	m.fieldMap["updater"] = m.Updater
	m.fieldMap["create_time"] = m.CreatedAt
	m.fieldMap["update_time"] = m.UpdatedAt
	m.fieldMap["deleted"] = m.DeletedAt
	m.fieldMap["deleted"] = m.Deleted
}

func (m memberLevel) clone(db *gorm.DB) memberLevel {
	m.memberLevelDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m memberLevel) replaceDB(db *gorm.DB) memberLevel {
	m.memberLevelDo.ReplaceDB(db)
	return m
}

type memberLevelDo struct{ gen.DO }

type IMemberLevelDo interface {
	gen.SubQuery
	Debug() IMemberLevelDo
	WithContext(ctx context.Context) IMemberLevelDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMemberLevelDo
	WriteDB() IMemberLevelDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMemberLevelDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMemberLevelDo
	Not(conds ...gen.Condition) IMemberLevelDo
	Or(conds ...gen.Condition) IMemberLevelDo
	Select(conds ...field.Expr) IMemberLevelDo
	Where(conds ...gen.Condition) IMemberLevelDo
	Order(conds ...field.Expr) IMemberLevelDo
	Distinct(cols ...field.Expr) IMemberLevelDo
	Omit(cols ...field.Expr) IMemberLevelDo
	Join(table schema.Tabler, on ...field.Expr) IMemberLevelDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMemberLevelDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMemberLevelDo
	Group(cols ...field.Expr) IMemberLevelDo
	Having(conds ...gen.Condition) IMemberLevelDo
	Limit(limit int) IMemberLevelDo
	Offset(offset int) IMemberLevelDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMemberLevelDo
	Unscoped() IMemberLevelDo
	Create(values ...*member.MemberLevel) error
	CreateInBatches(values []*member.MemberLevel, batchSize int) error
	Save(values ...*member.MemberLevel) error
	First() (*member.MemberLevel, error)
	Take() (*member.MemberLevel, error)
	Last() (*member.MemberLevel, error)
	Find() ([]*member.MemberLevel, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*member.MemberLevel, err error)
	FindInBatches(result *[]*member.MemberLevel, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*member.MemberLevel) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMemberLevelDo
	Assign(attrs ...field.AssignExpr) IMemberLevelDo
	Joins(fields ...field.RelationField) IMemberLevelDo
	Preload(fields ...field.RelationField) IMemberLevelDo
	FirstOrInit() (*member.MemberLevel, error)
	FirstOrCreate() (*member.MemberLevel, error)
	FindByPage(offset int, limit int) (result []*member.MemberLevel, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMemberLevelDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m memberLevelDo) Debug() IMemberLevelDo {
	return m.withDO(m.DO.Debug())
}

func (m memberLevelDo) WithContext(ctx context.Context) IMemberLevelDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m memberLevelDo) ReadDB() IMemberLevelDo {
	return m.Clauses(dbresolver.Read)
}

func (m memberLevelDo) WriteDB() IMemberLevelDo {
	return m.Clauses(dbresolver.Write)
}

func (m memberLevelDo) Session(config *gorm.Session) IMemberLevelDo {
	return m.withDO(m.DO.Session(config))
}

func (m memberLevelDo) Clauses(conds ...clause.Expression) IMemberLevelDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m memberLevelDo) Returning(value interface{}, columns ...string) IMemberLevelDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m memberLevelDo) Not(conds ...gen.Condition) IMemberLevelDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m memberLevelDo) Or(conds ...gen.Condition) IMemberLevelDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m memberLevelDo) Select(conds ...field.Expr) IMemberLevelDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m memberLevelDo) Where(conds ...gen.Condition) IMemberLevelDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m memberLevelDo) Order(conds ...field.Expr) IMemberLevelDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m memberLevelDo) Distinct(cols ...field.Expr) IMemberLevelDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m memberLevelDo) Omit(cols ...field.Expr) IMemberLevelDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m memberLevelDo) Join(table schema.Tabler, on ...field.Expr) IMemberLevelDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m memberLevelDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMemberLevelDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m memberLevelDo) RightJoin(table schema.Tabler, on ...field.Expr) IMemberLevelDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m memberLevelDo) Group(cols ...field.Expr) IMemberLevelDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m memberLevelDo) Having(conds ...gen.Condition) IMemberLevelDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m memberLevelDo) Limit(limit int) IMemberLevelDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m memberLevelDo) Offset(offset int) IMemberLevelDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m memberLevelDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMemberLevelDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m memberLevelDo) Unscoped() IMemberLevelDo {
	return m.withDO(m.DO.Unscoped())
}

func (m memberLevelDo) Create(values ...*member.MemberLevel) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m memberLevelDo) CreateInBatches(values []*member.MemberLevel, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m memberLevelDo) Save(values ...*member.MemberLevel) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m memberLevelDo) First() (*member.MemberLevel, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*member.MemberLevel), nil
	}
}

func (m memberLevelDo) Take() (*member.MemberLevel, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*member.MemberLevel), nil
	}
}

func (m memberLevelDo) Last() (*member.MemberLevel, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*member.MemberLevel), nil
	}
}

func (m memberLevelDo) Find() ([]*member.MemberLevel, error) {
	result, err := m.DO.Find()
	return result.([]*member.MemberLevel), err
}

func (m memberLevelDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*member.MemberLevel, err error) {
	buf := make([]*member.MemberLevel, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m memberLevelDo) FindInBatches(result *[]*member.MemberLevel, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m memberLevelDo) Attrs(attrs ...field.AssignExpr) IMemberLevelDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m memberLevelDo) Assign(attrs ...field.AssignExpr) IMemberLevelDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m memberLevelDo) Joins(fields ...field.RelationField) IMemberLevelDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m memberLevelDo) Preload(fields ...field.RelationField) IMemberLevelDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m memberLevelDo) FirstOrInit() (*member.MemberLevel, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*member.MemberLevel), nil
	}
}

func (m memberLevelDo) FirstOrCreate() (*member.MemberLevel, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*member.MemberLevel), nil
	}
}

func (m memberLevelDo) FindByPage(offset int, limit int) (result []*member.MemberLevel, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m memberLevelDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m memberLevelDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m memberLevelDo) Delete(models ...*member.MemberLevel) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *memberLevelDo) withDO(do gen.Dao) *memberLevelDo {
	m.DO = *do.(*gen.DO)
	return m
}
