// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend-go/internal/model/member"
)

func newMemberUser(db *gorm.DB, opts ...gen.DOOption) memberUser {
	_memberUser := memberUser{}

	_memberUser.memberUserDo.UseDB(db, opts...)
	_memberUser.memberUserDo.UseModel(&member.MemberUser{})

	tableName := _memberUser.memberUserDo.TableName()
	_memberUser.ALL = field.NewAsterisk(tableName)
	_memberUser.ID = field.NewInt64(tableName, "id")
	_memberUser.Mobile = field.NewString(tableName, "mobile")
	_memberUser.Password = field.NewString(tableName, "password")
	_memberUser.Status = field.NewInt32(tableName, "status")
	_memberUser.RegisterIP = field.NewString(tableName, "register_ip")
	_memberUser.RegisterTerminal = field.NewInt32(tableName, "register_terminal")
	_memberUser.LoginIP = field.NewString(tableName, "login_ip")
	_memberUser.LoginDate = field.NewTime(tableName, "login_date")
	_memberUser.Nickname = field.NewString(tableName, "nickname")
	_memberUser.Avatar = field.NewString(tableName, "avatar")
	_memberUser.Name = field.NewString(tableName, "name")
	_memberUser.Sex = field.NewInt32(tableName, "sex")
	_memberUser.Birthday = field.NewTime(tableName, "birthday")
	_memberUser.AreaID = field.NewInt32(tableName, "area_id")
	_memberUser.Mark = field.NewString(tableName, "mark")
	_memberUser.Point = field.NewInt32(tableName, "point")
	_memberUser.TagIds = field.NewField(tableName, "tag_ids")
	_memberUser.LevelID = field.NewInt64(tableName, "level_id")
	_memberUser.Experience = field.NewInt32(tableName, "experience")
	_memberUser.GroupID = field.NewInt64(tableName, "group_id")
	_memberUser.TenantID = field.NewInt64(tableName, "tenant_id")
	_memberUser.Creator = field.NewString(tableName, "creator")
	_memberUser.Updater = field.NewString(tableName, "updater")
	_memberUser.CreatedAt = field.NewTime(tableName, "create_time")
	_memberUser.UpdatedAt = field.NewTime(tableName, "update_time")
	_memberUser.Deleted = field.NewField(tableName, "deleted")
	_memberUser.BrokerageEnabled = field.NewField(tableName, "brokerage_enabled")

	_memberUser.fillFieldMap()

	return _memberUser
}

type memberUser struct {
	memberUserDo memberUserDo

	ALL              field.Asterisk
	ID               field.Int64  // 用户ID
	Mobile           field.String // 手机
	Password         field.String // 密码
	Status           field.Int32  // 状态
	RegisterIP       field.String // 注册IP
	RegisterTerminal field.Int32  // 注册终端
	LoginIP          field.String // 最后登录IP
	LoginDate        field.Time   // 最后登录时间
	Nickname         field.String // 用户昵称
	Avatar           field.String // 头像
	Name             field.String // 真实姓名
	Sex              field.Int32  // 性别
	Birthday         field.Time   // 出生日期
	AreaID           field.Int32  // 所在地
	Mark             field.String // 备注
	Point            field.Int32  // 积分
	TagIds           field.Field  // 标签编号数组
	LevelID          field.Int64  // 等级编号
	Experience       field.Int32  // 经验
	GroupID          field.Int64  // 分组编号
	TenantID         field.Int64  // 租户编号
	Creator          field.String // 创建者
	Updater          field.String // 更新者
	CreatedAt        field.Time   // 创建时间
	UpdatedAt        field.Time   // 更新时间
	Deleted          field.Field  // 是否删除
	BrokerageEnabled field.Field  // 是否成为推广员

	fieldMap map[string]field.Expr
}

func (m memberUser) Table(newTableName string) *memberUser {
	m.memberUserDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m memberUser) As(alias string) *memberUser {
	m.memberUserDo.DO = *(m.memberUserDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *memberUser) updateTableName(table string) *memberUser {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt64(table, "id")
	m.Mobile = field.NewString(table, "mobile")
	m.Password = field.NewString(table, "password")
	m.Status = field.NewInt32(table, "status")
	m.RegisterIP = field.NewString(table, "register_ip")
	m.RegisterTerminal = field.NewInt32(table, "register_terminal")
	m.LoginIP = field.NewString(table, "login_ip")
	m.LoginDate = field.NewTime(table, "login_date")
	m.Nickname = field.NewString(table, "nickname")
	m.Avatar = field.NewString(table, "avatar")
	m.Name = field.NewString(table, "name")
	m.Sex = field.NewInt32(table, "sex")
	m.Birthday = field.NewTime(table, "birthday")
	m.AreaID = field.NewInt32(table, "area_id")
	m.Mark = field.NewString(table, "mark")
	m.Point = field.NewInt32(table, "point")
	m.TagIds = field.NewField(table, "tag_ids")
	m.LevelID = field.NewInt64(table, "level_id")
	m.Experience = field.NewInt32(table, "experience")
	m.GroupID = field.NewInt64(table, "group_id")
	m.TenantID = field.NewInt64(table, "tenant_id")
	m.Creator = field.NewString(table, "creator")
	m.Updater = field.NewString(table, "updater")
	m.CreatedAt = field.NewTime(table, "create_time")
	m.UpdatedAt = field.NewTime(table, "update_time")
	m.Deleted = field.NewField(table, "deleted")
	m.BrokerageEnabled = field.NewField(table, "brokerage_enabled")

	m.fillFieldMap()

	return m
}

func (m *memberUser) WithContext(ctx context.Context) IMemberUserDo {
	return m.memberUserDo.WithContext(ctx)
}

func (m memberUser) TableName() string { return m.memberUserDo.TableName() }

func (m memberUser) Alias() string { return m.memberUserDo.Alias() }

func (m memberUser) Columns(cols ...field.Expr) gen.Columns { return m.memberUserDo.Columns(cols...) }

func (m *memberUser) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *memberUser) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 27)
	m.fieldMap["id"] = m.ID
	m.fieldMap["mobile"] = m.Mobile
	m.fieldMap["password"] = m.Password
	m.fieldMap["status"] = m.Status
	m.fieldMap["register_ip"] = m.RegisterIP
	m.fieldMap["register_terminal"] = m.RegisterTerminal
	m.fieldMap["login_ip"] = m.LoginIP
	m.fieldMap["login_date"] = m.LoginDate
	m.fieldMap["nickname"] = m.Nickname
	m.fieldMap["avatar"] = m.Avatar
	m.fieldMap["name"] = m.Name
	m.fieldMap["sex"] = m.Sex
	m.fieldMap["birthday"] = m.Birthday
	m.fieldMap["area_id"] = m.AreaID
	m.fieldMap["mark"] = m.Mark
	m.fieldMap["point"] = m.Point
	m.fieldMap["tag_ids"] = m.TagIds
	m.fieldMap["level_id"] = m.LevelID
	m.fieldMap["experience"] = m.Experience
	m.fieldMap["group_id"] = m.GroupID
	m.fieldMap["tenant_id"] = m.TenantID
	m.fieldMap["creator"] = m.Creator
	m.fieldMap["updater"] = m.Updater
	m.fieldMap["create_time"] = m.CreatedAt
	m.fieldMap["update_time"] = m.UpdatedAt
	m.fieldMap["deleted"] = m.Deleted
	m.fieldMap["brokerage_enabled"] = m.BrokerageEnabled
}

func (m memberUser) clone(db *gorm.DB) memberUser {
	m.memberUserDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m memberUser) replaceDB(db *gorm.DB) memberUser {
	m.memberUserDo.ReplaceDB(db)
	return m
}

type memberUserDo struct{ gen.DO }

type IMemberUserDo interface {
	gen.SubQuery
	Debug() IMemberUserDo
	WithContext(ctx context.Context) IMemberUserDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMemberUserDo
	WriteDB() IMemberUserDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMemberUserDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMemberUserDo
	Not(conds ...gen.Condition) IMemberUserDo
	Or(conds ...gen.Condition) IMemberUserDo
	Select(conds ...field.Expr) IMemberUserDo
	Where(conds ...gen.Condition) IMemberUserDo
	Order(conds ...field.Expr) IMemberUserDo
	Distinct(cols ...field.Expr) IMemberUserDo
	Omit(cols ...field.Expr) IMemberUserDo
	Join(table schema.Tabler, on ...field.Expr) IMemberUserDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMemberUserDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMemberUserDo
	Group(cols ...field.Expr) IMemberUserDo
	Having(conds ...gen.Condition) IMemberUserDo
	Limit(limit int) IMemberUserDo
	Offset(offset int) IMemberUserDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMemberUserDo
	Unscoped() IMemberUserDo
	Create(values ...*member.MemberUser) error
	CreateInBatches(values []*member.MemberUser, batchSize int) error
	Save(values ...*member.MemberUser) error
	First() (*member.MemberUser, error)
	Take() (*member.MemberUser, error)
	Last() (*member.MemberUser, error)
	Find() ([]*member.MemberUser, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*member.MemberUser, err error)
	FindInBatches(result *[]*member.MemberUser, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*member.MemberUser) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMemberUserDo
	Assign(attrs ...field.AssignExpr) IMemberUserDo
	Joins(fields ...field.RelationField) IMemberUserDo
	Preload(fields ...field.RelationField) IMemberUserDo
	FirstOrInit() (*member.MemberUser, error)
	FirstOrCreate() (*member.MemberUser, error)
	FindByPage(offset int, limit int) (result []*member.MemberUser, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMemberUserDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m memberUserDo) Debug() IMemberUserDo {
	return m.withDO(m.DO.Debug())
}

func (m memberUserDo) WithContext(ctx context.Context) IMemberUserDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m memberUserDo) ReadDB() IMemberUserDo {
	return m.Clauses(dbresolver.Read)
}

func (m memberUserDo) WriteDB() IMemberUserDo {
	return m.Clauses(dbresolver.Write)
}

func (m memberUserDo) Session(config *gorm.Session) IMemberUserDo {
	return m.withDO(m.DO.Session(config))
}

func (m memberUserDo) Clauses(conds ...clause.Expression) IMemberUserDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m memberUserDo) Returning(value interface{}, columns ...string) IMemberUserDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m memberUserDo) Not(conds ...gen.Condition) IMemberUserDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m memberUserDo) Or(conds ...gen.Condition) IMemberUserDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m memberUserDo) Select(conds ...field.Expr) IMemberUserDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m memberUserDo) Where(conds ...gen.Condition) IMemberUserDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m memberUserDo) Order(conds ...field.Expr) IMemberUserDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m memberUserDo) Distinct(cols ...field.Expr) IMemberUserDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m memberUserDo) Omit(cols ...field.Expr) IMemberUserDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m memberUserDo) Join(table schema.Tabler, on ...field.Expr) IMemberUserDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m memberUserDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMemberUserDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m memberUserDo) RightJoin(table schema.Tabler, on ...field.Expr) IMemberUserDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m memberUserDo) Group(cols ...field.Expr) IMemberUserDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m memberUserDo) Having(conds ...gen.Condition) IMemberUserDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m memberUserDo) Limit(limit int) IMemberUserDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m memberUserDo) Offset(offset int) IMemberUserDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m memberUserDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMemberUserDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m memberUserDo) Unscoped() IMemberUserDo {
	return m.withDO(m.DO.Unscoped())
}

func (m memberUserDo) Create(values ...*member.MemberUser) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m memberUserDo) CreateInBatches(values []*member.MemberUser, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m memberUserDo) Save(values ...*member.MemberUser) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m memberUserDo) First() (*member.MemberUser, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*member.MemberUser), nil
	}
}

func (m memberUserDo) Take() (*member.MemberUser, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*member.MemberUser), nil
	}
}

func (m memberUserDo) Last() (*member.MemberUser, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*member.MemberUser), nil
	}
}

func (m memberUserDo) Find() ([]*member.MemberUser, error) {
	result, err := m.DO.Find()
	return result.([]*member.MemberUser), err
}

func (m memberUserDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*member.MemberUser, err error) {
	buf := make([]*member.MemberUser, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m memberUserDo) FindInBatches(result *[]*member.MemberUser, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m memberUserDo) Attrs(attrs ...field.AssignExpr) IMemberUserDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m memberUserDo) Assign(attrs ...field.AssignExpr) IMemberUserDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m memberUserDo) Joins(fields ...field.RelationField) IMemberUserDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m memberUserDo) Preload(fields ...field.RelationField) IMemberUserDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m memberUserDo) FirstOrInit() (*member.MemberUser, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*member.MemberUser), nil
	}
}

func (m memberUserDo) FirstOrCreate() (*member.MemberUser, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*member.MemberUser), nil
	}
}

func (m memberUserDo) FindByPage(offset int, limit int) (result []*member.MemberUser, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m memberUserDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m memberUserDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m memberUserDo) Delete(models ...*member.MemberUser) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *memberUserDo) withDO(do gen.Dao) *memberUserDo {
	m.DO = *do.(*gen.DO)
	return m
}
