// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend-go/internal/model/pay"
)

func newPayApp(db *gorm.DB, opts ...gen.DOOption) payApp {
	_payApp := payApp{}

	_payApp.payAppDo.UseDB(db, opts...)
	_payApp.payAppDo.UseModel(&pay.PayApp{})

	tableName := _payApp.payAppDo.TableName()
	_payApp.ALL = field.NewAsterisk(tableName)
	_payApp.ID = field.NewInt64(tableName, "id")
	_payApp.AppKey = field.NewString(tableName, "app_key")
	_payApp.Name = field.NewString(tableName, "name")
	_payApp.Status = field.NewInt(tableName, "status")
	_payApp.Remark = field.NewString(tableName, "remark")
	_payApp.OrderNotifyURL = field.NewString(tableName, "order_notify_url")
	_payApp.RefundNotifyURL = field.NewString(tableName, "refund_notify_url")
	_payApp.TransferNotifyURL = field.NewString(tableName, "transfer_notify_url")
	_payApp.Creator = field.NewString(tableName, "creator")
	_payApp.Updater = field.NewString(tableName, "updater")
	_payApp.CreatedAt = field.NewTime(tableName, "create_time")
	_payApp.UpdatedAt = field.NewTime(tableName, "update_time")
	_payApp.Deleted = field.NewField(tableName, "deleted")

	_payApp.fillFieldMap()

	return _payApp
}

type payApp struct {
	payAppDo payAppDo

	ALL               field.Asterisk
	ID                field.Int64  // 应用编号
	AppKey            field.String // 应用标识
	Name              field.String // 应用名
	Status            field.Int    // 状态
	Remark            field.String // 备注
	OrderNotifyURL    field.String // 支付结果的回调地址
	RefundNotifyURL   field.String // 退款结果的回调地址
	TransferNotifyURL field.String // 转账结果的回调地址
	Creator           field.String // 创建者
	Updater           field.String // 更新者
	CreatedAt         field.Time   // 创建时间
	UpdatedAt         field.Time   // 更新时间
	Deleted           field.Field  // 是否删除

	fieldMap map[string]field.Expr
}

func (p payApp) Table(newTableName string) *payApp {
	p.payAppDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p payApp) As(alias string) *payApp {
	p.payAppDo.DO = *(p.payAppDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *payApp) updateTableName(table string) *payApp {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.AppKey = field.NewString(table, "app_key")
	p.Name = field.NewString(table, "name")
	p.Status = field.NewInt(table, "status")
	p.Remark = field.NewString(table, "remark")
	p.OrderNotifyURL = field.NewString(table, "order_notify_url")
	p.RefundNotifyURL = field.NewString(table, "refund_notify_url")
	p.TransferNotifyURL = field.NewString(table, "transfer_notify_url")
	p.Creator = field.NewString(table, "creator")
	p.Updater = field.NewString(table, "updater")
	p.CreatedAt = field.NewTime(table, "create_time")
	p.UpdatedAt = field.NewTime(table, "update_time")
	p.Deleted = field.NewField(table, "deleted")

	p.fillFieldMap()

	return p
}

func (p *payApp) WithContext(ctx context.Context) IPayAppDo { return p.payAppDo.WithContext(ctx) }

func (p payApp) TableName() string { return p.payAppDo.TableName() }

func (p payApp) Alias() string { return p.payAppDo.Alias() }

func (p payApp) Columns(cols ...field.Expr) gen.Columns { return p.payAppDo.Columns(cols...) }

func (p *payApp) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *payApp) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 13)
	p.fieldMap["id"] = p.ID
	p.fieldMap["app_key"] = p.AppKey
	p.fieldMap["name"] = p.Name
	p.fieldMap["status"] = p.Status
	p.fieldMap["remark"] = p.Remark
	p.fieldMap["order_notify_url"] = p.OrderNotifyURL
	p.fieldMap["refund_notify_url"] = p.RefundNotifyURL
	p.fieldMap["transfer_notify_url"] = p.TransferNotifyURL
	p.fieldMap["creator"] = p.Creator
	p.fieldMap["updater"] = p.Updater
	p.fieldMap["create_time"] = p.CreatedAt
	p.fieldMap["update_time"] = p.UpdatedAt
	p.fieldMap["deleted"] = p.Deleted
}

func (p payApp) clone(db *gorm.DB) payApp {
	p.payAppDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p payApp) replaceDB(db *gorm.DB) payApp {
	p.payAppDo.ReplaceDB(db)
	return p
}

type payAppDo struct{ gen.DO }

type IPayAppDo interface {
	gen.SubQuery
	Debug() IPayAppDo
	WithContext(ctx context.Context) IPayAppDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPayAppDo
	WriteDB() IPayAppDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPayAppDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPayAppDo
	Not(conds ...gen.Condition) IPayAppDo
	Or(conds ...gen.Condition) IPayAppDo
	Select(conds ...field.Expr) IPayAppDo
	Where(conds ...gen.Condition) IPayAppDo
	Order(conds ...field.Expr) IPayAppDo
	Distinct(cols ...field.Expr) IPayAppDo
	Omit(cols ...field.Expr) IPayAppDo
	Join(table schema.Tabler, on ...field.Expr) IPayAppDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPayAppDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPayAppDo
	Group(cols ...field.Expr) IPayAppDo
	Having(conds ...gen.Condition) IPayAppDo
	Limit(limit int) IPayAppDo
	Offset(offset int) IPayAppDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPayAppDo
	Unscoped() IPayAppDo
	Create(values ...*pay.PayApp) error
	CreateInBatches(values []*pay.PayApp, batchSize int) error
	Save(values ...*pay.PayApp) error
	First() (*pay.PayApp, error)
	Take() (*pay.PayApp, error)
	Last() (*pay.PayApp, error)
	Find() ([]*pay.PayApp, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*pay.PayApp, err error)
	FindInBatches(result *[]*pay.PayApp, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*pay.PayApp) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPayAppDo
	Assign(attrs ...field.AssignExpr) IPayAppDo
	Joins(fields ...field.RelationField) IPayAppDo
	Preload(fields ...field.RelationField) IPayAppDo
	FirstOrInit() (*pay.PayApp, error)
	FirstOrCreate() (*pay.PayApp, error)
	FindByPage(offset int, limit int) (result []*pay.PayApp, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPayAppDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p payAppDo) Debug() IPayAppDo {
	return p.withDO(p.DO.Debug())
}

func (p payAppDo) WithContext(ctx context.Context) IPayAppDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p payAppDo) ReadDB() IPayAppDo {
	return p.Clauses(dbresolver.Read)
}

func (p payAppDo) WriteDB() IPayAppDo {
	return p.Clauses(dbresolver.Write)
}

func (p payAppDo) Session(config *gorm.Session) IPayAppDo {
	return p.withDO(p.DO.Session(config))
}

func (p payAppDo) Clauses(conds ...clause.Expression) IPayAppDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p payAppDo) Returning(value interface{}, columns ...string) IPayAppDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p payAppDo) Not(conds ...gen.Condition) IPayAppDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p payAppDo) Or(conds ...gen.Condition) IPayAppDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p payAppDo) Select(conds ...field.Expr) IPayAppDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p payAppDo) Where(conds ...gen.Condition) IPayAppDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p payAppDo) Order(conds ...field.Expr) IPayAppDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p payAppDo) Distinct(cols ...field.Expr) IPayAppDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p payAppDo) Omit(cols ...field.Expr) IPayAppDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p payAppDo) Join(table schema.Tabler, on ...field.Expr) IPayAppDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p payAppDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPayAppDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p payAppDo) RightJoin(table schema.Tabler, on ...field.Expr) IPayAppDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p payAppDo) Group(cols ...field.Expr) IPayAppDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p payAppDo) Having(conds ...gen.Condition) IPayAppDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p payAppDo) Limit(limit int) IPayAppDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p payAppDo) Offset(offset int) IPayAppDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p payAppDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPayAppDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p payAppDo) Unscoped() IPayAppDo {
	return p.withDO(p.DO.Unscoped())
}

func (p payAppDo) Create(values ...*pay.PayApp) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p payAppDo) CreateInBatches(values []*pay.PayApp, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p payAppDo) Save(values ...*pay.PayApp) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p payAppDo) First() (*pay.PayApp, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*pay.PayApp), nil
	}
}

func (p payAppDo) Take() (*pay.PayApp, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*pay.PayApp), nil
	}
}

func (p payAppDo) Last() (*pay.PayApp, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*pay.PayApp), nil
	}
}

func (p payAppDo) Find() ([]*pay.PayApp, error) {
	result, err := p.DO.Find()
	return result.([]*pay.PayApp), err
}

func (p payAppDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*pay.PayApp, err error) {
	buf := make([]*pay.PayApp, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p payAppDo) FindInBatches(result *[]*pay.PayApp, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p payAppDo) Attrs(attrs ...field.AssignExpr) IPayAppDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p payAppDo) Assign(attrs ...field.AssignExpr) IPayAppDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p payAppDo) Joins(fields ...field.RelationField) IPayAppDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p payAppDo) Preload(fields ...field.RelationField) IPayAppDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p payAppDo) FirstOrInit() (*pay.PayApp, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*pay.PayApp), nil
	}
}

func (p payAppDo) FirstOrCreate() (*pay.PayApp, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*pay.PayApp), nil
	}
}

func (p payAppDo) FindByPage(offset int, limit int) (result []*pay.PayApp, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p payAppDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p payAppDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p payAppDo) Delete(models ...*pay.PayApp) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *payAppDo) withDO(do gen.Dao) *payAppDo {
	p.DO = *do.(*gen.DO)
	return p
}
