// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend-go/internal/model/pay"
)

func newPayOrder(db *gorm.DB, opts ...gen.DOOption) payOrder {
	_payOrder := payOrder{}

	_payOrder.payOrderDo.UseDB(db, opts...)
	_payOrder.payOrderDo.UseModel(&pay.PayOrder{})

	tableName := _payOrder.payOrderDo.TableName()
	_payOrder.ALL = field.NewAsterisk(tableName)
	_payOrder.ID = field.NewInt64(tableName, "id")
	_payOrder.AppID = field.NewInt64(tableName, "app_id")
	_payOrder.ChannelID = field.NewInt64(tableName, "channel_id")
	_payOrder.ChannelCode = field.NewString(tableName, "channel_code")
	_payOrder.UserID = field.NewInt64(tableName, "user_id")
	_payOrder.UserType = field.NewInt(tableName, "user_type")
	_payOrder.MerchantOrderId = field.NewString(tableName, "merchant_order_id")
	_payOrder.Subject = field.NewString(tableName, "subject")
	_payOrder.Body = field.NewString(tableName, "body")
	_payOrder.NotifyURL = field.NewString(tableName, "notify_url")
	_payOrder.Price = field.NewInt(tableName, "price")
	_payOrder.ChannelFeeRate = field.NewFloat64(tableName, "channel_fee_rate")
	_payOrder.ChannelFeePrice = field.NewInt(tableName, "channel_fee_price")
	_payOrder.Status = field.NewInt(tableName, "status")
	_payOrder.UserIP = field.NewString(tableName, "user_ip")
	_payOrder.ExpireTime = field.NewTime(tableName, "expire_time")
	_payOrder.SuccessTime = field.NewTime(tableName, "success_time")
	_payOrder.ExtensionID = field.NewInt64(tableName, "extension_id")
	_payOrder.No = field.NewString(tableName, "no")
	_payOrder.RefundPrice = field.NewInt(tableName, "refund_price")
	_payOrder.ChannelUserID = field.NewString(tableName, "channel_user_id")
	_payOrder.ChannelOrderNo = field.NewString(tableName, "channel_order_no")
	_payOrder.Creator = field.NewString(tableName, "creator")
	_payOrder.Updater = field.NewString(tableName, "updater")
	_payOrder.CreatedAt = field.NewTime(tableName, "create_time")
	_payOrder.UpdatedAt = field.NewTime(tableName, "update_time")
	_payOrder.Deleted = field.NewField(tableName, "deleted")

	_payOrder.fillFieldMap()

	return _payOrder
}

type payOrder struct {
	payOrderDo payOrderDo

	ALL             field.Asterisk
	ID              field.Int64
	AppID           field.Int64
	ChannelID       field.Int64
	ChannelCode     field.String
	UserID          field.Int64
	UserType        field.Int
	MerchantOrderId field.String
	Subject         field.String
	Body            field.String
	NotifyURL       field.String
	Price           field.Int
	ChannelFeeRate  field.Float64
	ChannelFeePrice field.Int
	Status          field.Int
	UserIP          field.String
	ExpireTime      field.Time
	SuccessTime     field.Time
	ExtensionID     field.Int64
	No              field.String
	RefundPrice     field.Int
	ChannelUserID   field.String
	ChannelOrderNo  field.String
	Creator         field.String // 创建者
	Updater         field.String // 更新者
	CreatedAt       field.Time   // 创建时间
	UpdatedAt       field.Time   // 更新时间
	Deleted         field.Field  // 是否删除

	fieldMap map[string]field.Expr
}

func (p payOrder) Table(newTableName string) *payOrder {
	p.payOrderDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p payOrder) As(alias string) *payOrder {
	p.payOrderDo.DO = *(p.payOrderDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *payOrder) updateTableName(table string) *payOrder {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.AppID = field.NewInt64(table, "app_id")
	p.ChannelID = field.NewInt64(table, "channel_id")
	p.ChannelCode = field.NewString(table, "channel_code")
	p.UserID = field.NewInt64(table, "user_id")
	p.UserType = field.NewInt(table, "user_type")
	p.MerchantOrderId = field.NewString(table, "merchant_order_id")
	p.Subject = field.NewString(table, "subject")
	p.Body = field.NewString(table, "body")
	p.NotifyURL = field.NewString(table, "notify_url")
	p.Price = field.NewInt(table, "price")
	p.ChannelFeeRate = field.NewFloat64(table, "channel_fee_rate")
	p.ChannelFeePrice = field.NewInt(table, "channel_fee_price")
	p.Status = field.NewInt(table, "status")
	p.UserIP = field.NewString(table, "user_ip")
	p.ExpireTime = field.NewTime(table, "expire_time")
	p.SuccessTime = field.NewTime(table, "success_time")
	p.ExtensionID = field.NewInt64(table, "extension_id")
	p.No = field.NewString(table, "no")
	p.RefundPrice = field.NewInt(table, "refund_price")
	p.ChannelUserID = field.NewString(table, "channel_user_id")
	p.ChannelOrderNo = field.NewString(table, "channel_order_no")
	p.Creator = field.NewString(table, "creator")
	p.Updater = field.NewString(table, "updater")
	p.CreatedAt = field.NewTime(table, "create_time")
	p.UpdatedAt = field.NewTime(table, "update_time")
	p.Deleted = field.NewField(table, "deleted")

	p.fillFieldMap()

	return p
}

func (p *payOrder) WithContext(ctx context.Context) IPayOrderDo { return p.payOrderDo.WithContext(ctx) }

func (p payOrder) TableName() string { return p.payOrderDo.TableName() }

func (p payOrder) Alias() string { return p.payOrderDo.Alias() }

func (p payOrder) Columns(cols ...field.Expr) gen.Columns { return p.payOrderDo.Columns(cols...) }

func (p *payOrder) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *payOrder) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 27)
	p.fieldMap["id"] = p.ID
	p.fieldMap["app_id"] = p.AppID
	p.fieldMap["channel_id"] = p.ChannelID
	p.fieldMap["channel_code"] = p.ChannelCode
	p.fieldMap["user_id"] = p.UserID
	p.fieldMap["user_type"] = p.UserType
	p.fieldMap["merchant_order_id"] = p.MerchantOrderId
	p.fieldMap["subject"] = p.Subject
	p.fieldMap["body"] = p.Body
	p.fieldMap["notify_url"] = p.NotifyURL
	p.fieldMap["price"] = p.Price
	p.fieldMap["channel_fee_rate"] = p.ChannelFeeRate
	p.fieldMap["channel_fee_price"] = p.ChannelFeePrice
	p.fieldMap["status"] = p.Status
	p.fieldMap["user_ip"] = p.UserIP
	p.fieldMap["expire_time"] = p.ExpireTime
	p.fieldMap["success_time"] = p.SuccessTime
	p.fieldMap["extension_id"] = p.ExtensionID
	p.fieldMap["no"] = p.No
	p.fieldMap["refund_price"] = p.RefundPrice
	p.fieldMap["channel_user_id"] = p.ChannelUserID
	p.fieldMap["channel_order_no"] = p.ChannelOrderNo
	p.fieldMap["creator"] = p.Creator
	p.fieldMap["updater"] = p.Updater
	p.fieldMap["create_time"] = p.CreatedAt
	p.fieldMap["update_time"] = p.UpdatedAt
	p.fieldMap["deleted"] = p.Deleted
}

func (p payOrder) clone(db *gorm.DB) payOrder {
	p.payOrderDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p payOrder) replaceDB(db *gorm.DB) payOrder {
	p.payOrderDo.ReplaceDB(db)
	return p
}

type payOrderDo struct{ gen.DO }

type IPayOrderDo interface {
	gen.SubQuery
	Debug() IPayOrderDo
	WithContext(ctx context.Context) IPayOrderDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPayOrderDo
	WriteDB() IPayOrderDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPayOrderDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPayOrderDo
	Not(conds ...gen.Condition) IPayOrderDo
	Or(conds ...gen.Condition) IPayOrderDo
	Select(conds ...field.Expr) IPayOrderDo
	Where(conds ...gen.Condition) IPayOrderDo
	Order(conds ...field.Expr) IPayOrderDo
	Distinct(cols ...field.Expr) IPayOrderDo
	Omit(cols ...field.Expr) IPayOrderDo
	Join(table schema.Tabler, on ...field.Expr) IPayOrderDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPayOrderDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPayOrderDo
	Group(cols ...field.Expr) IPayOrderDo
	Having(conds ...gen.Condition) IPayOrderDo
	Limit(limit int) IPayOrderDo
	Offset(offset int) IPayOrderDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPayOrderDo
	Unscoped() IPayOrderDo
	Create(values ...*pay.PayOrder) error
	CreateInBatches(values []*pay.PayOrder, batchSize int) error
	Save(values ...*pay.PayOrder) error
	First() (*pay.PayOrder, error)
	Take() (*pay.PayOrder, error)
	Last() (*pay.PayOrder, error)
	Find() ([]*pay.PayOrder, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*pay.PayOrder, err error)
	FindInBatches(result *[]*pay.PayOrder, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*pay.PayOrder) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPayOrderDo
	Assign(attrs ...field.AssignExpr) IPayOrderDo
	Joins(fields ...field.RelationField) IPayOrderDo
	Preload(fields ...field.RelationField) IPayOrderDo
	FirstOrInit() (*pay.PayOrder, error)
	FirstOrCreate() (*pay.PayOrder, error)
	FindByPage(offset int, limit int) (result []*pay.PayOrder, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPayOrderDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p payOrderDo) Debug() IPayOrderDo {
	return p.withDO(p.DO.Debug())
}

func (p payOrderDo) WithContext(ctx context.Context) IPayOrderDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p payOrderDo) ReadDB() IPayOrderDo {
	return p.Clauses(dbresolver.Read)
}

func (p payOrderDo) WriteDB() IPayOrderDo {
	return p.Clauses(dbresolver.Write)
}

func (p payOrderDo) Session(config *gorm.Session) IPayOrderDo {
	return p.withDO(p.DO.Session(config))
}

func (p payOrderDo) Clauses(conds ...clause.Expression) IPayOrderDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p payOrderDo) Returning(value interface{}, columns ...string) IPayOrderDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p payOrderDo) Not(conds ...gen.Condition) IPayOrderDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p payOrderDo) Or(conds ...gen.Condition) IPayOrderDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p payOrderDo) Select(conds ...field.Expr) IPayOrderDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p payOrderDo) Where(conds ...gen.Condition) IPayOrderDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p payOrderDo) Order(conds ...field.Expr) IPayOrderDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p payOrderDo) Distinct(cols ...field.Expr) IPayOrderDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p payOrderDo) Omit(cols ...field.Expr) IPayOrderDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p payOrderDo) Join(table schema.Tabler, on ...field.Expr) IPayOrderDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p payOrderDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPayOrderDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p payOrderDo) RightJoin(table schema.Tabler, on ...field.Expr) IPayOrderDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p payOrderDo) Group(cols ...field.Expr) IPayOrderDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p payOrderDo) Having(conds ...gen.Condition) IPayOrderDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p payOrderDo) Limit(limit int) IPayOrderDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p payOrderDo) Offset(offset int) IPayOrderDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p payOrderDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPayOrderDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p payOrderDo) Unscoped() IPayOrderDo {
	return p.withDO(p.DO.Unscoped())
}

func (p payOrderDo) Create(values ...*pay.PayOrder) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p payOrderDo) CreateInBatches(values []*pay.PayOrder, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p payOrderDo) Save(values ...*pay.PayOrder) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p payOrderDo) First() (*pay.PayOrder, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*pay.PayOrder), nil
	}
}

func (p payOrderDo) Take() (*pay.PayOrder, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*pay.PayOrder), nil
	}
}

func (p payOrderDo) Last() (*pay.PayOrder, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*pay.PayOrder), nil
	}
}

func (p payOrderDo) Find() ([]*pay.PayOrder, error) {
	result, err := p.DO.Find()
	return result.([]*pay.PayOrder), err
}

func (p payOrderDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*pay.PayOrder, err error) {
	buf := make([]*pay.PayOrder, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p payOrderDo) FindInBatches(result *[]*pay.PayOrder, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p payOrderDo) Attrs(attrs ...field.AssignExpr) IPayOrderDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p payOrderDo) Assign(attrs ...field.AssignExpr) IPayOrderDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p payOrderDo) Joins(fields ...field.RelationField) IPayOrderDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p payOrderDo) Preload(fields ...field.RelationField) IPayOrderDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p payOrderDo) FirstOrInit() (*pay.PayOrder, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*pay.PayOrder), nil
	}
}

func (p payOrderDo) FirstOrCreate() (*pay.PayOrder, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*pay.PayOrder), nil
	}
}

func (p payOrderDo) FindByPage(offset int, limit int) (result []*pay.PayOrder, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p payOrderDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p payOrderDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p payOrderDo) Delete(models ...*pay.PayOrder) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *payOrderDo) withDO(do gen.Dao) *payOrderDo {
	p.DO = *do.(*gen.DO)
	return p
}
