// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend-go/internal/model/product"
)

func newProductSku(db *gorm.DB, opts ...gen.DOOption) productSku {
	_productSku := productSku{}

	_productSku.productSkuDo.UseDB(db, opts...)
	_productSku.productSkuDo.UseModel(&product.ProductSku{})

	tableName := _productSku.productSkuDo.TableName()
	_productSku.ALL = field.NewAsterisk(tableName)
	_productSku.ID = field.NewInt64(tableName, "id")
	_productSku.SpuID = field.NewInt64(tableName, "spu_id")
	_productSku.Properties = field.NewField(tableName, "properties")
	_productSku.Price = field.NewInt(tableName, "price")
	_productSku.MarketPrice = field.NewInt(tableName, "market_price")
	_productSku.CostPrice = field.NewInt(tableName, "cost_price")
	_productSku.BarCode = field.NewString(tableName, "bar_code")
	_productSku.PicURL = field.NewString(tableName, "pic_url")
	_productSku.Stock = field.NewInt(tableName, "stock")
	_productSku.Weight = field.NewFloat64(tableName, "weight")
	_productSku.Volume = field.NewFloat64(tableName, "volume")
	_productSku.FirstBrokeragePrice = field.NewInt(tableName, "first_brokerage_price")
	_productSku.SecondBrokeragePrice = field.NewInt(tableName, "second_brokerage_price")
	_productSku.SalesCount = field.NewInt(tableName, "sales_count")
	_productSku.Creator = field.NewString(tableName, "creator")
	_productSku.Updater = field.NewString(tableName, "updater")
	_productSku.CreatedAt = field.NewTime(tableName, "create_time")
	_productSku.UpdatedAt = field.NewTime(tableName, "update_time")
	_productSku.Deleted = field.NewField(tableName, "deleted")

	_productSku.fillFieldMap()

	return _productSku
}

type productSku struct {
	productSkuDo productSkuDo

	ALL                  field.Asterisk
	ID                   field.Int64   // 主键
	SpuID                field.Int64   // SPU编号
	Properties           field.Field   // 属性数组
	Price                field.Int     // 商品价格
	MarketPrice          field.Int     // 市场价
	CostPrice            field.Int     // 成本价
	BarCode              field.String  // 商品条码
	PicURL               field.String  // 图片地址
	Stock                field.Int     // 库存
	Weight               field.Float64 // 商品重量
	Volume               field.Float64 // 商品体积
	FirstBrokeragePrice  field.Int     // 一级分销的佣金
	SecondBrokeragePrice field.Int     // 二级分销的佣金
	SalesCount           field.Int     // 商品销量
	Creator              field.String  // 创建者
	Updater              field.String  // 更新者
	CreatedAt            field.Time    // 创建时间
	UpdatedAt            field.Time    // 更新时间
	Deleted              field.Field   // 是否删除

	fieldMap map[string]field.Expr
}

func (p productSku) Table(newTableName string) *productSku {
	p.productSkuDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p productSku) As(alias string) *productSku {
	p.productSkuDo.DO = *(p.productSkuDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *productSku) updateTableName(table string) *productSku {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.SpuID = field.NewInt64(table, "spu_id")
	p.Properties = field.NewField(table, "properties")
	p.Price = field.NewInt(table, "price")
	p.MarketPrice = field.NewInt(table, "market_price")
	p.CostPrice = field.NewInt(table, "cost_price")
	p.BarCode = field.NewString(table, "bar_code")
	p.PicURL = field.NewString(table, "pic_url")
	p.Stock = field.NewInt(table, "stock")
	p.Weight = field.NewFloat64(table, "weight")
	p.Volume = field.NewFloat64(table, "volume")
	p.FirstBrokeragePrice = field.NewInt(table, "first_brokerage_price")
	p.SecondBrokeragePrice = field.NewInt(table, "second_brokerage_price")
	p.SalesCount = field.NewInt(table, "sales_count")
	p.Creator = field.NewString(table, "creator")
	p.Updater = field.NewString(table, "updater")
	p.CreatedAt = field.NewTime(table, "create_time")
	p.UpdatedAt = field.NewTime(table, "update_time")
	p.Deleted = field.NewField(table, "deleted")

	p.fillFieldMap()

	return p
}

func (p *productSku) WithContext(ctx context.Context) IProductSkuDo {
	return p.productSkuDo.WithContext(ctx)
}

func (p productSku) TableName() string { return p.productSkuDo.TableName() }

func (p productSku) Alias() string { return p.productSkuDo.Alias() }

func (p productSku) Columns(cols ...field.Expr) gen.Columns { return p.productSkuDo.Columns(cols...) }

func (p *productSku) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *productSku) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 19)
	p.fieldMap["id"] = p.ID
	p.fieldMap["spu_id"] = p.SpuID
	p.fieldMap["properties"] = p.Properties
	p.fieldMap["price"] = p.Price
	p.fieldMap["market_price"] = p.MarketPrice
	p.fieldMap["cost_price"] = p.CostPrice
	p.fieldMap["bar_code"] = p.BarCode
	p.fieldMap["pic_url"] = p.PicURL
	p.fieldMap["stock"] = p.Stock
	p.fieldMap["weight"] = p.Weight
	p.fieldMap["volume"] = p.Volume
	p.fieldMap["first_brokerage_price"] = p.FirstBrokeragePrice
	p.fieldMap["second_brokerage_price"] = p.SecondBrokeragePrice
	p.fieldMap["sales_count"] = p.SalesCount
	p.fieldMap["creator"] = p.Creator
	p.fieldMap["updater"] = p.Updater
	p.fieldMap["create_time"] = p.CreatedAt
	p.fieldMap["update_time"] = p.UpdatedAt
	p.fieldMap["deleted"] = p.Deleted
}

func (p productSku) clone(db *gorm.DB) productSku {
	p.productSkuDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p productSku) replaceDB(db *gorm.DB) productSku {
	p.productSkuDo.ReplaceDB(db)
	return p
}

type productSkuDo struct{ gen.DO }

type IProductSkuDo interface {
	gen.SubQuery
	Debug() IProductSkuDo
	WithContext(ctx context.Context) IProductSkuDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IProductSkuDo
	WriteDB() IProductSkuDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IProductSkuDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IProductSkuDo
	Not(conds ...gen.Condition) IProductSkuDo
	Or(conds ...gen.Condition) IProductSkuDo
	Select(conds ...field.Expr) IProductSkuDo
	Where(conds ...gen.Condition) IProductSkuDo
	Order(conds ...field.Expr) IProductSkuDo
	Distinct(cols ...field.Expr) IProductSkuDo
	Omit(cols ...field.Expr) IProductSkuDo
	Join(table schema.Tabler, on ...field.Expr) IProductSkuDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IProductSkuDo
	RightJoin(table schema.Tabler, on ...field.Expr) IProductSkuDo
	Group(cols ...field.Expr) IProductSkuDo
	Having(conds ...gen.Condition) IProductSkuDo
	Limit(limit int) IProductSkuDo
	Offset(offset int) IProductSkuDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IProductSkuDo
	Unscoped() IProductSkuDo
	Create(values ...*product.ProductSku) error
	CreateInBatches(values []*product.ProductSku, batchSize int) error
	Save(values ...*product.ProductSku) error
	First() (*product.ProductSku, error)
	Take() (*product.ProductSku, error)
	Last() (*product.ProductSku, error)
	Find() ([]*product.ProductSku, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*product.ProductSku, err error)
	FindInBatches(result *[]*product.ProductSku, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*product.ProductSku) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IProductSkuDo
	Assign(attrs ...field.AssignExpr) IProductSkuDo
	Joins(fields ...field.RelationField) IProductSkuDo
	Preload(fields ...field.RelationField) IProductSkuDo
	FirstOrInit() (*product.ProductSku, error)
	FirstOrCreate() (*product.ProductSku, error)
	FindByPage(offset int, limit int) (result []*product.ProductSku, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IProductSkuDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p productSkuDo) Debug() IProductSkuDo {
	return p.withDO(p.DO.Debug())
}

func (p productSkuDo) WithContext(ctx context.Context) IProductSkuDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p productSkuDo) ReadDB() IProductSkuDo {
	return p.Clauses(dbresolver.Read)
}

func (p productSkuDo) WriteDB() IProductSkuDo {
	return p.Clauses(dbresolver.Write)
}

func (p productSkuDo) Session(config *gorm.Session) IProductSkuDo {
	return p.withDO(p.DO.Session(config))
}

func (p productSkuDo) Clauses(conds ...clause.Expression) IProductSkuDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p productSkuDo) Returning(value interface{}, columns ...string) IProductSkuDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p productSkuDo) Not(conds ...gen.Condition) IProductSkuDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p productSkuDo) Or(conds ...gen.Condition) IProductSkuDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p productSkuDo) Select(conds ...field.Expr) IProductSkuDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p productSkuDo) Where(conds ...gen.Condition) IProductSkuDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p productSkuDo) Order(conds ...field.Expr) IProductSkuDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p productSkuDo) Distinct(cols ...field.Expr) IProductSkuDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p productSkuDo) Omit(cols ...field.Expr) IProductSkuDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p productSkuDo) Join(table schema.Tabler, on ...field.Expr) IProductSkuDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p productSkuDo) LeftJoin(table schema.Tabler, on ...field.Expr) IProductSkuDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p productSkuDo) RightJoin(table schema.Tabler, on ...field.Expr) IProductSkuDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p productSkuDo) Group(cols ...field.Expr) IProductSkuDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p productSkuDo) Having(conds ...gen.Condition) IProductSkuDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p productSkuDo) Limit(limit int) IProductSkuDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p productSkuDo) Offset(offset int) IProductSkuDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p productSkuDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IProductSkuDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p productSkuDo) Unscoped() IProductSkuDo {
	return p.withDO(p.DO.Unscoped())
}

func (p productSkuDo) Create(values ...*product.ProductSku) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p productSkuDo) CreateInBatches(values []*product.ProductSku, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p productSkuDo) Save(values ...*product.ProductSku) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p productSkuDo) First() (*product.ProductSku, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*product.ProductSku), nil
	}
}

func (p productSkuDo) Take() (*product.ProductSku, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*product.ProductSku), nil
	}
}

func (p productSkuDo) Last() (*product.ProductSku, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*product.ProductSku), nil
	}
}

func (p productSkuDo) Find() ([]*product.ProductSku, error) {
	result, err := p.DO.Find()
	return result.([]*product.ProductSku), err
}

func (p productSkuDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*product.ProductSku, err error) {
	buf := make([]*product.ProductSku, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p productSkuDo) FindInBatches(result *[]*product.ProductSku, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p productSkuDo) Attrs(attrs ...field.AssignExpr) IProductSkuDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p productSkuDo) Assign(attrs ...field.AssignExpr) IProductSkuDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p productSkuDo) Joins(fields ...field.RelationField) IProductSkuDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p productSkuDo) Preload(fields ...field.RelationField) IProductSkuDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p productSkuDo) FirstOrInit() (*product.ProductSku, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*product.ProductSku), nil
	}
}

func (p productSkuDo) FirstOrCreate() (*product.ProductSku, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*product.ProductSku), nil
	}
}

func (p productSkuDo) FindByPage(offset int, limit int) (result []*product.ProductSku, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p productSkuDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p productSkuDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p productSkuDo) Delete(models ...*product.ProductSku) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *productSkuDo) withDO(do gen.Dao) *productSkuDo {
	p.DO = *do.(*gen.DO)
	return p
}
