// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend-go/internal/model/product"
)

func newProductCategory(db *gorm.DB, opts ...gen.DOOption) productCategory {
	_productCategory := productCategory{}

	_productCategory.productCategoryDo.UseDB(db, opts...)
	_productCategory.productCategoryDo.UseModel(&product.ProductCategory{})

	tableName := _productCategory.productCategoryDo.TableName()
	_productCategory.ALL = field.NewAsterisk(tableName)
	_productCategory.ID = field.NewInt64(tableName, "id")
	_productCategory.ParentID = field.NewInt64(tableName, "parent_id")
	_productCategory.Name = field.NewString(tableName, "name")
	_productCategory.PicURL = field.NewString(tableName, "pic_url")
	_productCategory.Sort = field.NewInt32(tableName, "sort")
	_productCategory.Status = field.NewInt32(tableName, "status")
	_productCategory.Description = field.NewString(tableName, "description")
	_productCategory.Creator = field.NewString(tableName, "creator")
	_productCategory.Updater = field.NewString(tableName, "updater")
	_productCategory.CreatedAt = field.NewTime(tableName, "create_time")
	_productCategory.UpdatedAt = field.NewTime(tableName, "update_time")
	_productCategory.Deleted = field.NewField(tableName, "deleted")

	_productCategory.fillFieldMap()

	return _productCategory
}

type productCategory struct {
	productCategoryDo productCategoryDo

	ALL         field.Asterisk
	ID          field.Int64  // 分类编号
	ParentID    field.Int64  // 父分类编号
	Name        field.String // 分类名称
	PicURL      field.String // 移动端分类图
	Sort        field.Int32  // 分类排序
	Status      field.Int32  // 开启状态
	Description field.String // 分类描述
	Creator     field.String // 创建者
	Updater     field.String // 更新者
	CreatedAt   field.Time   // 创建时间
	UpdatedAt   field.Time   // 更新时间
	Deleted     field.Field  // 是否删除

	fieldMap map[string]field.Expr
}

func (p productCategory) Table(newTableName string) *productCategory {
	p.productCategoryDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p productCategory) As(alias string) *productCategory {
	p.productCategoryDo.DO = *(p.productCategoryDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *productCategory) updateTableName(table string) *productCategory {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.ParentID = field.NewInt64(table, "parent_id")
	p.Name = field.NewString(table, "name")
	p.PicURL = field.NewString(table, "pic_url")
	p.Sort = field.NewInt32(table, "sort")
	p.Status = field.NewInt32(table, "status")
	p.Description = field.NewString(table, "description")
	p.Creator = field.NewString(table, "creator")
	p.Updater = field.NewString(table, "updater")
	p.CreatedAt = field.NewTime(table, "create_time")
	p.UpdatedAt = field.NewTime(table, "update_time")
	p.Deleted = field.NewField(table, "deleted")

	p.fillFieldMap()

	return p
}

func (p *productCategory) WithContext(ctx context.Context) IProductCategoryDo {
	return p.productCategoryDo.WithContext(ctx)
}

func (p productCategory) TableName() string { return p.productCategoryDo.TableName() }

func (p productCategory) Alias() string { return p.productCategoryDo.Alias() }

func (p productCategory) Columns(cols ...field.Expr) gen.Columns {
	return p.productCategoryDo.Columns(cols...)
}

func (p *productCategory) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *productCategory) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 12)
	p.fieldMap["id"] = p.ID
	p.fieldMap["parent_id"] = p.ParentID
	p.fieldMap["name"] = p.Name
	p.fieldMap["pic_url"] = p.PicURL
	p.fieldMap["sort"] = p.Sort
	p.fieldMap["status"] = p.Status
	p.fieldMap["description"] = p.Description
	p.fieldMap["creator"] = p.Creator
	p.fieldMap["updater"] = p.Updater
	p.fieldMap["create_time"] = p.CreatedAt
	p.fieldMap["update_time"] = p.UpdatedAt
	p.fieldMap["deleted"] = p.Deleted
}

func (p productCategory) clone(db *gorm.DB) productCategory {
	p.productCategoryDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p productCategory) replaceDB(db *gorm.DB) productCategory {
	p.productCategoryDo.ReplaceDB(db)
	return p
}

type productCategoryDo struct{ gen.DO }

type IProductCategoryDo interface {
	gen.SubQuery
	Debug() IProductCategoryDo
	WithContext(ctx context.Context) IProductCategoryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IProductCategoryDo
	WriteDB() IProductCategoryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IProductCategoryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IProductCategoryDo
	Not(conds ...gen.Condition) IProductCategoryDo
	Or(conds ...gen.Condition) IProductCategoryDo
	Select(conds ...field.Expr) IProductCategoryDo
	Where(conds ...gen.Condition) IProductCategoryDo
	Order(conds ...field.Expr) IProductCategoryDo
	Distinct(cols ...field.Expr) IProductCategoryDo
	Omit(cols ...field.Expr) IProductCategoryDo
	Join(table schema.Tabler, on ...field.Expr) IProductCategoryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IProductCategoryDo
	RightJoin(table schema.Tabler, on ...field.Expr) IProductCategoryDo
	Group(cols ...field.Expr) IProductCategoryDo
	Having(conds ...gen.Condition) IProductCategoryDo
	Limit(limit int) IProductCategoryDo
	Offset(offset int) IProductCategoryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IProductCategoryDo
	Unscoped() IProductCategoryDo
	Create(values ...*product.ProductCategory) error
	CreateInBatches(values []*product.ProductCategory, batchSize int) error
	Save(values ...*product.ProductCategory) error
	First() (*product.ProductCategory, error)
	Take() (*product.ProductCategory, error)
	Last() (*product.ProductCategory, error)
	Find() ([]*product.ProductCategory, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*product.ProductCategory, err error)
	FindInBatches(result *[]*product.ProductCategory, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*product.ProductCategory) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IProductCategoryDo
	Assign(attrs ...field.AssignExpr) IProductCategoryDo
	Joins(fields ...field.RelationField) IProductCategoryDo
	Preload(fields ...field.RelationField) IProductCategoryDo
	FirstOrInit() (*product.ProductCategory, error)
	FirstOrCreate() (*product.ProductCategory, error)
	FindByPage(offset int, limit int) (result []*product.ProductCategory, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IProductCategoryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p productCategoryDo) Debug() IProductCategoryDo {
	return p.withDO(p.DO.Debug())
}

func (p productCategoryDo) WithContext(ctx context.Context) IProductCategoryDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p productCategoryDo) ReadDB() IProductCategoryDo {
	return p.Clauses(dbresolver.Read)
}

func (p productCategoryDo) WriteDB() IProductCategoryDo {
	return p.Clauses(dbresolver.Write)
}

func (p productCategoryDo) Session(config *gorm.Session) IProductCategoryDo {
	return p.withDO(p.DO.Session(config))
}

func (p productCategoryDo) Clauses(conds ...clause.Expression) IProductCategoryDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p productCategoryDo) Returning(value interface{}, columns ...string) IProductCategoryDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p productCategoryDo) Not(conds ...gen.Condition) IProductCategoryDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p productCategoryDo) Or(conds ...gen.Condition) IProductCategoryDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p productCategoryDo) Select(conds ...field.Expr) IProductCategoryDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p productCategoryDo) Where(conds ...gen.Condition) IProductCategoryDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p productCategoryDo) Order(conds ...field.Expr) IProductCategoryDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p productCategoryDo) Distinct(cols ...field.Expr) IProductCategoryDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p productCategoryDo) Omit(cols ...field.Expr) IProductCategoryDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p productCategoryDo) Join(table schema.Tabler, on ...field.Expr) IProductCategoryDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p productCategoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) IProductCategoryDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p productCategoryDo) RightJoin(table schema.Tabler, on ...field.Expr) IProductCategoryDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p productCategoryDo) Group(cols ...field.Expr) IProductCategoryDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p productCategoryDo) Having(conds ...gen.Condition) IProductCategoryDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p productCategoryDo) Limit(limit int) IProductCategoryDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p productCategoryDo) Offset(offset int) IProductCategoryDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p productCategoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IProductCategoryDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p productCategoryDo) Unscoped() IProductCategoryDo {
	return p.withDO(p.DO.Unscoped())
}

func (p productCategoryDo) Create(values ...*product.ProductCategory) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p productCategoryDo) CreateInBatches(values []*product.ProductCategory, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p productCategoryDo) Save(values ...*product.ProductCategory) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p productCategoryDo) First() (*product.ProductCategory, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*product.ProductCategory), nil
	}
}

func (p productCategoryDo) Take() (*product.ProductCategory, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*product.ProductCategory), nil
	}
}

func (p productCategoryDo) Last() (*product.ProductCategory, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*product.ProductCategory), nil
	}
}

func (p productCategoryDo) Find() ([]*product.ProductCategory, error) {
	result, err := p.DO.Find()
	return result.([]*product.ProductCategory), err
}

func (p productCategoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*product.ProductCategory, err error) {
	buf := make([]*product.ProductCategory, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p productCategoryDo) FindInBatches(result *[]*product.ProductCategory, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p productCategoryDo) Attrs(attrs ...field.AssignExpr) IProductCategoryDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p productCategoryDo) Assign(attrs ...field.AssignExpr) IProductCategoryDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p productCategoryDo) Joins(fields ...field.RelationField) IProductCategoryDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p productCategoryDo) Preload(fields ...field.RelationField) IProductCategoryDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p productCategoryDo) FirstOrInit() (*product.ProductCategory, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*product.ProductCategory), nil
	}
}

func (p productCategoryDo) FirstOrCreate() (*product.ProductCategory, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*product.ProductCategory), nil
	}
}

func (p productCategoryDo) FindByPage(offset int, limit int) (result []*product.ProductCategory, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p productCategoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p productCategoryDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p productCategoryDo) Delete(models ...*product.ProductCategory) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *productCategoryDo) withDO(do gen.Dao) *productCategoryDo {
	p.DO = *do.(*gen.DO)
	return p
}
