// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend-go/internal/model/product"
)

func newProductPropertyValue(db *gorm.DB, opts ...gen.DOOption) productPropertyValue {
	_productPropertyValue := productPropertyValue{}

	_productPropertyValue.productPropertyValueDo.UseDB(db, opts...)
	_productPropertyValue.productPropertyValueDo.UseModel(&product.ProductPropertyValue{})

	tableName := _productPropertyValue.productPropertyValueDo.TableName()
	_productPropertyValue.ALL = field.NewAsterisk(tableName)
	_productPropertyValue.ID = field.NewInt64(tableName, "id")
	_productPropertyValue.PropertyID = field.NewInt64(tableName, "property_id")
	_productPropertyValue.Name = field.NewString(tableName, "name")
	_productPropertyValue.Remark = field.NewString(tableName, "remark")
	_productPropertyValue.Creator = field.NewString(tableName, "creator")
	_productPropertyValue.Updater = field.NewString(tableName, "updater")
	_productPropertyValue.CreatedAt = field.NewTime(tableName, "create_time")
	_productPropertyValue.UpdatedAt = field.NewTime(tableName, "update_time")
	_productPropertyValue.Deleted = field.NewField(tableName, "deleted")

	_productPropertyValue.fillFieldMap()

	return _productPropertyValue
}

type productPropertyValue struct {
	productPropertyValueDo productPropertyValueDo

	ALL        field.Asterisk
	ID         field.Int64  // 主键
	PropertyID field.Int64  // 属性项的编号
	Name       field.String // 名称
	Remark     field.String // 备注
	Creator    field.String // 创建者
	Updater    field.String // 更新者
	CreatedAt  field.Time   // 创建时间
	UpdatedAt  field.Time   // 更新时间
	Deleted    field.Field  // 是否删除

	fieldMap map[string]field.Expr
}

func (p productPropertyValue) Table(newTableName string) *productPropertyValue {
	p.productPropertyValueDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p productPropertyValue) As(alias string) *productPropertyValue {
	p.productPropertyValueDo.DO = *(p.productPropertyValueDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *productPropertyValue) updateTableName(table string) *productPropertyValue {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.PropertyID = field.NewInt64(table, "property_id")
	p.Name = field.NewString(table, "name")
	p.Remark = field.NewString(table, "remark")
	p.Creator = field.NewString(table, "creator")
	p.Updater = field.NewString(table, "updater")
	p.CreatedAt = field.NewTime(table, "create_time")
	p.UpdatedAt = field.NewTime(table, "update_time")
	p.Deleted = field.NewField(table, "deleted")

	p.fillFieldMap()

	return p
}

func (p *productPropertyValue) WithContext(ctx context.Context) IProductPropertyValueDo {
	return p.productPropertyValueDo.WithContext(ctx)
}

func (p productPropertyValue) TableName() string { return p.productPropertyValueDo.TableName() }

func (p productPropertyValue) Alias() string { return p.productPropertyValueDo.Alias() }

func (p productPropertyValue) Columns(cols ...field.Expr) gen.Columns {
	return p.productPropertyValueDo.Columns(cols...)
}

func (p *productPropertyValue) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *productPropertyValue) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 9)
	p.fieldMap["id"] = p.ID
	p.fieldMap["property_id"] = p.PropertyID
	p.fieldMap["name"] = p.Name
	p.fieldMap["remark"] = p.Remark
	p.fieldMap["creator"] = p.Creator
	p.fieldMap["updater"] = p.Updater
	p.fieldMap["create_time"] = p.CreatedAt
	p.fieldMap["update_time"] = p.UpdatedAt
	p.fieldMap["deleted"] = p.Deleted
}

func (p productPropertyValue) clone(db *gorm.DB) productPropertyValue {
	p.productPropertyValueDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p productPropertyValue) replaceDB(db *gorm.DB) productPropertyValue {
	p.productPropertyValueDo.ReplaceDB(db)
	return p
}

type productPropertyValueDo struct{ gen.DO }

type IProductPropertyValueDo interface {
	gen.SubQuery
	Debug() IProductPropertyValueDo
	WithContext(ctx context.Context) IProductPropertyValueDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IProductPropertyValueDo
	WriteDB() IProductPropertyValueDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IProductPropertyValueDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IProductPropertyValueDo
	Not(conds ...gen.Condition) IProductPropertyValueDo
	Or(conds ...gen.Condition) IProductPropertyValueDo
	Select(conds ...field.Expr) IProductPropertyValueDo
	Where(conds ...gen.Condition) IProductPropertyValueDo
	Order(conds ...field.Expr) IProductPropertyValueDo
	Distinct(cols ...field.Expr) IProductPropertyValueDo
	Omit(cols ...field.Expr) IProductPropertyValueDo
	Join(table schema.Tabler, on ...field.Expr) IProductPropertyValueDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IProductPropertyValueDo
	RightJoin(table schema.Tabler, on ...field.Expr) IProductPropertyValueDo
	Group(cols ...field.Expr) IProductPropertyValueDo
	Having(conds ...gen.Condition) IProductPropertyValueDo
	Limit(limit int) IProductPropertyValueDo
	Offset(offset int) IProductPropertyValueDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IProductPropertyValueDo
	Unscoped() IProductPropertyValueDo
	Create(values ...*product.ProductPropertyValue) error
	CreateInBatches(values []*product.ProductPropertyValue, batchSize int) error
	Save(values ...*product.ProductPropertyValue) error
	First() (*product.ProductPropertyValue, error)
	Take() (*product.ProductPropertyValue, error)
	Last() (*product.ProductPropertyValue, error)
	Find() ([]*product.ProductPropertyValue, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*product.ProductPropertyValue, err error)
	FindInBatches(result *[]*product.ProductPropertyValue, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*product.ProductPropertyValue) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IProductPropertyValueDo
	Assign(attrs ...field.AssignExpr) IProductPropertyValueDo
	Joins(fields ...field.RelationField) IProductPropertyValueDo
	Preload(fields ...field.RelationField) IProductPropertyValueDo
	FirstOrInit() (*product.ProductPropertyValue, error)
	FirstOrCreate() (*product.ProductPropertyValue, error)
	FindByPage(offset int, limit int) (result []*product.ProductPropertyValue, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IProductPropertyValueDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p productPropertyValueDo) Debug() IProductPropertyValueDo {
	return p.withDO(p.DO.Debug())
}

func (p productPropertyValueDo) WithContext(ctx context.Context) IProductPropertyValueDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p productPropertyValueDo) ReadDB() IProductPropertyValueDo {
	return p.Clauses(dbresolver.Read)
}

func (p productPropertyValueDo) WriteDB() IProductPropertyValueDo {
	return p.Clauses(dbresolver.Write)
}

func (p productPropertyValueDo) Session(config *gorm.Session) IProductPropertyValueDo {
	return p.withDO(p.DO.Session(config))
}

func (p productPropertyValueDo) Clauses(conds ...clause.Expression) IProductPropertyValueDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p productPropertyValueDo) Returning(value interface{}, columns ...string) IProductPropertyValueDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p productPropertyValueDo) Not(conds ...gen.Condition) IProductPropertyValueDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p productPropertyValueDo) Or(conds ...gen.Condition) IProductPropertyValueDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p productPropertyValueDo) Select(conds ...field.Expr) IProductPropertyValueDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p productPropertyValueDo) Where(conds ...gen.Condition) IProductPropertyValueDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p productPropertyValueDo) Order(conds ...field.Expr) IProductPropertyValueDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p productPropertyValueDo) Distinct(cols ...field.Expr) IProductPropertyValueDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p productPropertyValueDo) Omit(cols ...field.Expr) IProductPropertyValueDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p productPropertyValueDo) Join(table schema.Tabler, on ...field.Expr) IProductPropertyValueDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p productPropertyValueDo) LeftJoin(table schema.Tabler, on ...field.Expr) IProductPropertyValueDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p productPropertyValueDo) RightJoin(table schema.Tabler, on ...field.Expr) IProductPropertyValueDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p productPropertyValueDo) Group(cols ...field.Expr) IProductPropertyValueDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p productPropertyValueDo) Having(conds ...gen.Condition) IProductPropertyValueDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p productPropertyValueDo) Limit(limit int) IProductPropertyValueDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p productPropertyValueDo) Offset(offset int) IProductPropertyValueDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p productPropertyValueDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IProductPropertyValueDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p productPropertyValueDo) Unscoped() IProductPropertyValueDo {
	return p.withDO(p.DO.Unscoped())
}

func (p productPropertyValueDo) Create(values ...*product.ProductPropertyValue) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p productPropertyValueDo) CreateInBatches(values []*product.ProductPropertyValue, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p productPropertyValueDo) Save(values ...*product.ProductPropertyValue) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p productPropertyValueDo) First() (*product.ProductPropertyValue, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*product.ProductPropertyValue), nil
	}
}

func (p productPropertyValueDo) Take() (*product.ProductPropertyValue, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*product.ProductPropertyValue), nil
	}
}

func (p productPropertyValueDo) Last() (*product.ProductPropertyValue, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*product.ProductPropertyValue), nil
	}
}

func (p productPropertyValueDo) Find() ([]*product.ProductPropertyValue, error) {
	result, err := p.DO.Find()
	return result.([]*product.ProductPropertyValue), err
}

func (p productPropertyValueDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*product.ProductPropertyValue, err error) {
	buf := make([]*product.ProductPropertyValue, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p productPropertyValueDo) FindInBatches(result *[]*product.ProductPropertyValue, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p productPropertyValueDo) Attrs(attrs ...field.AssignExpr) IProductPropertyValueDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p productPropertyValueDo) Assign(attrs ...field.AssignExpr) IProductPropertyValueDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p productPropertyValueDo) Joins(fields ...field.RelationField) IProductPropertyValueDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p productPropertyValueDo) Preload(fields ...field.RelationField) IProductPropertyValueDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p productPropertyValueDo) FirstOrInit() (*product.ProductPropertyValue, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*product.ProductPropertyValue), nil
	}
}

func (p productPropertyValueDo) FirstOrCreate() (*product.ProductPropertyValue, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*product.ProductPropertyValue), nil
	}
}

func (p productPropertyValueDo) FindByPage(offset int, limit int) (result []*product.ProductPropertyValue, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p productPropertyValueDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p productPropertyValueDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p productPropertyValueDo) Delete(models ...*product.ProductPropertyValue) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *productPropertyValueDo) withDO(do gen.Dao) *productPropertyValueDo {
	p.DO = *do.(*gen.DO)
	return p
}
