// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend-go/internal/model/product"
)

func newProductProperty(db *gorm.DB, opts ...gen.DOOption) productProperty {
	_productProperty := productProperty{}

	_productProperty.productPropertyDo.UseDB(db, opts...)
	_productProperty.productPropertyDo.UseModel(&product.ProductProperty{})

	tableName := _productProperty.productPropertyDo.TableName()
	_productProperty.ALL = field.NewAsterisk(tableName)
	_productProperty.ID = field.NewInt64(tableName, "id")
	_productProperty.Name = field.NewString(tableName, "name")
	_productProperty.Remark = field.NewString(tableName, "remark")
	_productProperty.Creator = field.NewString(tableName, "creator")
	_productProperty.Updater = field.NewString(tableName, "updater")
	_productProperty.CreatedAt = field.NewTime(tableName, "create_time")
	_productProperty.UpdatedAt = field.NewTime(tableName, "update_time")
	_productProperty.Deleted = field.NewField(tableName, "deleted")

	_productProperty.fillFieldMap()

	return _productProperty
}

type productProperty struct {
	productPropertyDo productPropertyDo

	ALL       field.Asterisk
	ID        field.Int64  // 主键
	Name      field.String // 名称
	Remark    field.String // 备注
	Creator   field.String // 创建者
	Updater   field.String // 更新者
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 更新时间
	Deleted   field.Field  // 是否删除

	fieldMap map[string]field.Expr
}

func (p productProperty) Table(newTableName string) *productProperty {
	p.productPropertyDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p productProperty) As(alias string) *productProperty {
	p.productPropertyDo.DO = *(p.productPropertyDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *productProperty) updateTableName(table string) *productProperty {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.Name = field.NewString(table, "name")
	p.Remark = field.NewString(table, "remark")
	p.Creator = field.NewString(table, "creator")
	p.Updater = field.NewString(table, "updater")
	p.CreatedAt = field.NewTime(table, "create_time")
	p.UpdatedAt = field.NewTime(table, "update_time")
	p.Deleted = field.NewField(table, "deleted")

	p.fillFieldMap()

	return p
}

func (p *productProperty) WithContext(ctx context.Context) IProductPropertyDo {
	return p.productPropertyDo.WithContext(ctx)
}

func (p productProperty) TableName() string { return p.productPropertyDo.TableName() }

func (p productProperty) Alias() string { return p.productPropertyDo.Alias() }

func (p productProperty) Columns(cols ...field.Expr) gen.Columns {
	return p.productPropertyDo.Columns(cols...)
}

func (p *productProperty) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *productProperty) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 8)
	p.fieldMap["id"] = p.ID
	p.fieldMap["name"] = p.Name
	p.fieldMap["remark"] = p.Remark
	p.fieldMap["creator"] = p.Creator
	p.fieldMap["updater"] = p.Updater
	p.fieldMap["create_time"] = p.CreatedAt
	p.fieldMap["update_time"] = p.UpdatedAt
	p.fieldMap["deleted"] = p.Deleted
}

func (p productProperty) clone(db *gorm.DB) productProperty {
	p.productPropertyDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p productProperty) replaceDB(db *gorm.DB) productProperty {
	p.productPropertyDo.ReplaceDB(db)
	return p
}

type productPropertyDo struct{ gen.DO }

type IProductPropertyDo interface {
	gen.SubQuery
	Debug() IProductPropertyDo
	WithContext(ctx context.Context) IProductPropertyDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IProductPropertyDo
	WriteDB() IProductPropertyDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IProductPropertyDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IProductPropertyDo
	Not(conds ...gen.Condition) IProductPropertyDo
	Or(conds ...gen.Condition) IProductPropertyDo
	Select(conds ...field.Expr) IProductPropertyDo
	Where(conds ...gen.Condition) IProductPropertyDo
	Order(conds ...field.Expr) IProductPropertyDo
	Distinct(cols ...field.Expr) IProductPropertyDo
	Omit(cols ...field.Expr) IProductPropertyDo
	Join(table schema.Tabler, on ...field.Expr) IProductPropertyDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IProductPropertyDo
	RightJoin(table schema.Tabler, on ...field.Expr) IProductPropertyDo
	Group(cols ...field.Expr) IProductPropertyDo
	Having(conds ...gen.Condition) IProductPropertyDo
	Limit(limit int) IProductPropertyDo
	Offset(offset int) IProductPropertyDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IProductPropertyDo
	Unscoped() IProductPropertyDo
	Create(values ...*product.ProductProperty) error
	CreateInBatches(values []*product.ProductProperty, batchSize int) error
	Save(values ...*product.ProductProperty) error
	First() (*product.ProductProperty, error)
	Take() (*product.ProductProperty, error)
	Last() (*product.ProductProperty, error)
	Find() ([]*product.ProductProperty, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*product.ProductProperty, err error)
	FindInBatches(result *[]*product.ProductProperty, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*product.ProductProperty) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IProductPropertyDo
	Assign(attrs ...field.AssignExpr) IProductPropertyDo
	Joins(fields ...field.RelationField) IProductPropertyDo
	Preload(fields ...field.RelationField) IProductPropertyDo
	FirstOrInit() (*product.ProductProperty, error)
	FirstOrCreate() (*product.ProductProperty, error)
	FindByPage(offset int, limit int) (result []*product.ProductProperty, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IProductPropertyDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p productPropertyDo) Debug() IProductPropertyDo {
	return p.withDO(p.DO.Debug())
}

func (p productPropertyDo) WithContext(ctx context.Context) IProductPropertyDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p productPropertyDo) ReadDB() IProductPropertyDo {
	return p.Clauses(dbresolver.Read)
}

func (p productPropertyDo) WriteDB() IProductPropertyDo {
	return p.Clauses(dbresolver.Write)
}

func (p productPropertyDo) Session(config *gorm.Session) IProductPropertyDo {
	return p.withDO(p.DO.Session(config))
}

func (p productPropertyDo) Clauses(conds ...clause.Expression) IProductPropertyDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p productPropertyDo) Returning(value interface{}, columns ...string) IProductPropertyDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p productPropertyDo) Not(conds ...gen.Condition) IProductPropertyDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p productPropertyDo) Or(conds ...gen.Condition) IProductPropertyDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p productPropertyDo) Select(conds ...field.Expr) IProductPropertyDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p productPropertyDo) Where(conds ...gen.Condition) IProductPropertyDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p productPropertyDo) Order(conds ...field.Expr) IProductPropertyDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p productPropertyDo) Distinct(cols ...field.Expr) IProductPropertyDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p productPropertyDo) Omit(cols ...field.Expr) IProductPropertyDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p productPropertyDo) Join(table schema.Tabler, on ...field.Expr) IProductPropertyDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p productPropertyDo) LeftJoin(table schema.Tabler, on ...field.Expr) IProductPropertyDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p productPropertyDo) RightJoin(table schema.Tabler, on ...field.Expr) IProductPropertyDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p productPropertyDo) Group(cols ...field.Expr) IProductPropertyDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p productPropertyDo) Having(conds ...gen.Condition) IProductPropertyDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p productPropertyDo) Limit(limit int) IProductPropertyDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p productPropertyDo) Offset(offset int) IProductPropertyDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p productPropertyDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IProductPropertyDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p productPropertyDo) Unscoped() IProductPropertyDo {
	return p.withDO(p.DO.Unscoped())
}

func (p productPropertyDo) Create(values ...*product.ProductProperty) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p productPropertyDo) CreateInBatches(values []*product.ProductProperty, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p productPropertyDo) Save(values ...*product.ProductProperty) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p productPropertyDo) First() (*product.ProductProperty, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*product.ProductProperty), nil
	}
}

func (p productPropertyDo) Take() (*product.ProductProperty, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*product.ProductProperty), nil
	}
}

func (p productPropertyDo) Last() (*product.ProductProperty, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*product.ProductProperty), nil
	}
}

func (p productPropertyDo) Find() ([]*product.ProductProperty, error) {
	result, err := p.DO.Find()
	return result.([]*product.ProductProperty), err
}

func (p productPropertyDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*product.ProductProperty, err error) {
	buf := make([]*product.ProductProperty, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p productPropertyDo) FindInBatches(result *[]*product.ProductProperty, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p productPropertyDo) Attrs(attrs ...field.AssignExpr) IProductPropertyDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p productPropertyDo) Assign(attrs ...field.AssignExpr) IProductPropertyDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p productPropertyDo) Joins(fields ...field.RelationField) IProductPropertyDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p productPropertyDo) Preload(fields ...field.RelationField) IProductPropertyDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p productPropertyDo) FirstOrInit() (*product.ProductProperty, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*product.ProductProperty), nil
	}
}

func (p productPropertyDo) FirstOrCreate() (*product.ProductProperty, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*product.ProductProperty), nil
	}
}

func (p productPropertyDo) FindByPage(offset int, limit int) (result []*product.ProductProperty, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p productPropertyDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p productPropertyDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p productPropertyDo) Delete(models ...*product.ProductProperty) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *productPropertyDo) withDO(do gen.Dao) *productPropertyDo {
	p.DO = *do.(*gen.DO)
	return p
}
