// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend-go/internal/model/promotion"
)

func newPromotionBargainRecord(db *gorm.DB, opts ...gen.DOOption) promotionBargainRecord {
	_promotionBargainRecord := promotionBargainRecord{}

	_promotionBargainRecord.promotionBargainRecordDo.UseDB(db, opts...)
	_promotionBargainRecord.promotionBargainRecordDo.UseModel(&promotion.PromotionBargainRecord{})

	tableName := _promotionBargainRecord.promotionBargainRecordDo.TableName()
	_promotionBargainRecord.ALL = field.NewAsterisk(tableName)
	_promotionBargainRecord.ID = field.NewInt64(tableName, "id")
	_promotionBargainRecord.UserID = field.NewInt64(tableName, "user_id")
	_promotionBargainRecord.ActivityID = field.NewInt64(tableName, "activity_id")
	_promotionBargainRecord.SpuID = field.NewInt64(tableName, "spu_id")
	_promotionBargainRecord.SkuID = field.NewInt64(tableName, "sku_id")
	_promotionBargainRecord.BargainFirstPrice = field.NewInt(tableName, "bargain_first_price")
	_promotionBargainRecord.BargainPrice = field.NewInt(tableName, "bargain_price")
	_promotionBargainRecord.Status = field.NewInt(tableName, "status")
	_promotionBargainRecord.EndTime = field.NewTime(tableName, "end_time")
	_promotionBargainRecord.OrderID = field.NewInt64(tableName, "order_id")
	_promotionBargainRecord.Creator = field.NewString(tableName, "creator")
	_promotionBargainRecord.Updater = field.NewString(tableName, "updater")
	_promotionBargainRecord.CreatedAt = field.NewTime(tableName, "create_time")
	_promotionBargainRecord.UpdatedAt = field.NewTime(tableName, "update_time")
	_promotionBargainRecord.Deleted = field.NewField(tableName, "deleted")
	_promotionBargainRecord.TenantID = field.NewInt64(tableName, "tenant_id")

	_promotionBargainRecord.fillFieldMap()

	return _promotionBargainRecord
}

type promotionBargainRecord struct {
	promotionBargainRecordDo promotionBargainRecordDo

	ALL               field.Asterisk
	ID                field.Int64  // 编号
	UserID            field.Int64  // 用户编号
	ActivityID        field.Int64  // 砍价活动编号
	SpuID             field.Int64  // 商品 SPU 编号
	SkuID             field.Int64  // 商品 SKU 编号
	BargainFirstPrice field.Int    // 砍价起始价格，单位：分
	BargainPrice      field.Int    // 当前砍价，单位：分
	Status            field.Int    // 状态
	EndTime           field.Time   // 结束时间
	OrderID           field.Int64  // 订单编号
	Creator           field.String // 创建者
	Updater           field.String // 更新者
	CreatedAt         field.Time   // 创建时间
	UpdatedAt         field.Time   // 更新时间
	Deleted           field.Field  // 是否删除
	TenantID          field.Int64  // 租户编号

	fieldMap map[string]field.Expr
}

func (p promotionBargainRecord) Table(newTableName string) *promotionBargainRecord {
	p.promotionBargainRecordDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p promotionBargainRecord) As(alias string) *promotionBargainRecord {
	p.promotionBargainRecordDo.DO = *(p.promotionBargainRecordDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *promotionBargainRecord) updateTableName(table string) *promotionBargainRecord {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.UserID = field.NewInt64(table, "user_id")
	p.ActivityID = field.NewInt64(table, "activity_id")
	p.SpuID = field.NewInt64(table, "spu_id")
	p.SkuID = field.NewInt64(table, "sku_id")
	p.BargainFirstPrice = field.NewInt(table, "bargain_first_price")
	p.BargainPrice = field.NewInt(table, "bargain_price")
	p.Status = field.NewInt(table, "status")
	p.EndTime = field.NewTime(table, "end_time")
	p.OrderID = field.NewInt64(table, "order_id")
	p.Creator = field.NewString(table, "creator")
	p.Updater = field.NewString(table, "updater")
	p.CreatedAt = field.NewTime(table, "create_time")
	p.UpdatedAt = field.NewTime(table, "update_time")
	p.Deleted = field.NewField(table, "deleted")
	p.TenantID = field.NewInt64(table, "tenant_id")

	p.fillFieldMap()

	return p
}

func (p *promotionBargainRecord) WithContext(ctx context.Context) IPromotionBargainRecordDo {
	return p.promotionBargainRecordDo.WithContext(ctx)
}

func (p promotionBargainRecord) TableName() string { return p.promotionBargainRecordDo.TableName() }

func (p promotionBargainRecord) Alias() string { return p.promotionBargainRecordDo.Alias() }

func (p promotionBargainRecord) Columns(cols ...field.Expr) gen.Columns {
	return p.promotionBargainRecordDo.Columns(cols...)
}

func (p *promotionBargainRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *promotionBargainRecord) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 16)
	p.fieldMap["id"] = p.ID
	p.fieldMap["user_id"] = p.UserID
	p.fieldMap["activity_id"] = p.ActivityID
	p.fieldMap["spu_id"] = p.SpuID
	p.fieldMap["sku_id"] = p.SkuID
	p.fieldMap["bargain_first_price"] = p.BargainFirstPrice
	p.fieldMap["bargain_price"] = p.BargainPrice
	p.fieldMap["status"] = p.Status
	p.fieldMap["end_time"] = p.EndTime
	p.fieldMap["order_id"] = p.OrderID
	p.fieldMap["creator"] = p.Creator
	p.fieldMap["updater"] = p.Updater
	p.fieldMap["create_time"] = p.CreatedAt
	p.fieldMap["update_time"] = p.UpdatedAt
	p.fieldMap["deleted"] = p.Deleted
	p.fieldMap["tenant_id"] = p.TenantID
}

func (p promotionBargainRecord) clone(db *gorm.DB) promotionBargainRecord {
	p.promotionBargainRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p promotionBargainRecord) replaceDB(db *gorm.DB) promotionBargainRecord {
	p.promotionBargainRecordDo.ReplaceDB(db)
	return p
}

type promotionBargainRecordDo struct{ gen.DO }

type IPromotionBargainRecordDo interface {
	gen.SubQuery
	Debug() IPromotionBargainRecordDo
	WithContext(ctx context.Context) IPromotionBargainRecordDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPromotionBargainRecordDo
	WriteDB() IPromotionBargainRecordDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPromotionBargainRecordDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPromotionBargainRecordDo
	Not(conds ...gen.Condition) IPromotionBargainRecordDo
	Or(conds ...gen.Condition) IPromotionBargainRecordDo
	Select(conds ...field.Expr) IPromotionBargainRecordDo
	Where(conds ...gen.Condition) IPromotionBargainRecordDo
	Order(conds ...field.Expr) IPromotionBargainRecordDo
	Distinct(cols ...field.Expr) IPromotionBargainRecordDo
	Omit(cols ...field.Expr) IPromotionBargainRecordDo
	Join(table schema.Tabler, on ...field.Expr) IPromotionBargainRecordDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPromotionBargainRecordDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPromotionBargainRecordDo
	Group(cols ...field.Expr) IPromotionBargainRecordDo
	Having(conds ...gen.Condition) IPromotionBargainRecordDo
	Limit(limit int) IPromotionBargainRecordDo
	Offset(offset int) IPromotionBargainRecordDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPromotionBargainRecordDo
	Unscoped() IPromotionBargainRecordDo
	Create(values ...*promotion.PromotionBargainRecord) error
	CreateInBatches(values []*promotion.PromotionBargainRecord, batchSize int) error
	Save(values ...*promotion.PromotionBargainRecord) error
	First() (*promotion.PromotionBargainRecord, error)
	Take() (*promotion.PromotionBargainRecord, error)
	Last() (*promotion.PromotionBargainRecord, error)
	Find() ([]*promotion.PromotionBargainRecord, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*promotion.PromotionBargainRecord, err error)
	FindInBatches(result *[]*promotion.PromotionBargainRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*promotion.PromotionBargainRecord) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPromotionBargainRecordDo
	Assign(attrs ...field.AssignExpr) IPromotionBargainRecordDo
	Joins(fields ...field.RelationField) IPromotionBargainRecordDo
	Preload(fields ...field.RelationField) IPromotionBargainRecordDo
	FirstOrInit() (*promotion.PromotionBargainRecord, error)
	FirstOrCreate() (*promotion.PromotionBargainRecord, error)
	FindByPage(offset int, limit int) (result []*promotion.PromotionBargainRecord, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPromotionBargainRecordDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p promotionBargainRecordDo) Debug() IPromotionBargainRecordDo {
	return p.withDO(p.DO.Debug())
}

func (p promotionBargainRecordDo) WithContext(ctx context.Context) IPromotionBargainRecordDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p promotionBargainRecordDo) ReadDB() IPromotionBargainRecordDo {
	return p.Clauses(dbresolver.Read)
}

func (p promotionBargainRecordDo) WriteDB() IPromotionBargainRecordDo {
	return p.Clauses(dbresolver.Write)
}

func (p promotionBargainRecordDo) Session(config *gorm.Session) IPromotionBargainRecordDo {
	return p.withDO(p.DO.Session(config))
}

func (p promotionBargainRecordDo) Clauses(conds ...clause.Expression) IPromotionBargainRecordDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p promotionBargainRecordDo) Returning(value interface{}, columns ...string) IPromotionBargainRecordDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p promotionBargainRecordDo) Not(conds ...gen.Condition) IPromotionBargainRecordDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p promotionBargainRecordDo) Or(conds ...gen.Condition) IPromotionBargainRecordDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p promotionBargainRecordDo) Select(conds ...field.Expr) IPromotionBargainRecordDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p promotionBargainRecordDo) Where(conds ...gen.Condition) IPromotionBargainRecordDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p promotionBargainRecordDo) Order(conds ...field.Expr) IPromotionBargainRecordDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p promotionBargainRecordDo) Distinct(cols ...field.Expr) IPromotionBargainRecordDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p promotionBargainRecordDo) Omit(cols ...field.Expr) IPromotionBargainRecordDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p promotionBargainRecordDo) Join(table schema.Tabler, on ...field.Expr) IPromotionBargainRecordDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p promotionBargainRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPromotionBargainRecordDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p promotionBargainRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) IPromotionBargainRecordDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p promotionBargainRecordDo) Group(cols ...field.Expr) IPromotionBargainRecordDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p promotionBargainRecordDo) Having(conds ...gen.Condition) IPromotionBargainRecordDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p promotionBargainRecordDo) Limit(limit int) IPromotionBargainRecordDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p promotionBargainRecordDo) Offset(offset int) IPromotionBargainRecordDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p promotionBargainRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPromotionBargainRecordDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p promotionBargainRecordDo) Unscoped() IPromotionBargainRecordDo {
	return p.withDO(p.DO.Unscoped())
}

func (p promotionBargainRecordDo) Create(values ...*promotion.PromotionBargainRecord) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p promotionBargainRecordDo) CreateInBatches(values []*promotion.PromotionBargainRecord, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p promotionBargainRecordDo) Save(values ...*promotion.PromotionBargainRecord) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p promotionBargainRecordDo) First() (*promotion.PromotionBargainRecord, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionBargainRecord), nil
	}
}

func (p promotionBargainRecordDo) Take() (*promotion.PromotionBargainRecord, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionBargainRecord), nil
	}
}

func (p promotionBargainRecordDo) Last() (*promotion.PromotionBargainRecord, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionBargainRecord), nil
	}
}

func (p promotionBargainRecordDo) Find() ([]*promotion.PromotionBargainRecord, error) {
	result, err := p.DO.Find()
	return result.([]*promotion.PromotionBargainRecord), err
}

func (p promotionBargainRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*promotion.PromotionBargainRecord, err error) {
	buf := make([]*promotion.PromotionBargainRecord, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p promotionBargainRecordDo) FindInBatches(result *[]*promotion.PromotionBargainRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p promotionBargainRecordDo) Attrs(attrs ...field.AssignExpr) IPromotionBargainRecordDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p promotionBargainRecordDo) Assign(attrs ...field.AssignExpr) IPromotionBargainRecordDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p promotionBargainRecordDo) Joins(fields ...field.RelationField) IPromotionBargainRecordDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p promotionBargainRecordDo) Preload(fields ...field.RelationField) IPromotionBargainRecordDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p promotionBargainRecordDo) FirstOrInit() (*promotion.PromotionBargainRecord, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionBargainRecord), nil
	}
}

func (p promotionBargainRecordDo) FirstOrCreate() (*promotion.PromotionBargainRecord, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionBargainRecord), nil
	}
}

func (p promotionBargainRecordDo) FindByPage(offset int, limit int) (result []*promotion.PromotionBargainRecord, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p promotionBargainRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p promotionBargainRecordDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p promotionBargainRecordDo) Delete(models ...*promotion.PromotionBargainRecord) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *promotionBargainRecordDo) withDO(do gen.Dao) *promotionBargainRecordDo {
	p.DO = *do.(*gen.DO)
	return p
}
