// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend-go/internal/model/promotion"
)

func newPromotionBargainActivity(db *gorm.DB, opts ...gen.DOOption) promotionBargainActivity {
	_promotionBargainActivity := promotionBargainActivity{}

	_promotionBargainActivity.promotionBargainActivityDo.UseDB(db, opts...)
	_promotionBargainActivity.promotionBargainActivityDo.UseModel(&promotion.PromotionBargainActivity{})

	tableName := _promotionBargainActivity.promotionBargainActivityDo.TableName()
	_promotionBargainActivity.ALL = field.NewAsterisk(tableName)
	_promotionBargainActivity.ID = field.NewInt64(tableName, "id")
	_promotionBargainActivity.Name = field.NewString(tableName, "name")
	_promotionBargainActivity.StartTime = field.NewTime(tableName, "start_time")
	_promotionBargainActivity.EndTime = field.NewTime(tableName, "end_time")
	_promotionBargainActivity.Status = field.NewInt(tableName, "status")
	_promotionBargainActivity.SpuID = field.NewInt64(tableName, "spu_id")
	_promotionBargainActivity.SkuID = field.NewInt64(tableName, "sku_id")
	_promotionBargainActivity.BargainFirstPrice = field.NewInt(tableName, "bargain_first_price")
	_promotionBargainActivity.BargainMinPrice = field.NewInt(tableName, "bargain_min_price")
	_promotionBargainActivity.Stock = field.NewInt(tableName, "stock")
	_promotionBargainActivity.TotalStock = field.NewInt(tableName, "total_stock")
	_promotionBargainActivity.HelpMaxCount = field.NewInt(tableName, "help_max_count")
	_promotionBargainActivity.BargainCount = field.NewInt(tableName, "bargain_count")
	_promotionBargainActivity.TotalLimitCount = field.NewInt(tableName, "total_limit_count")
	_promotionBargainActivity.RandomMinPrice = field.NewInt(tableName, "random_min_price")
	_promotionBargainActivity.RandomMaxPrice = field.NewInt(tableName, "random_max_price")
	_promotionBargainActivity.Sort = field.NewInt(tableName, "sort")
	_promotionBargainActivity.Remark = field.NewString(tableName, "remark")
	_promotionBargainActivity.Creator = field.NewString(tableName, "creator")
	_promotionBargainActivity.Updater = field.NewString(tableName, "updater")
	_promotionBargainActivity.CreatedAt = field.NewTime(tableName, "create_time")
	_promotionBargainActivity.UpdatedAt = field.NewTime(tableName, "update_time")
	_promotionBargainActivity.Deleted = field.NewField(tableName, "deleted")
	_promotionBargainActivity.TenantID = field.NewInt64(tableName, "tenant_id")

	_promotionBargainActivity.fillFieldMap()

	return _promotionBargainActivity
}

type promotionBargainActivity struct {
	promotionBargainActivityDo promotionBargainActivityDo

	ALL               field.Asterisk
	ID                field.Int64  // 编号
	Name              field.String // 砍价活动名称
	StartTime         field.Time   // 活动开始时间
	EndTime           field.Time   // 活动结束时间
	Status            field.Int    // 状态
	SpuID             field.Int64  // 商品 SPU 编号
	SkuID             field.Int64  // 商品 SKU 编号
	BargainFirstPrice field.Int    // 砍价起始价格，单位：分
	BargainMinPrice   field.Int    // 砍价底价，单位：分
	Stock             field.Int    // 砍价库存
	TotalStock        field.Int    // 砍价总库存
	HelpMaxCount      field.Int    // 砍价人数
	BargainCount      field.Int    // 帮砍次数
	TotalLimitCount   field.Int    // 总限购数量
	RandomMinPrice    field.Int    // 用户每次砍价的最小金额
	RandomMaxPrice    field.Int    // 用户每次砍价的最大金额
	Sort              field.Int    // 排序
	Remark            field.String // 备注
	Creator           field.String // 创建者
	Updater           field.String // 更新者
	CreatedAt         field.Time   // 创建时间
	UpdatedAt         field.Time   // 更新时间
	Deleted           field.Field  // 是否删除
	TenantID          field.Int64  // 租户编号

	fieldMap map[string]field.Expr
}

func (p promotionBargainActivity) Table(newTableName string) *promotionBargainActivity {
	p.promotionBargainActivityDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p promotionBargainActivity) As(alias string) *promotionBargainActivity {
	p.promotionBargainActivityDo.DO = *(p.promotionBargainActivityDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *promotionBargainActivity) updateTableName(table string) *promotionBargainActivity {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.Name = field.NewString(table, "name")
	p.StartTime = field.NewTime(table, "start_time")
	p.EndTime = field.NewTime(table, "end_time")
	p.Status = field.NewInt(table, "status")
	p.SpuID = field.NewInt64(table, "spu_id")
	p.SkuID = field.NewInt64(table, "sku_id")
	p.BargainFirstPrice = field.NewInt(table, "bargain_first_price")
	p.BargainMinPrice = field.NewInt(table, "bargain_min_price")
	p.Stock = field.NewInt(table, "stock")
	p.TotalStock = field.NewInt(table, "total_stock")
	p.HelpMaxCount = field.NewInt(table, "help_max_count")
	p.BargainCount = field.NewInt(table, "bargain_count")
	p.TotalLimitCount = field.NewInt(table, "total_limit_count")
	p.RandomMinPrice = field.NewInt(table, "random_min_price")
	p.RandomMaxPrice = field.NewInt(table, "random_max_price")
	p.Sort = field.NewInt(table, "sort")
	p.Remark = field.NewString(table, "remark")
	p.Creator = field.NewString(table, "creator")
	p.Updater = field.NewString(table, "updater")
	p.CreatedAt = field.NewTime(table, "create_time")
	p.UpdatedAt = field.NewTime(table, "update_time")
	p.Deleted = field.NewField(table, "deleted")
	p.TenantID = field.NewInt64(table, "tenant_id")

	p.fillFieldMap()

	return p
}

func (p *promotionBargainActivity) WithContext(ctx context.Context) IPromotionBargainActivityDo {
	return p.promotionBargainActivityDo.WithContext(ctx)
}

func (p promotionBargainActivity) TableName() string { return p.promotionBargainActivityDo.TableName() }

func (p promotionBargainActivity) Alias() string { return p.promotionBargainActivityDo.Alias() }

func (p promotionBargainActivity) Columns(cols ...field.Expr) gen.Columns {
	return p.promotionBargainActivityDo.Columns(cols...)
}

func (p *promotionBargainActivity) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *promotionBargainActivity) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 24)
	p.fieldMap["id"] = p.ID
	p.fieldMap["name"] = p.Name
	p.fieldMap["start_time"] = p.StartTime
	p.fieldMap["end_time"] = p.EndTime
	p.fieldMap["status"] = p.Status
	p.fieldMap["spu_id"] = p.SpuID
	p.fieldMap["sku_id"] = p.SkuID
	p.fieldMap["bargain_first_price"] = p.BargainFirstPrice
	p.fieldMap["bargain_min_price"] = p.BargainMinPrice
	p.fieldMap["stock"] = p.Stock
	p.fieldMap["total_stock"] = p.TotalStock
	p.fieldMap["help_max_count"] = p.HelpMaxCount
	p.fieldMap["bargain_count"] = p.BargainCount
	p.fieldMap["total_limit_count"] = p.TotalLimitCount
	p.fieldMap["random_min_price"] = p.RandomMinPrice
	p.fieldMap["random_max_price"] = p.RandomMaxPrice
	p.fieldMap["sort"] = p.Sort
	p.fieldMap["remark"] = p.Remark
	p.fieldMap["creator"] = p.Creator
	p.fieldMap["updater"] = p.Updater
	p.fieldMap["create_time"] = p.CreatedAt
	p.fieldMap["update_time"] = p.UpdatedAt
	p.fieldMap["deleted"] = p.Deleted
	p.fieldMap["tenant_id"] = p.TenantID
}

func (p promotionBargainActivity) clone(db *gorm.DB) promotionBargainActivity {
	p.promotionBargainActivityDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p promotionBargainActivity) replaceDB(db *gorm.DB) promotionBargainActivity {
	p.promotionBargainActivityDo.ReplaceDB(db)
	return p
}

type promotionBargainActivityDo struct{ gen.DO }

type IPromotionBargainActivityDo interface {
	gen.SubQuery
	Debug() IPromotionBargainActivityDo
	WithContext(ctx context.Context) IPromotionBargainActivityDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPromotionBargainActivityDo
	WriteDB() IPromotionBargainActivityDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPromotionBargainActivityDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPromotionBargainActivityDo
	Not(conds ...gen.Condition) IPromotionBargainActivityDo
	Or(conds ...gen.Condition) IPromotionBargainActivityDo
	Select(conds ...field.Expr) IPromotionBargainActivityDo
	Where(conds ...gen.Condition) IPromotionBargainActivityDo
	Order(conds ...field.Expr) IPromotionBargainActivityDo
	Distinct(cols ...field.Expr) IPromotionBargainActivityDo
	Omit(cols ...field.Expr) IPromotionBargainActivityDo
	Join(table schema.Tabler, on ...field.Expr) IPromotionBargainActivityDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPromotionBargainActivityDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPromotionBargainActivityDo
	Group(cols ...field.Expr) IPromotionBargainActivityDo
	Having(conds ...gen.Condition) IPromotionBargainActivityDo
	Limit(limit int) IPromotionBargainActivityDo
	Offset(offset int) IPromotionBargainActivityDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPromotionBargainActivityDo
	Unscoped() IPromotionBargainActivityDo
	Create(values ...*promotion.PromotionBargainActivity) error
	CreateInBatches(values []*promotion.PromotionBargainActivity, batchSize int) error
	Save(values ...*promotion.PromotionBargainActivity) error
	First() (*promotion.PromotionBargainActivity, error)
	Take() (*promotion.PromotionBargainActivity, error)
	Last() (*promotion.PromotionBargainActivity, error)
	Find() ([]*promotion.PromotionBargainActivity, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*promotion.PromotionBargainActivity, err error)
	FindInBatches(result *[]*promotion.PromotionBargainActivity, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*promotion.PromotionBargainActivity) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPromotionBargainActivityDo
	Assign(attrs ...field.AssignExpr) IPromotionBargainActivityDo
	Joins(fields ...field.RelationField) IPromotionBargainActivityDo
	Preload(fields ...field.RelationField) IPromotionBargainActivityDo
	FirstOrInit() (*promotion.PromotionBargainActivity, error)
	FirstOrCreate() (*promotion.PromotionBargainActivity, error)
	FindByPage(offset int, limit int) (result []*promotion.PromotionBargainActivity, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPromotionBargainActivityDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p promotionBargainActivityDo) Debug() IPromotionBargainActivityDo {
	return p.withDO(p.DO.Debug())
}

func (p promotionBargainActivityDo) WithContext(ctx context.Context) IPromotionBargainActivityDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p promotionBargainActivityDo) ReadDB() IPromotionBargainActivityDo {
	return p.Clauses(dbresolver.Read)
}

func (p promotionBargainActivityDo) WriteDB() IPromotionBargainActivityDo {
	return p.Clauses(dbresolver.Write)
}

func (p promotionBargainActivityDo) Session(config *gorm.Session) IPromotionBargainActivityDo {
	return p.withDO(p.DO.Session(config))
}

func (p promotionBargainActivityDo) Clauses(conds ...clause.Expression) IPromotionBargainActivityDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p promotionBargainActivityDo) Returning(value interface{}, columns ...string) IPromotionBargainActivityDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p promotionBargainActivityDo) Not(conds ...gen.Condition) IPromotionBargainActivityDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p promotionBargainActivityDo) Or(conds ...gen.Condition) IPromotionBargainActivityDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p promotionBargainActivityDo) Select(conds ...field.Expr) IPromotionBargainActivityDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p promotionBargainActivityDo) Where(conds ...gen.Condition) IPromotionBargainActivityDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p promotionBargainActivityDo) Order(conds ...field.Expr) IPromotionBargainActivityDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p promotionBargainActivityDo) Distinct(cols ...field.Expr) IPromotionBargainActivityDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p promotionBargainActivityDo) Omit(cols ...field.Expr) IPromotionBargainActivityDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p promotionBargainActivityDo) Join(table schema.Tabler, on ...field.Expr) IPromotionBargainActivityDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p promotionBargainActivityDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPromotionBargainActivityDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p promotionBargainActivityDo) RightJoin(table schema.Tabler, on ...field.Expr) IPromotionBargainActivityDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p promotionBargainActivityDo) Group(cols ...field.Expr) IPromotionBargainActivityDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p promotionBargainActivityDo) Having(conds ...gen.Condition) IPromotionBargainActivityDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p promotionBargainActivityDo) Limit(limit int) IPromotionBargainActivityDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p promotionBargainActivityDo) Offset(offset int) IPromotionBargainActivityDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p promotionBargainActivityDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPromotionBargainActivityDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p promotionBargainActivityDo) Unscoped() IPromotionBargainActivityDo {
	return p.withDO(p.DO.Unscoped())
}

func (p promotionBargainActivityDo) Create(values ...*promotion.PromotionBargainActivity) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p promotionBargainActivityDo) CreateInBatches(values []*promotion.PromotionBargainActivity, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p promotionBargainActivityDo) Save(values ...*promotion.PromotionBargainActivity) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p promotionBargainActivityDo) First() (*promotion.PromotionBargainActivity, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionBargainActivity), nil
	}
}

func (p promotionBargainActivityDo) Take() (*promotion.PromotionBargainActivity, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionBargainActivity), nil
	}
}

func (p promotionBargainActivityDo) Last() (*promotion.PromotionBargainActivity, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionBargainActivity), nil
	}
}

func (p promotionBargainActivityDo) Find() ([]*promotion.PromotionBargainActivity, error) {
	result, err := p.DO.Find()
	return result.([]*promotion.PromotionBargainActivity), err
}

func (p promotionBargainActivityDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*promotion.PromotionBargainActivity, err error) {
	buf := make([]*promotion.PromotionBargainActivity, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p promotionBargainActivityDo) FindInBatches(result *[]*promotion.PromotionBargainActivity, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p promotionBargainActivityDo) Attrs(attrs ...field.AssignExpr) IPromotionBargainActivityDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p promotionBargainActivityDo) Assign(attrs ...field.AssignExpr) IPromotionBargainActivityDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p promotionBargainActivityDo) Joins(fields ...field.RelationField) IPromotionBargainActivityDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p promotionBargainActivityDo) Preload(fields ...field.RelationField) IPromotionBargainActivityDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p promotionBargainActivityDo) FirstOrInit() (*promotion.PromotionBargainActivity, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionBargainActivity), nil
	}
}

func (p promotionBargainActivityDo) FirstOrCreate() (*promotion.PromotionBargainActivity, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionBargainActivity), nil
	}
}

func (p promotionBargainActivityDo) FindByPage(offset int, limit int) (result []*promotion.PromotionBargainActivity, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p promotionBargainActivityDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p promotionBargainActivityDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p promotionBargainActivityDo) Delete(models ...*promotion.PromotionBargainActivity) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *promotionBargainActivityDo) withDO(do gen.Dao) *promotionBargainActivityDo {
	p.DO = *do.(*gen.DO)
	return p
}
