// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend-go/internal/model/promotion"
)

func newPromotionBanner(db *gorm.DB, opts ...gen.DOOption) promotionBanner {
	_promotionBanner := promotionBanner{}

	_promotionBanner.promotionBannerDo.UseDB(db, opts...)
	_promotionBanner.promotionBannerDo.UseModel(&promotion.PromotionBanner{})

	tableName := _promotionBanner.promotionBannerDo.TableName()
	_promotionBanner.ALL = field.NewAsterisk(tableName)
	_promotionBanner.ID = field.NewInt64(tableName, "id")
	_promotionBanner.Title = field.NewString(tableName, "title")
	_promotionBanner.PicURL = field.NewString(tableName, "pic_url")
	_promotionBanner.Url = field.NewString(tableName, "url")
	_promotionBanner.Status = field.NewInt(tableName, "status")
	_promotionBanner.Sort = field.NewInt(tableName, "sort")
	_promotionBanner.Position = field.NewInt(tableName, "position")
	_promotionBanner.Memo = field.NewString(tableName, "memo")
	_promotionBanner.Creator = field.NewString(tableName, "creator")
	_promotionBanner.Updater = field.NewString(tableName, "updater")
	_promotionBanner.CreatedAt = field.NewTime(tableName, "create_time")
	_promotionBanner.UpdatedAt = field.NewTime(tableName, "update_time")
	_promotionBanner.DeletedAt = field.NewField(tableName, "deleted")
	_promotionBanner.Deleted = field.NewBool(tableName, "deleted")

	_promotionBanner.fillFieldMap()

	return _promotionBanner
}

type promotionBanner struct {
	promotionBannerDo promotionBannerDo

	ALL       field.Asterisk
	ID        field.Int64  // 编号
	Title     field.String // 标题
	PicURL    field.String // 图片地址
	Url       field.String // 跳转地址
	Status    field.Int    // 状态
	Sort      field.Int    // 排序
	Position  field.Int    // 位置
	Memo      field.String // 备注
	Creator   field.String // 创建者
	Updater   field.String // 更新者
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 更新时间
	DeletedAt field.Field  // 删除时间
	Deleted   field.Bool   // 是否删除

	fieldMap map[string]field.Expr
}

func (p promotionBanner) Table(newTableName string) *promotionBanner {
	p.promotionBannerDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p promotionBanner) As(alias string) *promotionBanner {
	p.promotionBannerDo.DO = *(p.promotionBannerDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *promotionBanner) updateTableName(table string) *promotionBanner {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.Title = field.NewString(table, "title")
	p.PicURL = field.NewString(table, "pic_url")
	p.Url = field.NewString(table, "url")
	p.Status = field.NewInt(table, "status")
	p.Sort = field.NewInt(table, "sort")
	p.Position = field.NewInt(table, "position")
	p.Memo = field.NewString(table, "memo")
	p.Creator = field.NewString(table, "creator")
	p.Updater = field.NewString(table, "updater")
	p.CreatedAt = field.NewTime(table, "create_time")
	p.UpdatedAt = field.NewTime(table, "update_time")
	p.DeletedAt = field.NewField(table, "deleted")
	p.Deleted = field.NewBool(table, "deleted")

	p.fillFieldMap()

	return p
}

func (p *promotionBanner) WithContext(ctx context.Context) IPromotionBannerDo {
	return p.promotionBannerDo.WithContext(ctx)
}

func (p promotionBanner) TableName() string { return p.promotionBannerDo.TableName() }

func (p promotionBanner) Alias() string { return p.promotionBannerDo.Alias() }

func (p promotionBanner) Columns(cols ...field.Expr) gen.Columns {
	return p.promotionBannerDo.Columns(cols...)
}

func (p *promotionBanner) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *promotionBanner) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 14)
	p.fieldMap["id"] = p.ID
	p.fieldMap["title"] = p.Title
	p.fieldMap["pic_url"] = p.PicURL
	p.fieldMap["url"] = p.Url
	p.fieldMap["status"] = p.Status
	p.fieldMap["sort"] = p.Sort
	p.fieldMap["position"] = p.Position
	p.fieldMap["memo"] = p.Memo
	p.fieldMap["creator"] = p.Creator
	p.fieldMap["updater"] = p.Updater
	p.fieldMap["create_time"] = p.CreatedAt
	p.fieldMap["update_time"] = p.UpdatedAt
	p.fieldMap["deleted"] = p.DeletedAt
	p.fieldMap["deleted"] = p.Deleted
}

func (p promotionBanner) clone(db *gorm.DB) promotionBanner {
	p.promotionBannerDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p promotionBanner) replaceDB(db *gorm.DB) promotionBanner {
	p.promotionBannerDo.ReplaceDB(db)
	return p
}

type promotionBannerDo struct{ gen.DO }

type IPromotionBannerDo interface {
	gen.SubQuery
	Debug() IPromotionBannerDo
	WithContext(ctx context.Context) IPromotionBannerDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPromotionBannerDo
	WriteDB() IPromotionBannerDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPromotionBannerDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPromotionBannerDo
	Not(conds ...gen.Condition) IPromotionBannerDo
	Or(conds ...gen.Condition) IPromotionBannerDo
	Select(conds ...field.Expr) IPromotionBannerDo
	Where(conds ...gen.Condition) IPromotionBannerDo
	Order(conds ...field.Expr) IPromotionBannerDo
	Distinct(cols ...field.Expr) IPromotionBannerDo
	Omit(cols ...field.Expr) IPromotionBannerDo
	Join(table schema.Tabler, on ...field.Expr) IPromotionBannerDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPromotionBannerDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPromotionBannerDo
	Group(cols ...field.Expr) IPromotionBannerDo
	Having(conds ...gen.Condition) IPromotionBannerDo
	Limit(limit int) IPromotionBannerDo
	Offset(offset int) IPromotionBannerDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPromotionBannerDo
	Unscoped() IPromotionBannerDo
	Create(values ...*promotion.PromotionBanner) error
	CreateInBatches(values []*promotion.PromotionBanner, batchSize int) error
	Save(values ...*promotion.PromotionBanner) error
	First() (*promotion.PromotionBanner, error)
	Take() (*promotion.PromotionBanner, error)
	Last() (*promotion.PromotionBanner, error)
	Find() ([]*promotion.PromotionBanner, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*promotion.PromotionBanner, err error)
	FindInBatches(result *[]*promotion.PromotionBanner, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*promotion.PromotionBanner) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPromotionBannerDo
	Assign(attrs ...field.AssignExpr) IPromotionBannerDo
	Joins(fields ...field.RelationField) IPromotionBannerDo
	Preload(fields ...field.RelationField) IPromotionBannerDo
	FirstOrInit() (*promotion.PromotionBanner, error)
	FirstOrCreate() (*promotion.PromotionBanner, error)
	FindByPage(offset int, limit int) (result []*promotion.PromotionBanner, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPromotionBannerDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p promotionBannerDo) Debug() IPromotionBannerDo {
	return p.withDO(p.DO.Debug())
}

func (p promotionBannerDo) WithContext(ctx context.Context) IPromotionBannerDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p promotionBannerDo) ReadDB() IPromotionBannerDo {
	return p.Clauses(dbresolver.Read)
}

func (p promotionBannerDo) WriteDB() IPromotionBannerDo {
	return p.Clauses(dbresolver.Write)
}

func (p promotionBannerDo) Session(config *gorm.Session) IPromotionBannerDo {
	return p.withDO(p.DO.Session(config))
}

func (p promotionBannerDo) Clauses(conds ...clause.Expression) IPromotionBannerDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p promotionBannerDo) Returning(value interface{}, columns ...string) IPromotionBannerDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p promotionBannerDo) Not(conds ...gen.Condition) IPromotionBannerDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p promotionBannerDo) Or(conds ...gen.Condition) IPromotionBannerDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p promotionBannerDo) Select(conds ...field.Expr) IPromotionBannerDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p promotionBannerDo) Where(conds ...gen.Condition) IPromotionBannerDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p promotionBannerDo) Order(conds ...field.Expr) IPromotionBannerDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p promotionBannerDo) Distinct(cols ...field.Expr) IPromotionBannerDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p promotionBannerDo) Omit(cols ...field.Expr) IPromotionBannerDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p promotionBannerDo) Join(table schema.Tabler, on ...field.Expr) IPromotionBannerDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p promotionBannerDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPromotionBannerDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p promotionBannerDo) RightJoin(table schema.Tabler, on ...field.Expr) IPromotionBannerDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p promotionBannerDo) Group(cols ...field.Expr) IPromotionBannerDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p promotionBannerDo) Having(conds ...gen.Condition) IPromotionBannerDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p promotionBannerDo) Limit(limit int) IPromotionBannerDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p promotionBannerDo) Offset(offset int) IPromotionBannerDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p promotionBannerDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPromotionBannerDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p promotionBannerDo) Unscoped() IPromotionBannerDo {
	return p.withDO(p.DO.Unscoped())
}

func (p promotionBannerDo) Create(values ...*promotion.PromotionBanner) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p promotionBannerDo) CreateInBatches(values []*promotion.PromotionBanner, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p promotionBannerDo) Save(values ...*promotion.PromotionBanner) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p promotionBannerDo) First() (*promotion.PromotionBanner, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionBanner), nil
	}
}

func (p promotionBannerDo) Take() (*promotion.PromotionBanner, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionBanner), nil
	}
}

func (p promotionBannerDo) Last() (*promotion.PromotionBanner, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionBanner), nil
	}
}

func (p promotionBannerDo) Find() ([]*promotion.PromotionBanner, error) {
	result, err := p.DO.Find()
	return result.([]*promotion.PromotionBanner), err
}

func (p promotionBannerDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*promotion.PromotionBanner, err error) {
	buf := make([]*promotion.PromotionBanner, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p promotionBannerDo) FindInBatches(result *[]*promotion.PromotionBanner, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p promotionBannerDo) Attrs(attrs ...field.AssignExpr) IPromotionBannerDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p promotionBannerDo) Assign(attrs ...field.AssignExpr) IPromotionBannerDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p promotionBannerDo) Joins(fields ...field.RelationField) IPromotionBannerDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p promotionBannerDo) Preload(fields ...field.RelationField) IPromotionBannerDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p promotionBannerDo) FirstOrInit() (*promotion.PromotionBanner, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionBanner), nil
	}
}

func (p promotionBannerDo) FirstOrCreate() (*promotion.PromotionBanner, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionBanner), nil
	}
}

func (p promotionBannerDo) FindByPage(offset int, limit int) (result []*promotion.PromotionBanner, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p promotionBannerDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p promotionBannerDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p promotionBannerDo) Delete(models ...*promotion.PromotionBanner) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *promotionBannerDo) withDO(do gen.Dao) *promotionBannerDo {
	p.DO = *do.(*gen.DO)
	return p
}
