// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend-go/internal/model/promotion"
)

func newPromotionCombinationRecord(db *gorm.DB, opts ...gen.DOOption) promotionCombinationRecord {
	_promotionCombinationRecord := promotionCombinationRecord{}

	_promotionCombinationRecord.promotionCombinationRecordDo.UseDB(db, opts...)
	_promotionCombinationRecord.promotionCombinationRecordDo.UseModel(&promotion.PromotionCombinationRecord{})

	tableName := _promotionCombinationRecord.promotionCombinationRecordDo.TableName()
	_promotionCombinationRecord.ALL = field.NewAsterisk(tableName)
	_promotionCombinationRecord.ID = field.NewInt64(tableName, "id")
	_promotionCombinationRecord.ActivityID = field.NewInt64(tableName, "activity_id")
	_promotionCombinationRecord.CombinationPrice = field.NewInt(tableName, "combination_price")
	_promotionCombinationRecord.SpuID = field.NewInt64(tableName, "spu_id")
	_promotionCombinationRecord.SpuName = field.NewString(tableName, "spu_name")
	_promotionCombinationRecord.PicUrl = field.NewString(tableName, "pic_url")
	_promotionCombinationRecord.SkuID = field.NewInt64(tableName, "sku_id")
	_promotionCombinationRecord.Count = field.NewInt(tableName, "count")
	_promotionCombinationRecord.UserID = field.NewInt64(tableName, "user_id")
	_promotionCombinationRecord.Nickname = field.NewString(tableName, "nickname")
	_promotionCombinationRecord.Avatar = field.NewString(tableName, "avatar")
	_promotionCombinationRecord.HeadID = field.NewInt64(tableName, "head_id")
	_promotionCombinationRecord.Status = field.NewInt(tableName, "status")
	_promotionCombinationRecord.OrderID = field.NewInt64(tableName, "order_id")
	_promotionCombinationRecord.UserSize = field.NewInt(tableName, "user_size")
	_promotionCombinationRecord.UserCount = field.NewInt(tableName, "user_count")
	_promotionCombinationRecord.VirtualGroup = field.NewBool(tableName, "virtual_group")
	_promotionCombinationRecord.ExpireTime = field.NewTime(tableName, "expire_time")
	_promotionCombinationRecord.StartTime = field.NewTime(tableName, "start_time")
	_promotionCombinationRecord.EndTime = field.NewTime(tableName, "end_time")
	_promotionCombinationRecord.Creator = field.NewString(tableName, "creator")
	_promotionCombinationRecord.Updater = field.NewString(tableName, "updater")
	_promotionCombinationRecord.CreatedAt = field.NewTime(tableName, "create_time")
	_promotionCombinationRecord.UpdatedAt = field.NewTime(tableName, "update_time")
	_promotionCombinationRecord.Deleted = field.NewField(tableName, "deleted")
	_promotionCombinationRecord.TenantID = field.NewInt64(tableName, "tenant_id")

	_promotionCombinationRecord.fillFieldMap()

	return _promotionCombinationRecord
}

type promotionCombinationRecord struct {
	promotionCombinationRecordDo promotionCombinationRecordDo

	ALL              field.Asterisk
	ID               field.Int64  // 编号
	ActivityID       field.Int64  // 活动编号
	CombinationPrice field.Int    // 拼团单价
	SpuID            field.Int64  // SPU编号
	SpuName          field.String // 商品名字
	PicUrl           field.String // 商品图片
	SkuID            field.Int64  // SKU编号
	Count            field.Int    // 购买数量
	UserID           field.Int64  // 用户编号
	Nickname         field.String // 用户昵称
	Avatar           field.String // 用户头像
	HeadID           field.Int64  // 团长编号
	Status           field.Int    // 拼团状态
	OrderID          field.Int64  // 订单编号
	UserSize         field.Int    // 成团人数
	UserCount        field.Int    // 已入团人数
	VirtualGroup     field.Bool   // 是否虚拟成团
	ExpireTime       field.Time   // 过期时间
	StartTime        field.Time   // 开始时间
	EndTime          field.Time   // 结束时间
	Creator          field.String // 创建者
	Updater          field.String // 更新者
	CreatedAt        field.Time   // 创建时间
	UpdatedAt        field.Time   // 更新时间
	Deleted          field.Field  // 是否删除
	TenantID         field.Int64  // 租户编号

	fieldMap map[string]field.Expr
}

func (p promotionCombinationRecord) Table(newTableName string) *promotionCombinationRecord {
	p.promotionCombinationRecordDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p promotionCombinationRecord) As(alias string) *promotionCombinationRecord {
	p.promotionCombinationRecordDo.DO = *(p.promotionCombinationRecordDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *promotionCombinationRecord) updateTableName(table string) *promotionCombinationRecord {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.ActivityID = field.NewInt64(table, "activity_id")
	p.CombinationPrice = field.NewInt(table, "combination_price")
	p.SpuID = field.NewInt64(table, "spu_id")
	p.SpuName = field.NewString(table, "spu_name")
	p.PicUrl = field.NewString(table, "pic_url")
	p.SkuID = field.NewInt64(table, "sku_id")
	p.Count = field.NewInt(table, "count")
	p.UserID = field.NewInt64(table, "user_id")
	p.Nickname = field.NewString(table, "nickname")
	p.Avatar = field.NewString(table, "avatar")
	p.HeadID = field.NewInt64(table, "head_id")
	p.Status = field.NewInt(table, "status")
	p.OrderID = field.NewInt64(table, "order_id")
	p.UserSize = field.NewInt(table, "user_size")
	p.UserCount = field.NewInt(table, "user_count")
	p.VirtualGroup = field.NewBool(table, "virtual_group")
	p.ExpireTime = field.NewTime(table, "expire_time")
	p.StartTime = field.NewTime(table, "start_time")
	p.EndTime = field.NewTime(table, "end_time")
	p.Creator = field.NewString(table, "creator")
	p.Updater = field.NewString(table, "updater")
	p.CreatedAt = field.NewTime(table, "create_time")
	p.UpdatedAt = field.NewTime(table, "update_time")
	p.Deleted = field.NewField(table, "deleted")
	p.TenantID = field.NewInt64(table, "tenant_id")

	p.fillFieldMap()

	return p
}

func (p *promotionCombinationRecord) WithContext(ctx context.Context) IPromotionCombinationRecordDo {
	return p.promotionCombinationRecordDo.WithContext(ctx)
}

func (p promotionCombinationRecord) TableName() string {
	return p.promotionCombinationRecordDo.TableName()
}

func (p promotionCombinationRecord) Alias() string { return p.promotionCombinationRecordDo.Alias() }

func (p promotionCombinationRecord) Columns(cols ...field.Expr) gen.Columns {
	return p.promotionCombinationRecordDo.Columns(cols...)
}

func (p *promotionCombinationRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *promotionCombinationRecord) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 26)
	p.fieldMap["id"] = p.ID
	p.fieldMap["activity_id"] = p.ActivityID
	p.fieldMap["combination_price"] = p.CombinationPrice
	p.fieldMap["spu_id"] = p.SpuID
	p.fieldMap["spu_name"] = p.SpuName
	p.fieldMap["pic_url"] = p.PicUrl
	p.fieldMap["sku_id"] = p.SkuID
	p.fieldMap["count"] = p.Count
	p.fieldMap["user_id"] = p.UserID
	p.fieldMap["nickname"] = p.Nickname
	p.fieldMap["avatar"] = p.Avatar
	p.fieldMap["head_id"] = p.HeadID
	p.fieldMap["status"] = p.Status
	p.fieldMap["order_id"] = p.OrderID
	p.fieldMap["user_size"] = p.UserSize
	p.fieldMap["user_count"] = p.UserCount
	p.fieldMap["virtual_group"] = p.VirtualGroup
	p.fieldMap["expire_time"] = p.ExpireTime
	p.fieldMap["start_time"] = p.StartTime
	p.fieldMap["end_time"] = p.EndTime
	p.fieldMap["creator"] = p.Creator
	p.fieldMap["updater"] = p.Updater
	p.fieldMap["create_time"] = p.CreatedAt
	p.fieldMap["update_time"] = p.UpdatedAt
	p.fieldMap["deleted"] = p.Deleted
	p.fieldMap["tenant_id"] = p.TenantID
}

func (p promotionCombinationRecord) clone(db *gorm.DB) promotionCombinationRecord {
	p.promotionCombinationRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p promotionCombinationRecord) replaceDB(db *gorm.DB) promotionCombinationRecord {
	p.promotionCombinationRecordDo.ReplaceDB(db)
	return p
}

type promotionCombinationRecordDo struct{ gen.DO }

type IPromotionCombinationRecordDo interface {
	gen.SubQuery
	Debug() IPromotionCombinationRecordDo
	WithContext(ctx context.Context) IPromotionCombinationRecordDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPromotionCombinationRecordDo
	WriteDB() IPromotionCombinationRecordDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPromotionCombinationRecordDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPromotionCombinationRecordDo
	Not(conds ...gen.Condition) IPromotionCombinationRecordDo
	Or(conds ...gen.Condition) IPromotionCombinationRecordDo
	Select(conds ...field.Expr) IPromotionCombinationRecordDo
	Where(conds ...gen.Condition) IPromotionCombinationRecordDo
	Order(conds ...field.Expr) IPromotionCombinationRecordDo
	Distinct(cols ...field.Expr) IPromotionCombinationRecordDo
	Omit(cols ...field.Expr) IPromotionCombinationRecordDo
	Join(table schema.Tabler, on ...field.Expr) IPromotionCombinationRecordDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPromotionCombinationRecordDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPromotionCombinationRecordDo
	Group(cols ...field.Expr) IPromotionCombinationRecordDo
	Having(conds ...gen.Condition) IPromotionCombinationRecordDo
	Limit(limit int) IPromotionCombinationRecordDo
	Offset(offset int) IPromotionCombinationRecordDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPromotionCombinationRecordDo
	Unscoped() IPromotionCombinationRecordDo
	Create(values ...*promotion.PromotionCombinationRecord) error
	CreateInBatches(values []*promotion.PromotionCombinationRecord, batchSize int) error
	Save(values ...*promotion.PromotionCombinationRecord) error
	First() (*promotion.PromotionCombinationRecord, error)
	Take() (*promotion.PromotionCombinationRecord, error)
	Last() (*promotion.PromotionCombinationRecord, error)
	Find() ([]*promotion.PromotionCombinationRecord, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*promotion.PromotionCombinationRecord, err error)
	FindInBatches(result *[]*promotion.PromotionCombinationRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*promotion.PromotionCombinationRecord) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPromotionCombinationRecordDo
	Assign(attrs ...field.AssignExpr) IPromotionCombinationRecordDo
	Joins(fields ...field.RelationField) IPromotionCombinationRecordDo
	Preload(fields ...field.RelationField) IPromotionCombinationRecordDo
	FirstOrInit() (*promotion.PromotionCombinationRecord, error)
	FirstOrCreate() (*promotion.PromotionCombinationRecord, error)
	FindByPage(offset int, limit int) (result []*promotion.PromotionCombinationRecord, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPromotionCombinationRecordDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p promotionCombinationRecordDo) Debug() IPromotionCombinationRecordDo {
	return p.withDO(p.DO.Debug())
}

func (p promotionCombinationRecordDo) WithContext(ctx context.Context) IPromotionCombinationRecordDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p promotionCombinationRecordDo) ReadDB() IPromotionCombinationRecordDo {
	return p.Clauses(dbresolver.Read)
}

func (p promotionCombinationRecordDo) WriteDB() IPromotionCombinationRecordDo {
	return p.Clauses(dbresolver.Write)
}

func (p promotionCombinationRecordDo) Session(config *gorm.Session) IPromotionCombinationRecordDo {
	return p.withDO(p.DO.Session(config))
}

func (p promotionCombinationRecordDo) Clauses(conds ...clause.Expression) IPromotionCombinationRecordDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p promotionCombinationRecordDo) Returning(value interface{}, columns ...string) IPromotionCombinationRecordDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p promotionCombinationRecordDo) Not(conds ...gen.Condition) IPromotionCombinationRecordDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p promotionCombinationRecordDo) Or(conds ...gen.Condition) IPromotionCombinationRecordDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p promotionCombinationRecordDo) Select(conds ...field.Expr) IPromotionCombinationRecordDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p promotionCombinationRecordDo) Where(conds ...gen.Condition) IPromotionCombinationRecordDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p promotionCombinationRecordDo) Order(conds ...field.Expr) IPromotionCombinationRecordDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p promotionCombinationRecordDo) Distinct(cols ...field.Expr) IPromotionCombinationRecordDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p promotionCombinationRecordDo) Omit(cols ...field.Expr) IPromotionCombinationRecordDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p promotionCombinationRecordDo) Join(table schema.Tabler, on ...field.Expr) IPromotionCombinationRecordDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p promotionCombinationRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPromotionCombinationRecordDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p promotionCombinationRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) IPromotionCombinationRecordDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p promotionCombinationRecordDo) Group(cols ...field.Expr) IPromotionCombinationRecordDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p promotionCombinationRecordDo) Having(conds ...gen.Condition) IPromotionCombinationRecordDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p promotionCombinationRecordDo) Limit(limit int) IPromotionCombinationRecordDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p promotionCombinationRecordDo) Offset(offset int) IPromotionCombinationRecordDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p promotionCombinationRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPromotionCombinationRecordDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p promotionCombinationRecordDo) Unscoped() IPromotionCombinationRecordDo {
	return p.withDO(p.DO.Unscoped())
}

func (p promotionCombinationRecordDo) Create(values ...*promotion.PromotionCombinationRecord) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p promotionCombinationRecordDo) CreateInBatches(values []*promotion.PromotionCombinationRecord, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p promotionCombinationRecordDo) Save(values ...*promotion.PromotionCombinationRecord) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p promotionCombinationRecordDo) First() (*promotion.PromotionCombinationRecord, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionCombinationRecord), nil
	}
}

func (p promotionCombinationRecordDo) Take() (*promotion.PromotionCombinationRecord, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionCombinationRecord), nil
	}
}

func (p promotionCombinationRecordDo) Last() (*promotion.PromotionCombinationRecord, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionCombinationRecord), nil
	}
}

func (p promotionCombinationRecordDo) Find() ([]*promotion.PromotionCombinationRecord, error) {
	result, err := p.DO.Find()
	return result.([]*promotion.PromotionCombinationRecord), err
}

func (p promotionCombinationRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*promotion.PromotionCombinationRecord, err error) {
	buf := make([]*promotion.PromotionCombinationRecord, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p promotionCombinationRecordDo) FindInBatches(result *[]*promotion.PromotionCombinationRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p promotionCombinationRecordDo) Attrs(attrs ...field.AssignExpr) IPromotionCombinationRecordDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p promotionCombinationRecordDo) Assign(attrs ...field.AssignExpr) IPromotionCombinationRecordDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p promotionCombinationRecordDo) Joins(fields ...field.RelationField) IPromotionCombinationRecordDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p promotionCombinationRecordDo) Preload(fields ...field.RelationField) IPromotionCombinationRecordDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p promotionCombinationRecordDo) FirstOrInit() (*promotion.PromotionCombinationRecord, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionCombinationRecord), nil
	}
}

func (p promotionCombinationRecordDo) FirstOrCreate() (*promotion.PromotionCombinationRecord, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionCombinationRecord), nil
	}
}

func (p promotionCombinationRecordDo) FindByPage(offset int, limit int) (result []*promotion.PromotionCombinationRecord, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p promotionCombinationRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p promotionCombinationRecordDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p promotionCombinationRecordDo) Delete(models ...*promotion.PromotionCombinationRecord) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *promotionCombinationRecordDo) withDO(do gen.Dao) *promotionCombinationRecordDo {
	p.DO = *do.(*gen.DO)
	return p
}
