// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend-go/internal/model/promotion"
)

func newPromotionCouponTemplate(db *gorm.DB, opts ...gen.DOOption) promotionCouponTemplate {
	_promotionCouponTemplate := promotionCouponTemplate{}

	_promotionCouponTemplate.promotionCouponTemplateDo.UseDB(db, opts...)
	_promotionCouponTemplate.promotionCouponTemplateDo.UseModel(&promotion.PromotionCouponTemplate{})

	tableName := _promotionCouponTemplate.promotionCouponTemplateDo.TableName()
	_promotionCouponTemplate.ALL = field.NewAsterisk(tableName)
	_promotionCouponTemplate.ID = field.NewInt64(tableName, "id")
	_promotionCouponTemplate.Name = field.NewString(tableName, "name")
	_promotionCouponTemplate.Status = field.NewInt(tableName, "status")
	_promotionCouponTemplate.TotalCount = field.NewInt(tableName, "total_count")
	_promotionCouponTemplate.TakeCount = field.NewInt(tableName, "take_count")
	_promotionCouponTemplate.TakeLimitCount = field.NewInt(tableName, "take_limit_count")
	_promotionCouponTemplate.TakeType = field.NewInt(tableName, "take_type")
	_promotionCouponTemplate.UsePriceMin = field.NewInt(tableName, "use_price_min")
	_promotionCouponTemplate.ProductScope = field.NewInt(tableName, "product_scope")
	_promotionCouponTemplate.ProductScopeValues = field.NewField(tableName, "product_scope_values")
	_promotionCouponTemplate.ValidityType = field.NewInt(tableName, "validity_type")
	_promotionCouponTemplate.ValidStartTime = field.NewTime(tableName, "valid_start_time")
	_promotionCouponTemplate.ValidEndTime = field.NewTime(tableName, "valid_end_time")
	_promotionCouponTemplate.FixedStartTerm = field.NewInt(tableName, "fixed_start_term")
	_promotionCouponTemplate.FixedEndTerm = field.NewInt(tableName, "fixed_end_term")
	_promotionCouponTemplate.DiscountType = field.NewInt(tableName, "discount_type")
	_promotionCouponTemplate.DiscountPrice = field.NewInt(tableName, "discount_price")
	_promotionCouponTemplate.DiscountPercent = field.NewInt(tableName, "discount_percent")
	_promotionCouponTemplate.DiscountLimit = field.NewInt(tableName, "discount_limit")
	_promotionCouponTemplate.Creator = field.NewString(tableName, "creator")
	_promotionCouponTemplate.Updater = field.NewString(tableName, "updater")
	_promotionCouponTemplate.CreatedAt = field.NewTime(tableName, "create_time")
	_promotionCouponTemplate.UpdatedAt = field.NewTime(tableName, "update_time")
	_promotionCouponTemplate.DeletedAt = field.NewField(tableName, "deleted")
	_promotionCouponTemplate.Deleted = field.NewBool(tableName, "deleted")

	_promotionCouponTemplate.fillFieldMap()

	return _promotionCouponTemplate
}

type promotionCouponTemplate struct {
	promotionCouponTemplateDo promotionCouponTemplateDo

	ALL                field.Asterisk
	ID                 field.Int64  // 模板编号
	Name               field.String // 优惠券名称
	Status             field.Int    // 状态
	TotalCount         field.Int    // 发放总量
	TakeCount          field.Int    // 已领取数量
	TakeLimitCount     field.Int    // 每人限领数量
	TakeType           field.Int    // 领取方式
	UsePriceMin        field.Int    // 最低消费金额
	ProductScope       field.Int    // 商品范围
	ProductScopeValues field.Field  // 商品范围值
	ValidityType       field.Int    // 有效期类型
	ValidStartTime     field.Time   // 固定日期-开始
	ValidEndTime       field.Time   // 固定日期-结束
	FixedStartTerm     field.Int    // 领取后生效天数
	FixedEndTerm       field.Int    // 有效期天数
	DiscountType       field.Int    // 优惠类型
	DiscountPrice      field.Int    // 优惠金额
	DiscountPercent    field.Int    // 折扣百分比
	DiscountLimit      field.Int    // 最多优惠金额
	Creator            field.String // 创建者
	Updater            field.String // 更新者
	CreatedAt          field.Time   // 创建时间
	UpdatedAt          field.Time   // 更新时间
	DeletedAt          field.Field  // 删除时间
	Deleted            field.Bool   // 是否删除

	fieldMap map[string]field.Expr
}

func (p promotionCouponTemplate) Table(newTableName string) *promotionCouponTemplate {
	p.promotionCouponTemplateDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p promotionCouponTemplate) As(alias string) *promotionCouponTemplate {
	p.promotionCouponTemplateDo.DO = *(p.promotionCouponTemplateDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *promotionCouponTemplate) updateTableName(table string) *promotionCouponTemplate {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.Name = field.NewString(table, "name")
	p.Status = field.NewInt(table, "status")
	p.TotalCount = field.NewInt(table, "total_count")
	p.TakeCount = field.NewInt(table, "take_count")
	p.TakeLimitCount = field.NewInt(table, "take_limit_count")
	p.TakeType = field.NewInt(table, "take_type")
	p.UsePriceMin = field.NewInt(table, "use_price_min")
	p.ProductScope = field.NewInt(table, "product_scope")
	p.ProductScopeValues = field.NewField(table, "product_scope_values")
	p.ValidityType = field.NewInt(table, "validity_type")
	p.ValidStartTime = field.NewTime(table, "valid_start_time")
	p.ValidEndTime = field.NewTime(table, "valid_end_time")
	p.FixedStartTerm = field.NewInt(table, "fixed_start_term")
	p.FixedEndTerm = field.NewInt(table, "fixed_end_term")
	p.DiscountType = field.NewInt(table, "discount_type")
	p.DiscountPrice = field.NewInt(table, "discount_price")
	p.DiscountPercent = field.NewInt(table, "discount_percent")
	p.DiscountLimit = field.NewInt(table, "discount_limit")
	p.Creator = field.NewString(table, "creator")
	p.Updater = field.NewString(table, "updater")
	p.CreatedAt = field.NewTime(table, "create_time")
	p.UpdatedAt = field.NewTime(table, "update_time")
	p.DeletedAt = field.NewField(table, "deleted")
	p.Deleted = field.NewBool(table, "deleted")

	p.fillFieldMap()

	return p
}

func (p *promotionCouponTemplate) WithContext(ctx context.Context) IPromotionCouponTemplateDo {
	return p.promotionCouponTemplateDo.WithContext(ctx)
}

func (p promotionCouponTemplate) TableName() string { return p.promotionCouponTemplateDo.TableName() }

func (p promotionCouponTemplate) Alias() string { return p.promotionCouponTemplateDo.Alias() }

func (p promotionCouponTemplate) Columns(cols ...field.Expr) gen.Columns {
	return p.promotionCouponTemplateDo.Columns(cols...)
}

func (p *promotionCouponTemplate) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *promotionCouponTemplate) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 25)
	p.fieldMap["id"] = p.ID
	p.fieldMap["name"] = p.Name
	p.fieldMap["status"] = p.Status
	p.fieldMap["total_count"] = p.TotalCount
	p.fieldMap["take_count"] = p.TakeCount
	p.fieldMap["take_limit_count"] = p.TakeLimitCount
	p.fieldMap["take_type"] = p.TakeType
	p.fieldMap["use_price_min"] = p.UsePriceMin
	p.fieldMap["product_scope"] = p.ProductScope
	p.fieldMap["product_scope_values"] = p.ProductScopeValues
	p.fieldMap["validity_type"] = p.ValidityType
	p.fieldMap["valid_start_time"] = p.ValidStartTime
	p.fieldMap["valid_end_time"] = p.ValidEndTime
	p.fieldMap["fixed_start_term"] = p.FixedStartTerm
	p.fieldMap["fixed_end_term"] = p.FixedEndTerm
	p.fieldMap["discount_type"] = p.DiscountType
	p.fieldMap["discount_price"] = p.DiscountPrice
	p.fieldMap["discount_percent"] = p.DiscountPercent
	p.fieldMap["discount_limit"] = p.DiscountLimit
	p.fieldMap["creator"] = p.Creator
	p.fieldMap["updater"] = p.Updater
	p.fieldMap["create_time"] = p.CreatedAt
	p.fieldMap["update_time"] = p.UpdatedAt
	p.fieldMap["deleted"] = p.DeletedAt
	p.fieldMap["deleted"] = p.Deleted
}

func (p promotionCouponTemplate) clone(db *gorm.DB) promotionCouponTemplate {
	p.promotionCouponTemplateDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p promotionCouponTemplate) replaceDB(db *gorm.DB) promotionCouponTemplate {
	p.promotionCouponTemplateDo.ReplaceDB(db)
	return p
}

type promotionCouponTemplateDo struct{ gen.DO }

type IPromotionCouponTemplateDo interface {
	gen.SubQuery
	Debug() IPromotionCouponTemplateDo
	WithContext(ctx context.Context) IPromotionCouponTemplateDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPromotionCouponTemplateDo
	WriteDB() IPromotionCouponTemplateDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPromotionCouponTemplateDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPromotionCouponTemplateDo
	Not(conds ...gen.Condition) IPromotionCouponTemplateDo
	Or(conds ...gen.Condition) IPromotionCouponTemplateDo
	Select(conds ...field.Expr) IPromotionCouponTemplateDo
	Where(conds ...gen.Condition) IPromotionCouponTemplateDo
	Order(conds ...field.Expr) IPromotionCouponTemplateDo
	Distinct(cols ...field.Expr) IPromotionCouponTemplateDo
	Omit(cols ...field.Expr) IPromotionCouponTemplateDo
	Join(table schema.Tabler, on ...field.Expr) IPromotionCouponTemplateDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPromotionCouponTemplateDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPromotionCouponTemplateDo
	Group(cols ...field.Expr) IPromotionCouponTemplateDo
	Having(conds ...gen.Condition) IPromotionCouponTemplateDo
	Limit(limit int) IPromotionCouponTemplateDo
	Offset(offset int) IPromotionCouponTemplateDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPromotionCouponTemplateDo
	Unscoped() IPromotionCouponTemplateDo
	Create(values ...*promotion.PromotionCouponTemplate) error
	CreateInBatches(values []*promotion.PromotionCouponTemplate, batchSize int) error
	Save(values ...*promotion.PromotionCouponTemplate) error
	First() (*promotion.PromotionCouponTemplate, error)
	Take() (*promotion.PromotionCouponTemplate, error)
	Last() (*promotion.PromotionCouponTemplate, error)
	Find() ([]*promotion.PromotionCouponTemplate, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*promotion.PromotionCouponTemplate, err error)
	FindInBatches(result *[]*promotion.PromotionCouponTemplate, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*promotion.PromotionCouponTemplate) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPromotionCouponTemplateDo
	Assign(attrs ...field.AssignExpr) IPromotionCouponTemplateDo
	Joins(fields ...field.RelationField) IPromotionCouponTemplateDo
	Preload(fields ...field.RelationField) IPromotionCouponTemplateDo
	FirstOrInit() (*promotion.PromotionCouponTemplate, error)
	FirstOrCreate() (*promotion.PromotionCouponTemplate, error)
	FindByPage(offset int, limit int) (result []*promotion.PromotionCouponTemplate, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPromotionCouponTemplateDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p promotionCouponTemplateDo) Debug() IPromotionCouponTemplateDo {
	return p.withDO(p.DO.Debug())
}

func (p promotionCouponTemplateDo) WithContext(ctx context.Context) IPromotionCouponTemplateDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p promotionCouponTemplateDo) ReadDB() IPromotionCouponTemplateDo {
	return p.Clauses(dbresolver.Read)
}

func (p promotionCouponTemplateDo) WriteDB() IPromotionCouponTemplateDo {
	return p.Clauses(dbresolver.Write)
}

func (p promotionCouponTemplateDo) Session(config *gorm.Session) IPromotionCouponTemplateDo {
	return p.withDO(p.DO.Session(config))
}

func (p promotionCouponTemplateDo) Clauses(conds ...clause.Expression) IPromotionCouponTemplateDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p promotionCouponTemplateDo) Returning(value interface{}, columns ...string) IPromotionCouponTemplateDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p promotionCouponTemplateDo) Not(conds ...gen.Condition) IPromotionCouponTemplateDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p promotionCouponTemplateDo) Or(conds ...gen.Condition) IPromotionCouponTemplateDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p promotionCouponTemplateDo) Select(conds ...field.Expr) IPromotionCouponTemplateDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p promotionCouponTemplateDo) Where(conds ...gen.Condition) IPromotionCouponTemplateDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p promotionCouponTemplateDo) Order(conds ...field.Expr) IPromotionCouponTemplateDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p promotionCouponTemplateDo) Distinct(cols ...field.Expr) IPromotionCouponTemplateDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p promotionCouponTemplateDo) Omit(cols ...field.Expr) IPromotionCouponTemplateDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p promotionCouponTemplateDo) Join(table schema.Tabler, on ...field.Expr) IPromotionCouponTemplateDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p promotionCouponTemplateDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPromotionCouponTemplateDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p promotionCouponTemplateDo) RightJoin(table schema.Tabler, on ...field.Expr) IPromotionCouponTemplateDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p promotionCouponTemplateDo) Group(cols ...field.Expr) IPromotionCouponTemplateDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p promotionCouponTemplateDo) Having(conds ...gen.Condition) IPromotionCouponTemplateDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p promotionCouponTemplateDo) Limit(limit int) IPromotionCouponTemplateDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p promotionCouponTemplateDo) Offset(offset int) IPromotionCouponTemplateDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p promotionCouponTemplateDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPromotionCouponTemplateDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p promotionCouponTemplateDo) Unscoped() IPromotionCouponTemplateDo {
	return p.withDO(p.DO.Unscoped())
}

func (p promotionCouponTemplateDo) Create(values ...*promotion.PromotionCouponTemplate) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p promotionCouponTemplateDo) CreateInBatches(values []*promotion.PromotionCouponTemplate, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p promotionCouponTemplateDo) Save(values ...*promotion.PromotionCouponTemplate) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p promotionCouponTemplateDo) First() (*promotion.PromotionCouponTemplate, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionCouponTemplate), nil
	}
}

func (p promotionCouponTemplateDo) Take() (*promotion.PromotionCouponTemplate, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionCouponTemplate), nil
	}
}

func (p promotionCouponTemplateDo) Last() (*promotion.PromotionCouponTemplate, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionCouponTemplate), nil
	}
}

func (p promotionCouponTemplateDo) Find() ([]*promotion.PromotionCouponTemplate, error) {
	result, err := p.DO.Find()
	return result.([]*promotion.PromotionCouponTemplate), err
}

func (p promotionCouponTemplateDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*promotion.PromotionCouponTemplate, err error) {
	buf := make([]*promotion.PromotionCouponTemplate, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p promotionCouponTemplateDo) FindInBatches(result *[]*promotion.PromotionCouponTemplate, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p promotionCouponTemplateDo) Attrs(attrs ...field.AssignExpr) IPromotionCouponTemplateDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p promotionCouponTemplateDo) Assign(attrs ...field.AssignExpr) IPromotionCouponTemplateDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p promotionCouponTemplateDo) Joins(fields ...field.RelationField) IPromotionCouponTemplateDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p promotionCouponTemplateDo) Preload(fields ...field.RelationField) IPromotionCouponTemplateDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p promotionCouponTemplateDo) FirstOrInit() (*promotion.PromotionCouponTemplate, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionCouponTemplate), nil
	}
}

func (p promotionCouponTemplateDo) FirstOrCreate() (*promotion.PromotionCouponTemplate, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionCouponTemplate), nil
	}
}

func (p promotionCouponTemplateDo) FindByPage(offset int, limit int) (result []*promotion.PromotionCouponTemplate, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p promotionCouponTemplateDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p promotionCouponTemplateDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p promotionCouponTemplateDo) Delete(models ...*promotion.PromotionCouponTemplate) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *promotionCouponTemplateDo) withDO(do gen.Dao) *promotionCouponTemplateDo {
	p.DO = *do.(*gen.DO)
	return p
}
