// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend-go/internal/model/promotion"
)

func newPromotionRewardActivity(db *gorm.DB, opts ...gen.DOOption) promotionRewardActivity {
	_promotionRewardActivity := promotionRewardActivity{}

	_promotionRewardActivity.promotionRewardActivityDo.UseDB(db, opts...)
	_promotionRewardActivity.promotionRewardActivityDo.UseModel(&promotion.PromotionRewardActivity{})

	tableName := _promotionRewardActivity.promotionRewardActivityDo.TableName()
	_promotionRewardActivity.ALL = field.NewAsterisk(tableName)
	_promotionRewardActivity.ID = field.NewInt64(tableName, "id")
	_promotionRewardActivity.Name = field.NewString(tableName, "name")
	_promotionRewardActivity.Status = field.NewInt(tableName, "status")
	_promotionRewardActivity.StartTime = field.NewTime(tableName, "start_time")
	_promotionRewardActivity.EndTime = field.NewTime(tableName, "end_time")
	_promotionRewardActivity.ProductScope = field.NewInt(tableName, "product_scope")
	_promotionRewardActivity.ProductScopeValues = field.NewString(tableName, "product_scope_values")
	_promotionRewardActivity.ConditionType = field.NewInt(tableName, "condition_type")
	_promotionRewardActivity.Rules = field.NewString(tableName, "rules")
	_promotionRewardActivity.Sort = field.NewInt(tableName, "sort")
	_promotionRewardActivity.Remark = field.NewString(tableName, "remark")
	_promotionRewardActivity.Creator = field.NewString(tableName, "creator")
	_promotionRewardActivity.Updater = field.NewString(tableName, "updater")
	_promotionRewardActivity.CreatedAt = field.NewTime(tableName, "create_time")
	_promotionRewardActivity.UpdatedAt = field.NewTime(tableName, "update_time")
	_promotionRewardActivity.DeletedAt = field.NewField(tableName, "deleted")
	_promotionRewardActivity.Deleted = field.NewBool(tableName, "deleted")

	_promotionRewardActivity.fillFieldMap()

	return _promotionRewardActivity
}

type promotionRewardActivity struct {
	promotionRewardActivityDo promotionRewardActivityDo

	ALL                field.Asterisk
	ID                 field.Int64  // 活动编号
	Name               field.String // 活动名称
	Status             field.Int    // 状态
	StartTime          field.Time   // 开始时间
	EndTime            field.Time   // 结束时间
	ProductScope       field.Int    // 商品范围
	ProductScopeValues field.String // 商品范围值
	ConditionType      field.Int    // 条件类型
	Rules              field.String // 优惠规则
	Sort               field.Int    // 排序
	Remark             field.String // 备注
	Creator            field.String // 创建者
	Updater            field.String // 更新者
	CreatedAt          field.Time   // 创建时间
	UpdatedAt          field.Time   // 更新时间
	DeletedAt          field.Field  // 删除时间
	Deleted            field.Bool   // 是否删除

	fieldMap map[string]field.Expr
}

func (p promotionRewardActivity) Table(newTableName string) *promotionRewardActivity {
	p.promotionRewardActivityDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p promotionRewardActivity) As(alias string) *promotionRewardActivity {
	p.promotionRewardActivityDo.DO = *(p.promotionRewardActivityDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *promotionRewardActivity) updateTableName(table string) *promotionRewardActivity {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.Name = field.NewString(table, "name")
	p.Status = field.NewInt(table, "status")
	p.StartTime = field.NewTime(table, "start_time")
	p.EndTime = field.NewTime(table, "end_time")
	p.ProductScope = field.NewInt(table, "product_scope")
	p.ProductScopeValues = field.NewString(table, "product_scope_values")
	p.ConditionType = field.NewInt(table, "condition_type")
	p.Rules = field.NewString(table, "rules")
	p.Sort = field.NewInt(table, "sort")
	p.Remark = field.NewString(table, "remark")
	p.Creator = field.NewString(table, "creator")
	p.Updater = field.NewString(table, "updater")
	p.CreatedAt = field.NewTime(table, "create_time")
	p.UpdatedAt = field.NewTime(table, "update_time")
	p.DeletedAt = field.NewField(table, "deleted")
	p.Deleted = field.NewBool(table, "deleted")

	p.fillFieldMap()

	return p
}

func (p *promotionRewardActivity) WithContext(ctx context.Context) IPromotionRewardActivityDo {
	return p.promotionRewardActivityDo.WithContext(ctx)
}

func (p promotionRewardActivity) TableName() string { return p.promotionRewardActivityDo.TableName() }

func (p promotionRewardActivity) Alias() string { return p.promotionRewardActivityDo.Alias() }

func (p promotionRewardActivity) Columns(cols ...field.Expr) gen.Columns {
	return p.promotionRewardActivityDo.Columns(cols...)
}

func (p *promotionRewardActivity) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *promotionRewardActivity) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 17)
	p.fieldMap["id"] = p.ID
	p.fieldMap["name"] = p.Name
	p.fieldMap["status"] = p.Status
	p.fieldMap["start_time"] = p.StartTime
	p.fieldMap["end_time"] = p.EndTime
	p.fieldMap["product_scope"] = p.ProductScope
	p.fieldMap["product_scope_values"] = p.ProductScopeValues
	p.fieldMap["condition_type"] = p.ConditionType
	p.fieldMap["rules"] = p.Rules
	p.fieldMap["sort"] = p.Sort
	p.fieldMap["remark"] = p.Remark
	p.fieldMap["creator"] = p.Creator
	p.fieldMap["updater"] = p.Updater
	p.fieldMap["create_time"] = p.CreatedAt
	p.fieldMap["update_time"] = p.UpdatedAt
	p.fieldMap["deleted"] = p.DeletedAt
	p.fieldMap["deleted"] = p.Deleted
}

func (p promotionRewardActivity) clone(db *gorm.DB) promotionRewardActivity {
	p.promotionRewardActivityDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p promotionRewardActivity) replaceDB(db *gorm.DB) promotionRewardActivity {
	p.promotionRewardActivityDo.ReplaceDB(db)
	return p
}

type promotionRewardActivityDo struct{ gen.DO }

type IPromotionRewardActivityDo interface {
	gen.SubQuery
	Debug() IPromotionRewardActivityDo
	WithContext(ctx context.Context) IPromotionRewardActivityDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPromotionRewardActivityDo
	WriteDB() IPromotionRewardActivityDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPromotionRewardActivityDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPromotionRewardActivityDo
	Not(conds ...gen.Condition) IPromotionRewardActivityDo
	Or(conds ...gen.Condition) IPromotionRewardActivityDo
	Select(conds ...field.Expr) IPromotionRewardActivityDo
	Where(conds ...gen.Condition) IPromotionRewardActivityDo
	Order(conds ...field.Expr) IPromotionRewardActivityDo
	Distinct(cols ...field.Expr) IPromotionRewardActivityDo
	Omit(cols ...field.Expr) IPromotionRewardActivityDo
	Join(table schema.Tabler, on ...field.Expr) IPromotionRewardActivityDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPromotionRewardActivityDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPromotionRewardActivityDo
	Group(cols ...field.Expr) IPromotionRewardActivityDo
	Having(conds ...gen.Condition) IPromotionRewardActivityDo
	Limit(limit int) IPromotionRewardActivityDo
	Offset(offset int) IPromotionRewardActivityDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPromotionRewardActivityDo
	Unscoped() IPromotionRewardActivityDo
	Create(values ...*promotion.PromotionRewardActivity) error
	CreateInBatches(values []*promotion.PromotionRewardActivity, batchSize int) error
	Save(values ...*promotion.PromotionRewardActivity) error
	First() (*promotion.PromotionRewardActivity, error)
	Take() (*promotion.PromotionRewardActivity, error)
	Last() (*promotion.PromotionRewardActivity, error)
	Find() ([]*promotion.PromotionRewardActivity, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*promotion.PromotionRewardActivity, err error)
	FindInBatches(result *[]*promotion.PromotionRewardActivity, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*promotion.PromotionRewardActivity) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPromotionRewardActivityDo
	Assign(attrs ...field.AssignExpr) IPromotionRewardActivityDo
	Joins(fields ...field.RelationField) IPromotionRewardActivityDo
	Preload(fields ...field.RelationField) IPromotionRewardActivityDo
	FirstOrInit() (*promotion.PromotionRewardActivity, error)
	FirstOrCreate() (*promotion.PromotionRewardActivity, error)
	FindByPage(offset int, limit int) (result []*promotion.PromotionRewardActivity, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPromotionRewardActivityDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p promotionRewardActivityDo) Debug() IPromotionRewardActivityDo {
	return p.withDO(p.DO.Debug())
}

func (p promotionRewardActivityDo) WithContext(ctx context.Context) IPromotionRewardActivityDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p promotionRewardActivityDo) ReadDB() IPromotionRewardActivityDo {
	return p.Clauses(dbresolver.Read)
}

func (p promotionRewardActivityDo) WriteDB() IPromotionRewardActivityDo {
	return p.Clauses(dbresolver.Write)
}

func (p promotionRewardActivityDo) Session(config *gorm.Session) IPromotionRewardActivityDo {
	return p.withDO(p.DO.Session(config))
}

func (p promotionRewardActivityDo) Clauses(conds ...clause.Expression) IPromotionRewardActivityDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p promotionRewardActivityDo) Returning(value interface{}, columns ...string) IPromotionRewardActivityDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p promotionRewardActivityDo) Not(conds ...gen.Condition) IPromotionRewardActivityDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p promotionRewardActivityDo) Or(conds ...gen.Condition) IPromotionRewardActivityDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p promotionRewardActivityDo) Select(conds ...field.Expr) IPromotionRewardActivityDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p promotionRewardActivityDo) Where(conds ...gen.Condition) IPromotionRewardActivityDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p promotionRewardActivityDo) Order(conds ...field.Expr) IPromotionRewardActivityDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p promotionRewardActivityDo) Distinct(cols ...field.Expr) IPromotionRewardActivityDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p promotionRewardActivityDo) Omit(cols ...field.Expr) IPromotionRewardActivityDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p promotionRewardActivityDo) Join(table schema.Tabler, on ...field.Expr) IPromotionRewardActivityDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p promotionRewardActivityDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPromotionRewardActivityDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p promotionRewardActivityDo) RightJoin(table schema.Tabler, on ...field.Expr) IPromotionRewardActivityDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p promotionRewardActivityDo) Group(cols ...field.Expr) IPromotionRewardActivityDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p promotionRewardActivityDo) Having(conds ...gen.Condition) IPromotionRewardActivityDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p promotionRewardActivityDo) Limit(limit int) IPromotionRewardActivityDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p promotionRewardActivityDo) Offset(offset int) IPromotionRewardActivityDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p promotionRewardActivityDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPromotionRewardActivityDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p promotionRewardActivityDo) Unscoped() IPromotionRewardActivityDo {
	return p.withDO(p.DO.Unscoped())
}

func (p promotionRewardActivityDo) Create(values ...*promotion.PromotionRewardActivity) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p promotionRewardActivityDo) CreateInBatches(values []*promotion.PromotionRewardActivity, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p promotionRewardActivityDo) Save(values ...*promotion.PromotionRewardActivity) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p promotionRewardActivityDo) First() (*promotion.PromotionRewardActivity, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionRewardActivity), nil
	}
}

func (p promotionRewardActivityDo) Take() (*promotion.PromotionRewardActivity, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionRewardActivity), nil
	}
}

func (p promotionRewardActivityDo) Last() (*promotion.PromotionRewardActivity, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionRewardActivity), nil
	}
}

func (p promotionRewardActivityDo) Find() ([]*promotion.PromotionRewardActivity, error) {
	result, err := p.DO.Find()
	return result.([]*promotion.PromotionRewardActivity), err
}

func (p promotionRewardActivityDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*promotion.PromotionRewardActivity, err error) {
	buf := make([]*promotion.PromotionRewardActivity, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p promotionRewardActivityDo) FindInBatches(result *[]*promotion.PromotionRewardActivity, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p promotionRewardActivityDo) Attrs(attrs ...field.AssignExpr) IPromotionRewardActivityDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p promotionRewardActivityDo) Assign(attrs ...field.AssignExpr) IPromotionRewardActivityDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p promotionRewardActivityDo) Joins(fields ...field.RelationField) IPromotionRewardActivityDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p promotionRewardActivityDo) Preload(fields ...field.RelationField) IPromotionRewardActivityDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p promotionRewardActivityDo) FirstOrInit() (*promotion.PromotionRewardActivity, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionRewardActivity), nil
	}
}

func (p promotionRewardActivityDo) FirstOrCreate() (*promotion.PromotionRewardActivity, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionRewardActivity), nil
	}
}

func (p promotionRewardActivityDo) FindByPage(offset int, limit int) (result []*promotion.PromotionRewardActivity, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p promotionRewardActivityDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p promotionRewardActivityDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p promotionRewardActivityDo) Delete(models ...*promotion.PromotionRewardActivity) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *promotionRewardActivityDo) withDO(do gen.Dao) *promotionRewardActivityDo {
	p.DO = *do.(*gen.DO)
	return p
}
