// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend-go/internal/model/promotion"
)

func newPromotionSeckillConfig(db *gorm.DB, opts ...gen.DOOption) promotionSeckillConfig {
	_promotionSeckillConfig := promotionSeckillConfig{}

	_promotionSeckillConfig.promotionSeckillConfigDo.UseDB(db, opts...)
	_promotionSeckillConfig.promotionSeckillConfigDo.UseModel(&promotion.PromotionSeckillConfig{})

	tableName := _promotionSeckillConfig.promotionSeckillConfigDo.TableName()
	_promotionSeckillConfig.ALL = field.NewAsterisk(tableName)
	_promotionSeckillConfig.ID = field.NewInt64(tableName, "id")
	_promotionSeckillConfig.Name = field.NewString(tableName, "name")
	_promotionSeckillConfig.StartTime = field.NewString(tableName, "start_time")
	_promotionSeckillConfig.EndTime = field.NewString(tableName, "end_time")
	_promotionSeckillConfig.SliderPicUrls = field.NewField(tableName, "slider_pic_urls")
	_promotionSeckillConfig.Status = field.NewInt(tableName, "status")
	_promotionSeckillConfig.Creator = field.NewString(tableName, "creator")
	_promotionSeckillConfig.Updater = field.NewString(tableName, "updater")
	_promotionSeckillConfig.CreatedAt = field.NewTime(tableName, "create_time")
	_promotionSeckillConfig.UpdatedAt = field.NewTime(tableName, "update_time")
	_promotionSeckillConfig.Deleted = field.NewField(tableName, "deleted")
	_promotionSeckillConfig.TenantID = field.NewInt64(tableName, "tenant_id")

	_promotionSeckillConfig.fillFieldMap()

	return _promotionSeckillConfig
}

type promotionSeckillConfig struct {
	promotionSeckillConfigDo promotionSeckillConfigDo

	ALL           field.Asterisk
	ID            field.Int64  // 编号
	Name          field.String // 秒杀时段名称
	StartTime     field.String // 开始时间点
	EndTime       field.String // 结束时间点
	SliderPicUrls field.Field  // 秒杀轮播图
	Status        field.Int    // 状态
	Creator       field.String // 创建者
	Updater       field.String // 更新者
	CreatedAt     field.Time   // 创建时间
	UpdatedAt     field.Time   // 更新时间
	Deleted       field.Field  // 是否删除
	TenantID      field.Int64  // 租户编号

	fieldMap map[string]field.Expr
}

func (p promotionSeckillConfig) Table(newTableName string) *promotionSeckillConfig {
	p.promotionSeckillConfigDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p promotionSeckillConfig) As(alias string) *promotionSeckillConfig {
	p.promotionSeckillConfigDo.DO = *(p.promotionSeckillConfigDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *promotionSeckillConfig) updateTableName(table string) *promotionSeckillConfig {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.Name = field.NewString(table, "name")
	p.StartTime = field.NewString(table, "start_time")
	p.EndTime = field.NewString(table, "end_time")
	p.SliderPicUrls = field.NewField(table, "slider_pic_urls")
	p.Status = field.NewInt(table, "status")
	p.Creator = field.NewString(table, "creator")
	p.Updater = field.NewString(table, "updater")
	p.CreatedAt = field.NewTime(table, "create_time")
	p.UpdatedAt = field.NewTime(table, "update_time")
	p.Deleted = field.NewField(table, "deleted")
	p.TenantID = field.NewInt64(table, "tenant_id")

	p.fillFieldMap()

	return p
}

func (p *promotionSeckillConfig) WithContext(ctx context.Context) IPromotionSeckillConfigDo {
	return p.promotionSeckillConfigDo.WithContext(ctx)
}

func (p promotionSeckillConfig) TableName() string { return p.promotionSeckillConfigDo.TableName() }

func (p promotionSeckillConfig) Alias() string { return p.promotionSeckillConfigDo.Alias() }

func (p promotionSeckillConfig) Columns(cols ...field.Expr) gen.Columns {
	return p.promotionSeckillConfigDo.Columns(cols...)
}

func (p *promotionSeckillConfig) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *promotionSeckillConfig) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 12)
	p.fieldMap["id"] = p.ID
	p.fieldMap["name"] = p.Name
	p.fieldMap["start_time"] = p.StartTime
	p.fieldMap["end_time"] = p.EndTime
	p.fieldMap["slider_pic_urls"] = p.SliderPicUrls
	p.fieldMap["status"] = p.Status
	p.fieldMap["creator"] = p.Creator
	p.fieldMap["updater"] = p.Updater
	p.fieldMap["create_time"] = p.CreatedAt
	p.fieldMap["update_time"] = p.UpdatedAt
	p.fieldMap["deleted"] = p.Deleted
	p.fieldMap["tenant_id"] = p.TenantID
}

func (p promotionSeckillConfig) clone(db *gorm.DB) promotionSeckillConfig {
	p.promotionSeckillConfigDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p promotionSeckillConfig) replaceDB(db *gorm.DB) promotionSeckillConfig {
	p.promotionSeckillConfigDo.ReplaceDB(db)
	return p
}

type promotionSeckillConfigDo struct{ gen.DO }

type IPromotionSeckillConfigDo interface {
	gen.SubQuery
	Debug() IPromotionSeckillConfigDo
	WithContext(ctx context.Context) IPromotionSeckillConfigDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPromotionSeckillConfigDo
	WriteDB() IPromotionSeckillConfigDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPromotionSeckillConfigDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPromotionSeckillConfigDo
	Not(conds ...gen.Condition) IPromotionSeckillConfigDo
	Or(conds ...gen.Condition) IPromotionSeckillConfigDo
	Select(conds ...field.Expr) IPromotionSeckillConfigDo
	Where(conds ...gen.Condition) IPromotionSeckillConfigDo
	Order(conds ...field.Expr) IPromotionSeckillConfigDo
	Distinct(cols ...field.Expr) IPromotionSeckillConfigDo
	Omit(cols ...field.Expr) IPromotionSeckillConfigDo
	Join(table schema.Tabler, on ...field.Expr) IPromotionSeckillConfigDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPromotionSeckillConfigDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPromotionSeckillConfigDo
	Group(cols ...field.Expr) IPromotionSeckillConfigDo
	Having(conds ...gen.Condition) IPromotionSeckillConfigDo
	Limit(limit int) IPromotionSeckillConfigDo
	Offset(offset int) IPromotionSeckillConfigDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPromotionSeckillConfigDo
	Unscoped() IPromotionSeckillConfigDo
	Create(values ...*promotion.PromotionSeckillConfig) error
	CreateInBatches(values []*promotion.PromotionSeckillConfig, batchSize int) error
	Save(values ...*promotion.PromotionSeckillConfig) error
	First() (*promotion.PromotionSeckillConfig, error)
	Take() (*promotion.PromotionSeckillConfig, error)
	Last() (*promotion.PromotionSeckillConfig, error)
	Find() ([]*promotion.PromotionSeckillConfig, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*promotion.PromotionSeckillConfig, err error)
	FindInBatches(result *[]*promotion.PromotionSeckillConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*promotion.PromotionSeckillConfig) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPromotionSeckillConfigDo
	Assign(attrs ...field.AssignExpr) IPromotionSeckillConfigDo
	Joins(fields ...field.RelationField) IPromotionSeckillConfigDo
	Preload(fields ...field.RelationField) IPromotionSeckillConfigDo
	FirstOrInit() (*promotion.PromotionSeckillConfig, error)
	FirstOrCreate() (*promotion.PromotionSeckillConfig, error)
	FindByPage(offset int, limit int) (result []*promotion.PromotionSeckillConfig, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPromotionSeckillConfigDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p promotionSeckillConfigDo) Debug() IPromotionSeckillConfigDo {
	return p.withDO(p.DO.Debug())
}

func (p promotionSeckillConfigDo) WithContext(ctx context.Context) IPromotionSeckillConfigDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p promotionSeckillConfigDo) ReadDB() IPromotionSeckillConfigDo {
	return p.Clauses(dbresolver.Read)
}

func (p promotionSeckillConfigDo) WriteDB() IPromotionSeckillConfigDo {
	return p.Clauses(dbresolver.Write)
}

func (p promotionSeckillConfigDo) Session(config *gorm.Session) IPromotionSeckillConfigDo {
	return p.withDO(p.DO.Session(config))
}

func (p promotionSeckillConfigDo) Clauses(conds ...clause.Expression) IPromotionSeckillConfigDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p promotionSeckillConfigDo) Returning(value interface{}, columns ...string) IPromotionSeckillConfigDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p promotionSeckillConfigDo) Not(conds ...gen.Condition) IPromotionSeckillConfigDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p promotionSeckillConfigDo) Or(conds ...gen.Condition) IPromotionSeckillConfigDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p promotionSeckillConfigDo) Select(conds ...field.Expr) IPromotionSeckillConfigDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p promotionSeckillConfigDo) Where(conds ...gen.Condition) IPromotionSeckillConfigDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p promotionSeckillConfigDo) Order(conds ...field.Expr) IPromotionSeckillConfigDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p promotionSeckillConfigDo) Distinct(cols ...field.Expr) IPromotionSeckillConfigDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p promotionSeckillConfigDo) Omit(cols ...field.Expr) IPromotionSeckillConfigDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p promotionSeckillConfigDo) Join(table schema.Tabler, on ...field.Expr) IPromotionSeckillConfigDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p promotionSeckillConfigDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPromotionSeckillConfigDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p promotionSeckillConfigDo) RightJoin(table schema.Tabler, on ...field.Expr) IPromotionSeckillConfigDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p promotionSeckillConfigDo) Group(cols ...field.Expr) IPromotionSeckillConfigDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p promotionSeckillConfigDo) Having(conds ...gen.Condition) IPromotionSeckillConfigDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p promotionSeckillConfigDo) Limit(limit int) IPromotionSeckillConfigDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p promotionSeckillConfigDo) Offset(offset int) IPromotionSeckillConfigDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p promotionSeckillConfigDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPromotionSeckillConfigDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p promotionSeckillConfigDo) Unscoped() IPromotionSeckillConfigDo {
	return p.withDO(p.DO.Unscoped())
}

func (p promotionSeckillConfigDo) Create(values ...*promotion.PromotionSeckillConfig) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p promotionSeckillConfigDo) CreateInBatches(values []*promotion.PromotionSeckillConfig, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p promotionSeckillConfigDo) Save(values ...*promotion.PromotionSeckillConfig) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p promotionSeckillConfigDo) First() (*promotion.PromotionSeckillConfig, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionSeckillConfig), nil
	}
}

func (p promotionSeckillConfigDo) Take() (*promotion.PromotionSeckillConfig, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionSeckillConfig), nil
	}
}

func (p promotionSeckillConfigDo) Last() (*promotion.PromotionSeckillConfig, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionSeckillConfig), nil
	}
}

func (p promotionSeckillConfigDo) Find() ([]*promotion.PromotionSeckillConfig, error) {
	result, err := p.DO.Find()
	return result.([]*promotion.PromotionSeckillConfig), err
}

func (p promotionSeckillConfigDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*promotion.PromotionSeckillConfig, err error) {
	buf := make([]*promotion.PromotionSeckillConfig, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p promotionSeckillConfigDo) FindInBatches(result *[]*promotion.PromotionSeckillConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p promotionSeckillConfigDo) Attrs(attrs ...field.AssignExpr) IPromotionSeckillConfigDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p promotionSeckillConfigDo) Assign(attrs ...field.AssignExpr) IPromotionSeckillConfigDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p promotionSeckillConfigDo) Joins(fields ...field.RelationField) IPromotionSeckillConfigDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p promotionSeckillConfigDo) Preload(fields ...field.RelationField) IPromotionSeckillConfigDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p promotionSeckillConfigDo) FirstOrInit() (*promotion.PromotionSeckillConfig, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionSeckillConfig), nil
	}
}

func (p promotionSeckillConfigDo) FirstOrCreate() (*promotion.PromotionSeckillConfig, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*promotion.PromotionSeckillConfig), nil
	}
}

func (p promotionSeckillConfigDo) FindByPage(offset int, limit int) (result []*promotion.PromotionSeckillConfig, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p promotionSeckillConfigDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p promotionSeckillConfigDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p promotionSeckillConfigDo) Delete(models ...*promotion.PromotionSeckillConfig) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *promotionSeckillConfigDo) withDO(do gen.Dao) *promotionSeckillConfigDo {
	p.DO = *do.(*gen.DO)
	return p
}
