// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend-go/internal/model"
)

func newSystemTenant(db *gorm.DB, opts ...gen.DOOption) systemTenant {
	_systemTenant := systemTenant{}

	_systemTenant.systemTenantDo.UseDB(db, opts...)
	_systemTenant.systemTenantDo.UseModel(&model.SystemTenant{})

	tableName := _systemTenant.systemTenantDo.TableName()
	_systemTenant.ALL = field.NewAsterisk(tableName)
	_systemTenant.ID = field.NewInt64(tableName, "id")
	_systemTenant.Name = field.NewString(tableName, "name")
	_systemTenant.ContactName = field.NewString(tableName, "contact_name")
	_systemTenant.ContactMobile = field.NewString(tableName, "contact_mobile")
	_systemTenant.Status = field.NewInt32(tableName, "status")
	_systemTenant.Domain = field.NewString(tableName, "domain")
	_systemTenant.Websites = field.NewString(tableName, "websites")
	_systemTenant.PackageID = field.NewInt64(tableName, "package_id")
	_systemTenant.ExpireDate = field.NewTime(tableName, "expire_time")
	_systemTenant.AccountCount = field.NewInt32(tableName, "account_count")
	_systemTenant.Creator = field.NewString(tableName, "creator")
	_systemTenant.Updater = field.NewString(tableName, "updater")
	_systemTenant.CreatedAt = field.NewTime(tableName, "create_time")
	_systemTenant.UpdatedAt = field.NewTime(tableName, "update_time")
	_systemTenant.Deleted = field.NewField(tableName, "deleted")

	_systemTenant.fillFieldMap()

	return _systemTenant
}

type systemTenant struct {
	systemTenantDo systemTenantDo

	ALL           field.Asterisk
	ID            field.Int64
	Name          field.String
	ContactName   field.String
	ContactMobile field.String
	Status        field.Int32
	Domain        field.String
	Websites      field.String
	PackageID     field.Int64
	ExpireDate    field.Time
	AccountCount  field.Int32
	Creator       field.String
	Updater       field.String
	CreatedAt     field.Time
	UpdatedAt     field.Time
	Deleted       field.Field

	fieldMap map[string]field.Expr
}

func (s systemTenant) Table(newTableName string) *systemTenant {
	s.systemTenantDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s systemTenant) As(alias string) *systemTenant {
	s.systemTenantDo.DO = *(s.systemTenantDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *systemTenant) updateTableName(table string) *systemTenant {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.Name = field.NewString(table, "name")
	s.ContactName = field.NewString(table, "contact_name")
	s.ContactMobile = field.NewString(table, "contact_mobile")
	s.Status = field.NewInt32(table, "status")
	s.Domain = field.NewString(table, "domain")
	s.Websites = field.NewString(table, "websites")
	s.PackageID = field.NewInt64(table, "package_id")
	s.ExpireDate = field.NewTime(table, "expire_time")
	s.AccountCount = field.NewInt32(table, "account_count")
	s.Creator = field.NewString(table, "creator")
	s.Updater = field.NewString(table, "updater")
	s.CreatedAt = field.NewTime(table, "create_time")
	s.UpdatedAt = field.NewTime(table, "update_time")
	s.Deleted = field.NewField(table, "deleted")

	s.fillFieldMap()

	return s
}

func (s *systemTenant) WithContext(ctx context.Context) ISystemTenantDo {
	return s.systemTenantDo.WithContext(ctx)
}

func (s systemTenant) TableName() string { return s.systemTenantDo.TableName() }

func (s systemTenant) Alias() string { return s.systemTenantDo.Alias() }

func (s systemTenant) Columns(cols ...field.Expr) gen.Columns {
	return s.systemTenantDo.Columns(cols...)
}

func (s *systemTenant) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *systemTenant) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 15)
	s.fieldMap["id"] = s.ID
	s.fieldMap["name"] = s.Name
	s.fieldMap["contact_name"] = s.ContactName
	s.fieldMap["contact_mobile"] = s.ContactMobile
	s.fieldMap["status"] = s.Status
	s.fieldMap["domain"] = s.Domain
	s.fieldMap["websites"] = s.Websites
	s.fieldMap["package_id"] = s.PackageID
	s.fieldMap["expire_time"] = s.ExpireDate
	s.fieldMap["account_count"] = s.AccountCount
	s.fieldMap["creator"] = s.Creator
	s.fieldMap["updater"] = s.Updater
	s.fieldMap["create_time"] = s.CreatedAt
	s.fieldMap["update_time"] = s.UpdatedAt
	s.fieldMap["deleted"] = s.Deleted
}

func (s systemTenant) clone(db *gorm.DB) systemTenant {
	s.systemTenantDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s systemTenant) replaceDB(db *gorm.DB) systemTenant {
	s.systemTenantDo.ReplaceDB(db)
	return s
}

type systemTenantDo struct{ gen.DO }

type ISystemTenantDo interface {
	gen.SubQuery
	Debug() ISystemTenantDo
	WithContext(ctx context.Context) ISystemTenantDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISystemTenantDo
	WriteDB() ISystemTenantDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISystemTenantDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISystemTenantDo
	Not(conds ...gen.Condition) ISystemTenantDo
	Or(conds ...gen.Condition) ISystemTenantDo
	Select(conds ...field.Expr) ISystemTenantDo
	Where(conds ...gen.Condition) ISystemTenantDo
	Order(conds ...field.Expr) ISystemTenantDo
	Distinct(cols ...field.Expr) ISystemTenantDo
	Omit(cols ...field.Expr) ISystemTenantDo
	Join(table schema.Tabler, on ...field.Expr) ISystemTenantDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISystemTenantDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISystemTenantDo
	Group(cols ...field.Expr) ISystemTenantDo
	Having(conds ...gen.Condition) ISystemTenantDo
	Limit(limit int) ISystemTenantDo
	Offset(offset int) ISystemTenantDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISystemTenantDo
	Unscoped() ISystemTenantDo
	Create(values ...*model.SystemTenant) error
	CreateInBatches(values []*model.SystemTenant, batchSize int) error
	Save(values ...*model.SystemTenant) error
	First() (*model.SystemTenant, error)
	Take() (*model.SystemTenant, error)
	Last() (*model.SystemTenant, error)
	Find() ([]*model.SystemTenant, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SystemTenant, err error)
	FindInBatches(result *[]*model.SystemTenant, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SystemTenant) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISystemTenantDo
	Assign(attrs ...field.AssignExpr) ISystemTenantDo
	Joins(fields ...field.RelationField) ISystemTenantDo
	Preload(fields ...field.RelationField) ISystemTenantDo
	FirstOrInit() (*model.SystemTenant, error)
	FirstOrCreate() (*model.SystemTenant, error)
	FindByPage(offset int, limit int) (result []*model.SystemTenant, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISystemTenantDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s systemTenantDo) Debug() ISystemTenantDo {
	return s.withDO(s.DO.Debug())
}

func (s systemTenantDo) WithContext(ctx context.Context) ISystemTenantDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s systemTenantDo) ReadDB() ISystemTenantDo {
	return s.Clauses(dbresolver.Read)
}

func (s systemTenantDo) WriteDB() ISystemTenantDo {
	return s.Clauses(dbresolver.Write)
}

func (s systemTenantDo) Session(config *gorm.Session) ISystemTenantDo {
	return s.withDO(s.DO.Session(config))
}

func (s systemTenantDo) Clauses(conds ...clause.Expression) ISystemTenantDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s systemTenantDo) Returning(value interface{}, columns ...string) ISystemTenantDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s systemTenantDo) Not(conds ...gen.Condition) ISystemTenantDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s systemTenantDo) Or(conds ...gen.Condition) ISystemTenantDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s systemTenantDo) Select(conds ...field.Expr) ISystemTenantDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s systemTenantDo) Where(conds ...gen.Condition) ISystemTenantDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s systemTenantDo) Order(conds ...field.Expr) ISystemTenantDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s systemTenantDo) Distinct(cols ...field.Expr) ISystemTenantDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s systemTenantDo) Omit(cols ...field.Expr) ISystemTenantDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s systemTenantDo) Join(table schema.Tabler, on ...field.Expr) ISystemTenantDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s systemTenantDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISystemTenantDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s systemTenantDo) RightJoin(table schema.Tabler, on ...field.Expr) ISystemTenantDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s systemTenantDo) Group(cols ...field.Expr) ISystemTenantDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s systemTenantDo) Having(conds ...gen.Condition) ISystemTenantDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s systemTenantDo) Limit(limit int) ISystemTenantDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s systemTenantDo) Offset(offset int) ISystemTenantDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s systemTenantDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISystemTenantDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s systemTenantDo) Unscoped() ISystemTenantDo {
	return s.withDO(s.DO.Unscoped())
}

func (s systemTenantDo) Create(values ...*model.SystemTenant) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s systemTenantDo) CreateInBatches(values []*model.SystemTenant, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s systemTenantDo) Save(values ...*model.SystemTenant) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s systemTenantDo) First() (*model.SystemTenant, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemTenant), nil
	}
}

func (s systemTenantDo) Take() (*model.SystemTenant, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemTenant), nil
	}
}

func (s systemTenantDo) Last() (*model.SystemTenant, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemTenant), nil
	}
}

func (s systemTenantDo) Find() ([]*model.SystemTenant, error) {
	result, err := s.DO.Find()
	return result.([]*model.SystemTenant), err
}

func (s systemTenantDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SystemTenant, err error) {
	buf := make([]*model.SystemTenant, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s systemTenantDo) FindInBatches(result *[]*model.SystemTenant, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s systemTenantDo) Attrs(attrs ...field.AssignExpr) ISystemTenantDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s systemTenantDo) Assign(attrs ...field.AssignExpr) ISystemTenantDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s systemTenantDo) Joins(fields ...field.RelationField) ISystemTenantDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s systemTenantDo) Preload(fields ...field.RelationField) ISystemTenantDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s systemTenantDo) FirstOrInit() (*model.SystemTenant, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemTenant), nil
	}
}

func (s systemTenantDo) FirstOrCreate() (*model.SystemTenant, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemTenant), nil
	}
}

func (s systemTenantDo) FindByPage(offset int, limit int) (result []*model.SystemTenant, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s systemTenantDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s systemTenantDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s systemTenantDo) Delete(models ...*model.SystemTenant) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *systemTenantDo) withDO(do gen.Dao) *systemTenantDo {
	s.DO = *do.(*gen.DO)
	return s
}
