// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend-go/internal/model"
)

func newSocialUserBind(db *gorm.DB, opts ...gen.DOOption) socialUserBind {
	_socialUserBind := socialUserBind{}

	_socialUserBind.socialUserBindDo.UseDB(db, opts...)
	_socialUserBind.socialUserBindDo.UseModel(&model.SocialUserBind{})

	tableName := _socialUserBind.socialUserBindDo.TableName()
	_socialUserBind.ALL = field.NewAsterisk(tableName)
	_socialUserBind.ID = field.NewInt64(tableName, "id")
	_socialUserBind.Creator = field.NewString(tableName, "creator")
	_socialUserBind.Updater = field.NewString(tableName, "updater")
	_socialUserBind.CreatedAt = field.NewTime(tableName, "create_time")
	_socialUserBind.UpdatedAt = field.NewTime(tableName, "update_time")
	_socialUserBind.Deleted = field.NewField(tableName, "deleted")
	_socialUserBind.UserID = field.NewInt64(tableName, "user_id")
	_socialUserBind.UserType = field.NewInt(tableName, "user_type")
	_socialUserBind.SocialType = field.NewInt(tableName, "social_type")
	_socialUserBind.SocialUserID = field.NewInt64(tableName, "social_user_id")

	_socialUserBind.fillFieldMap()

	return _socialUserBind
}

type socialUserBind struct {
	socialUserBindDo socialUserBindDo

	ALL          field.Asterisk
	ID           field.Int64  // 编号
	Creator      field.String // 创建者
	Updater      field.String // 更新者
	CreatedAt    field.Time   // 创建时间
	UpdatedAt    field.Time   // 更新时间
	Deleted      field.Field  // 是否删除
	UserID       field.Int64  // 用户编号
	UserType     field.Int    // 用户类型
	SocialType   field.Int    // 社交类型
	SocialUserID field.Int64  // 社交用户编号

	fieldMap map[string]field.Expr
}

func (s socialUserBind) Table(newTableName string) *socialUserBind {
	s.socialUserBindDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s socialUserBind) As(alias string) *socialUserBind {
	s.socialUserBindDo.DO = *(s.socialUserBindDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *socialUserBind) updateTableName(table string) *socialUserBind {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.Creator = field.NewString(table, "creator")
	s.Updater = field.NewString(table, "updater")
	s.CreatedAt = field.NewTime(table, "create_time")
	s.UpdatedAt = field.NewTime(table, "update_time")
	s.Deleted = field.NewField(table, "deleted")
	s.UserID = field.NewInt64(table, "user_id")
	s.UserType = field.NewInt(table, "user_type")
	s.SocialType = field.NewInt(table, "social_type")
	s.SocialUserID = field.NewInt64(table, "social_user_id")

	s.fillFieldMap()

	return s
}

func (s *socialUserBind) WithContext(ctx context.Context) ISocialUserBindDo {
	return s.socialUserBindDo.WithContext(ctx)
}

func (s socialUserBind) TableName() string { return s.socialUserBindDo.TableName() }

func (s socialUserBind) Alias() string { return s.socialUserBindDo.Alias() }

func (s socialUserBind) Columns(cols ...field.Expr) gen.Columns {
	return s.socialUserBindDo.Columns(cols...)
}

func (s *socialUserBind) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *socialUserBind) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 10)
	s.fieldMap["id"] = s.ID
	s.fieldMap["creator"] = s.Creator
	s.fieldMap["updater"] = s.Updater
	s.fieldMap["create_time"] = s.CreatedAt
	s.fieldMap["update_time"] = s.UpdatedAt
	s.fieldMap["deleted"] = s.Deleted
	s.fieldMap["user_id"] = s.UserID
	s.fieldMap["user_type"] = s.UserType
	s.fieldMap["social_type"] = s.SocialType
	s.fieldMap["social_user_id"] = s.SocialUserID
}

func (s socialUserBind) clone(db *gorm.DB) socialUserBind {
	s.socialUserBindDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s socialUserBind) replaceDB(db *gorm.DB) socialUserBind {
	s.socialUserBindDo.ReplaceDB(db)
	return s
}

type socialUserBindDo struct{ gen.DO }

type ISocialUserBindDo interface {
	gen.SubQuery
	Debug() ISocialUserBindDo
	WithContext(ctx context.Context) ISocialUserBindDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISocialUserBindDo
	WriteDB() ISocialUserBindDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISocialUserBindDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISocialUserBindDo
	Not(conds ...gen.Condition) ISocialUserBindDo
	Or(conds ...gen.Condition) ISocialUserBindDo
	Select(conds ...field.Expr) ISocialUserBindDo
	Where(conds ...gen.Condition) ISocialUserBindDo
	Order(conds ...field.Expr) ISocialUserBindDo
	Distinct(cols ...field.Expr) ISocialUserBindDo
	Omit(cols ...field.Expr) ISocialUserBindDo
	Join(table schema.Tabler, on ...field.Expr) ISocialUserBindDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISocialUserBindDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISocialUserBindDo
	Group(cols ...field.Expr) ISocialUserBindDo
	Having(conds ...gen.Condition) ISocialUserBindDo
	Limit(limit int) ISocialUserBindDo
	Offset(offset int) ISocialUserBindDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISocialUserBindDo
	Unscoped() ISocialUserBindDo
	Create(values ...*model.SocialUserBind) error
	CreateInBatches(values []*model.SocialUserBind, batchSize int) error
	Save(values ...*model.SocialUserBind) error
	First() (*model.SocialUserBind, error)
	Take() (*model.SocialUserBind, error)
	Last() (*model.SocialUserBind, error)
	Find() ([]*model.SocialUserBind, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SocialUserBind, err error)
	FindInBatches(result *[]*model.SocialUserBind, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SocialUserBind) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISocialUserBindDo
	Assign(attrs ...field.AssignExpr) ISocialUserBindDo
	Joins(fields ...field.RelationField) ISocialUserBindDo
	Preload(fields ...field.RelationField) ISocialUserBindDo
	FirstOrInit() (*model.SocialUserBind, error)
	FirstOrCreate() (*model.SocialUserBind, error)
	FindByPage(offset int, limit int) (result []*model.SocialUserBind, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISocialUserBindDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s socialUserBindDo) Debug() ISocialUserBindDo {
	return s.withDO(s.DO.Debug())
}

func (s socialUserBindDo) WithContext(ctx context.Context) ISocialUserBindDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s socialUserBindDo) ReadDB() ISocialUserBindDo {
	return s.Clauses(dbresolver.Read)
}

func (s socialUserBindDo) WriteDB() ISocialUserBindDo {
	return s.Clauses(dbresolver.Write)
}

func (s socialUserBindDo) Session(config *gorm.Session) ISocialUserBindDo {
	return s.withDO(s.DO.Session(config))
}

func (s socialUserBindDo) Clauses(conds ...clause.Expression) ISocialUserBindDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s socialUserBindDo) Returning(value interface{}, columns ...string) ISocialUserBindDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s socialUserBindDo) Not(conds ...gen.Condition) ISocialUserBindDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s socialUserBindDo) Or(conds ...gen.Condition) ISocialUserBindDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s socialUserBindDo) Select(conds ...field.Expr) ISocialUserBindDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s socialUserBindDo) Where(conds ...gen.Condition) ISocialUserBindDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s socialUserBindDo) Order(conds ...field.Expr) ISocialUserBindDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s socialUserBindDo) Distinct(cols ...field.Expr) ISocialUserBindDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s socialUserBindDo) Omit(cols ...field.Expr) ISocialUserBindDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s socialUserBindDo) Join(table schema.Tabler, on ...field.Expr) ISocialUserBindDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s socialUserBindDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISocialUserBindDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s socialUserBindDo) RightJoin(table schema.Tabler, on ...field.Expr) ISocialUserBindDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s socialUserBindDo) Group(cols ...field.Expr) ISocialUserBindDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s socialUserBindDo) Having(conds ...gen.Condition) ISocialUserBindDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s socialUserBindDo) Limit(limit int) ISocialUserBindDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s socialUserBindDo) Offset(offset int) ISocialUserBindDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s socialUserBindDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISocialUserBindDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s socialUserBindDo) Unscoped() ISocialUserBindDo {
	return s.withDO(s.DO.Unscoped())
}

func (s socialUserBindDo) Create(values ...*model.SocialUserBind) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s socialUserBindDo) CreateInBatches(values []*model.SocialUserBind, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s socialUserBindDo) Save(values ...*model.SocialUserBind) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s socialUserBindDo) First() (*model.SocialUserBind, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SocialUserBind), nil
	}
}

func (s socialUserBindDo) Take() (*model.SocialUserBind, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SocialUserBind), nil
	}
}

func (s socialUserBindDo) Last() (*model.SocialUserBind, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SocialUserBind), nil
	}
}

func (s socialUserBindDo) Find() ([]*model.SocialUserBind, error) {
	result, err := s.DO.Find()
	return result.([]*model.SocialUserBind), err
}

func (s socialUserBindDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SocialUserBind, err error) {
	buf := make([]*model.SocialUserBind, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s socialUserBindDo) FindInBatches(result *[]*model.SocialUserBind, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s socialUserBindDo) Attrs(attrs ...field.AssignExpr) ISocialUserBindDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s socialUserBindDo) Assign(attrs ...field.AssignExpr) ISocialUserBindDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s socialUserBindDo) Joins(fields ...field.RelationField) ISocialUserBindDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s socialUserBindDo) Preload(fields ...field.RelationField) ISocialUserBindDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s socialUserBindDo) FirstOrInit() (*model.SocialUserBind, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SocialUserBind), nil
	}
}

func (s socialUserBindDo) FirstOrCreate() (*model.SocialUserBind, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SocialUserBind), nil
	}
}

func (s socialUserBindDo) FindByPage(offset int, limit int) (result []*model.SocialUserBind, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s socialUserBindDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s socialUserBindDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s socialUserBindDo) Delete(models ...*model.SocialUserBind) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *socialUserBindDo) withDO(do gen.Dao) *socialUserBindDo {
	s.DO = *do.(*gen.DO)
	return s
}
