// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend-go/internal/model/trade"
)

func newTradeConfig(db *gorm.DB, opts ...gen.DOOption) tradeConfig {
	_tradeConfig := tradeConfig{}

	_tradeConfig.tradeConfigDo.UseDB(db, opts...)
	_tradeConfig.tradeConfigDo.UseModel(&trade.TradeConfig{})

	tableName := _tradeConfig.tradeConfigDo.TableName()
	_tradeConfig.ALL = field.NewAsterisk(tableName)
	_tradeConfig.ID = field.NewInt64(tableName, "id")
	_tradeConfig.AppID = field.NewInt64(tableName, "app_id")
	_tradeConfig.AfterSaleDeadlineDays = field.NewInt(tableName, "after_sale_deadline_days")
	_tradeConfig.PayTimeoutMinutes = field.NewInt(tableName, "pay_timeout_minutes")
	_tradeConfig.AutoReceiveDays = field.NewInt(tableName, "auto_receive_days")
	_tradeConfig.AutoCommentDays = field.NewInt(tableName, "auto_comment_days")
	_tradeConfig.BrokerageWithdrawMinPrice = field.NewInt(tableName, "brokerage_withdraw_min_price")
	_tradeConfig.BrokerageWithdrawFeePercent = field.NewInt(tableName, "brokerage_withdraw_fee_percent")
	_tradeConfig.BrokerageEnabled = field.NewField(tableName, "brokerage_enabled")
	_tradeConfig.BrokerageFrozenDays = field.NewInt(tableName, "brokerage_frozen_days")
	_tradeConfig.BrokerageFirstPercent = field.NewInt(tableName, "brokerage_first_percent")
	_tradeConfig.BrokerageSecondPercent = field.NewInt(tableName, "brokerage_second_percent")
	_tradeConfig.BrokeragePosterUrls = field.NewString(tableName, "brokerage_poster_urls")
	_tradeConfig.Creator = field.NewString(tableName, "creator")
	_tradeConfig.CreateTime = field.NewTime(tableName, "create_time")
	_tradeConfig.Updater = field.NewString(tableName, "updater")
	_tradeConfig.UpdateTime = field.NewTime(tableName, "update_time")
	_tradeConfig.Deleted = field.NewField(tableName, "deleted")
	_tradeConfig.TenantID = field.NewInt64(tableName, "tenant_id")

	_tradeConfig.fillFieldMap()

	return _tradeConfig
}

type tradeConfig struct {
	tradeConfigDo tradeConfigDo

	ALL                         field.Asterisk
	ID                          field.Int64  // 主键
	AppID                       field.Int64  // 支付应用ID
	AfterSaleDeadlineDays       field.Int    // 售后期限(天)
	PayTimeoutMinutes           field.Int    // 支付超时(分钟)
	AutoReceiveDays             field.Int    // 自动收货(天)
	AutoCommentDays             field.Int    // 自动好评(天)
	BrokerageWithdrawMinPrice   field.Int    // 提现最低金额
	BrokerageWithdrawFeePercent field.Int    // 提现手续费百分比
	BrokerageEnabled            field.Field  // 是否开启分销
	BrokerageFrozenDays         field.Int    // 分销佣金冻结时间
	BrokerageFirstPercent       field.Int    // 一级分销比例
	BrokerageSecondPercent      field.Int    // 二级分销比例
	BrokeragePosterUrls         field.String // 分销海报图
	Creator                     field.String // 创建者
	CreateTime                  field.Time   // 创建时间
	Updater                     field.String // 更新者
	UpdateTime                  field.Time   // 更新时间
	Deleted                     field.Field  // 是否删除
	TenantID                    field.Int64  // 租户编号

	fieldMap map[string]field.Expr
}

func (t tradeConfig) Table(newTableName string) *tradeConfig {
	t.tradeConfigDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tradeConfig) As(alias string) *tradeConfig {
	t.tradeConfigDo.DO = *(t.tradeConfigDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tradeConfig) updateTableName(table string) *tradeConfig {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.AppID = field.NewInt64(table, "app_id")
	t.AfterSaleDeadlineDays = field.NewInt(table, "after_sale_deadline_days")
	t.PayTimeoutMinutes = field.NewInt(table, "pay_timeout_minutes")
	t.AutoReceiveDays = field.NewInt(table, "auto_receive_days")
	t.AutoCommentDays = field.NewInt(table, "auto_comment_days")
	t.BrokerageWithdrawMinPrice = field.NewInt(table, "brokerage_withdraw_min_price")
	t.BrokerageWithdrawFeePercent = field.NewInt(table, "brokerage_withdraw_fee_percent")
	t.BrokerageEnabled = field.NewField(table, "brokerage_enabled")
	t.BrokerageFrozenDays = field.NewInt(table, "brokerage_frozen_days")
	t.BrokerageFirstPercent = field.NewInt(table, "brokerage_first_percent")
	t.BrokerageSecondPercent = field.NewInt(table, "brokerage_second_percent")
	t.BrokeragePosterUrls = field.NewString(table, "brokerage_poster_urls")
	t.Creator = field.NewString(table, "creator")
	t.CreateTime = field.NewTime(table, "create_time")
	t.Updater = field.NewString(table, "updater")
	t.UpdateTime = field.NewTime(table, "update_time")
	t.Deleted = field.NewField(table, "deleted")
	t.TenantID = field.NewInt64(table, "tenant_id")

	t.fillFieldMap()

	return t
}

func (t *tradeConfig) WithContext(ctx context.Context) ITradeConfigDo {
	return t.tradeConfigDo.WithContext(ctx)
}

func (t tradeConfig) TableName() string { return t.tradeConfigDo.TableName() }

func (t tradeConfig) Alias() string { return t.tradeConfigDo.Alias() }

func (t tradeConfig) Columns(cols ...field.Expr) gen.Columns { return t.tradeConfigDo.Columns(cols...) }

func (t *tradeConfig) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tradeConfig) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 19)
	t.fieldMap["id"] = t.ID
	t.fieldMap["app_id"] = t.AppID
	t.fieldMap["after_sale_deadline_days"] = t.AfterSaleDeadlineDays
	t.fieldMap["pay_timeout_minutes"] = t.PayTimeoutMinutes
	t.fieldMap["auto_receive_days"] = t.AutoReceiveDays
	t.fieldMap["auto_comment_days"] = t.AutoCommentDays
	t.fieldMap["brokerage_withdraw_min_price"] = t.BrokerageWithdrawMinPrice
	t.fieldMap["brokerage_withdraw_fee_percent"] = t.BrokerageWithdrawFeePercent
	t.fieldMap["brokerage_enabled"] = t.BrokerageEnabled
	t.fieldMap["brokerage_frozen_days"] = t.BrokerageFrozenDays
	t.fieldMap["brokerage_first_percent"] = t.BrokerageFirstPercent
	t.fieldMap["brokerage_second_percent"] = t.BrokerageSecondPercent
	t.fieldMap["brokerage_poster_urls"] = t.BrokeragePosterUrls
	t.fieldMap["creator"] = t.Creator
	t.fieldMap["create_time"] = t.CreateTime
	t.fieldMap["updater"] = t.Updater
	t.fieldMap["update_time"] = t.UpdateTime
	t.fieldMap["deleted"] = t.Deleted
	t.fieldMap["tenant_id"] = t.TenantID
}

func (t tradeConfig) clone(db *gorm.DB) tradeConfig {
	t.tradeConfigDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tradeConfig) replaceDB(db *gorm.DB) tradeConfig {
	t.tradeConfigDo.ReplaceDB(db)
	return t
}

type tradeConfigDo struct{ gen.DO }

type ITradeConfigDo interface {
	gen.SubQuery
	Debug() ITradeConfigDo
	WithContext(ctx context.Context) ITradeConfigDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITradeConfigDo
	WriteDB() ITradeConfigDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITradeConfigDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITradeConfigDo
	Not(conds ...gen.Condition) ITradeConfigDo
	Or(conds ...gen.Condition) ITradeConfigDo
	Select(conds ...field.Expr) ITradeConfigDo
	Where(conds ...gen.Condition) ITradeConfigDo
	Order(conds ...field.Expr) ITradeConfigDo
	Distinct(cols ...field.Expr) ITradeConfigDo
	Omit(cols ...field.Expr) ITradeConfigDo
	Join(table schema.Tabler, on ...field.Expr) ITradeConfigDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITradeConfigDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITradeConfigDo
	Group(cols ...field.Expr) ITradeConfigDo
	Having(conds ...gen.Condition) ITradeConfigDo
	Limit(limit int) ITradeConfigDo
	Offset(offset int) ITradeConfigDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITradeConfigDo
	Unscoped() ITradeConfigDo
	Create(values ...*trade.TradeConfig) error
	CreateInBatches(values []*trade.TradeConfig, batchSize int) error
	Save(values ...*trade.TradeConfig) error
	First() (*trade.TradeConfig, error)
	Take() (*trade.TradeConfig, error)
	Last() (*trade.TradeConfig, error)
	Find() ([]*trade.TradeConfig, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*trade.TradeConfig, err error)
	FindInBatches(result *[]*trade.TradeConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*trade.TradeConfig) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITradeConfigDo
	Assign(attrs ...field.AssignExpr) ITradeConfigDo
	Joins(fields ...field.RelationField) ITradeConfigDo
	Preload(fields ...field.RelationField) ITradeConfigDo
	FirstOrInit() (*trade.TradeConfig, error)
	FirstOrCreate() (*trade.TradeConfig, error)
	FindByPage(offset int, limit int) (result []*trade.TradeConfig, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITradeConfigDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tradeConfigDo) Debug() ITradeConfigDo {
	return t.withDO(t.DO.Debug())
}

func (t tradeConfigDo) WithContext(ctx context.Context) ITradeConfigDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tradeConfigDo) ReadDB() ITradeConfigDo {
	return t.Clauses(dbresolver.Read)
}

func (t tradeConfigDo) WriteDB() ITradeConfigDo {
	return t.Clauses(dbresolver.Write)
}

func (t tradeConfigDo) Session(config *gorm.Session) ITradeConfigDo {
	return t.withDO(t.DO.Session(config))
}

func (t tradeConfigDo) Clauses(conds ...clause.Expression) ITradeConfigDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tradeConfigDo) Returning(value interface{}, columns ...string) ITradeConfigDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tradeConfigDo) Not(conds ...gen.Condition) ITradeConfigDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tradeConfigDo) Or(conds ...gen.Condition) ITradeConfigDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tradeConfigDo) Select(conds ...field.Expr) ITradeConfigDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tradeConfigDo) Where(conds ...gen.Condition) ITradeConfigDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tradeConfigDo) Order(conds ...field.Expr) ITradeConfigDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tradeConfigDo) Distinct(cols ...field.Expr) ITradeConfigDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tradeConfigDo) Omit(cols ...field.Expr) ITradeConfigDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tradeConfigDo) Join(table schema.Tabler, on ...field.Expr) ITradeConfigDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tradeConfigDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITradeConfigDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tradeConfigDo) RightJoin(table schema.Tabler, on ...field.Expr) ITradeConfigDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tradeConfigDo) Group(cols ...field.Expr) ITradeConfigDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tradeConfigDo) Having(conds ...gen.Condition) ITradeConfigDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tradeConfigDo) Limit(limit int) ITradeConfigDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tradeConfigDo) Offset(offset int) ITradeConfigDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tradeConfigDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITradeConfigDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tradeConfigDo) Unscoped() ITradeConfigDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tradeConfigDo) Create(values ...*trade.TradeConfig) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tradeConfigDo) CreateInBatches(values []*trade.TradeConfig, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tradeConfigDo) Save(values ...*trade.TradeConfig) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tradeConfigDo) First() (*trade.TradeConfig, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*trade.TradeConfig), nil
	}
}

func (t tradeConfigDo) Take() (*trade.TradeConfig, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*trade.TradeConfig), nil
	}
}

func (t tradeConfigDo) Last() (*trade.TradeConfig, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*trade.TradeConfig), nil
	}
}

func (t tradeConfigDo) Find() ([]*trade.TradeConfig, error) {
	result, err := t.DO.Find()
	return result.([]*trade.TradeConfig), err
}

func (t tradeConfigDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*trade.TradeConfig, err error) {
	buf := make([]*trade.TradeConfig, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tradeConfigDo) FindInBatches(result *[]*trade.TradeConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tradeConfigDo) Attrs(attrs ...field.AssignExpr) ITradeConfigDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tradeConfigDo) Assign(attrs ...field.AssignExpr) ITradeConfigDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tradeConfigDo) Joins(fields ...field.RelationField) ITradeConfigDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tradeConfigDo) Preload(fields ...field.RelationField) ITradeConfigDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tradeConfigDo) FirstOrInit() (*trade.TradeConfig, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*trade.TradeConfig), nil
	}
}

func (t tradeConfigDo) FirstOrCreate() (*trade.TradeConfig, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*trade.TradeConfig), nil
	}
}

func (t tradeConfigDo) FindByPage(offset int, limit int) (result []*trade.TradeConfig, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tradeConfigDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tradeConfigDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tradeConfigDo) Delete(models ...*trade.TradeConfig) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tradeConfigDo) withDO(do gen.Dao) *tradeConfigDo {
	t.DO = *do.(*gen.DO)
	return t
}
