// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend-go/internal/model/trade/brokerage"
)

func newBrokerageRecord(db *gorm.DB, opts ...gen.DOOption) brokerageRecord {
	_brokerageRecord := brokerageRecord{}

	_brokerageRecord.brokerageRecordDo.UseDB(db, opts...)
	_brokerageRecord.brokerageRecordDo.UseModel(&brokerage.BrokerageRecord{})

	tableName := _brokerageRecord.brokerageRecordDo.TableName()
	_brokerageRecord.ALL = field.NewAsterisk(tableName)
	_brokerageRecord.ID = field.NewInt64(tableName, "id")
	_brokerageRecord.UserID = field.NewInt64(tableName, "user_id")
	_brokerageRecord.BizID = field.NewString(tableName, "biz_id")
	_brokerageRecord.BizType = field.NewInt(tableName, "biz_type")
	_brokerageRecord.Title = field.NewString(tableName, "title")
	_brokerageRecord.Description = field.NewString(tableName, "description")
	_brokerageRecord.Price = field.NewInt(tableName, "price")
	_brokerageRecord.TotalPrice = field.NewInt(tableName, "total_price")
	_brokerageRecord.Status = field.NewInt(tableName, "status")
	_brokerageRecord.FrozenDays = field.NewInt(tableName, "frozen_days")
	_brokerageRecord.UnfreezeTime = field.NewTime(tableName, "unfreeze_time")
	_brokerageRecord.SourceUserLevel = field.NewInt(tableName, "source_user_level")
	_brokerageRecord.SourceUserID = field.NewInt64(tableName, "source_user_id")
	_brokerageRecord.Creator = field.NewString(tableName, "creator")
	_brokerageRecord.Updater = field.NewString(tableName, "updater")
	_brokerageRecord.CreatedAt = field.NewTime(tableName, "create_time")
	_brokerageRecord.UpdatedAt = field.NewTime(tableName, "update_time")
	_brokerageRecord.DeletedAt = field.NewField(tableName, "deleted")
	_brokerageRecord.Deleted = field.NewBool(tableName, "deleted")

	_brokerageRecord.fillFieldMap()

	return _brokerageRecord
}

type brokerageRecord struct {
	brokerageRecordDo brokerageRecordDo

	ALL             field.Asterisk
	ID              field.Int64  // 编号
	UserID          field.Int64  // 用户编号
	BizID           field.String // 业务编号
	BizType         field.Int    // 业务类型
	Title           field.String // 标题
	Description     field.String // 说明
	Price           field.Int    // 金额
	TotalPrice      field.Int    // 当前总佣金
	Status          field.Int    // 状态
	FrozenDays      field.Int    // 冻结时间（天）
	UnfreezeTime    field.Time   // 解冻时间
	SourceUserLevel field.Int    // 来源用户等级
	SourceUserID    field.Int64  // 来源用户编号
	Creator         field.String // 创建者
	Updater         field.String // 更新者
	CreatedAt       field.Time   // 创建时间
	UpdatedAt       field.Time   // 更新时间
	DeletedAt       field.Field  // 删除时间
	Deleted         field.Bool   // 是否删除

	fieldMap map[string]field.Expr
}

func (b brokerageRecord) Table(newTableName string) *brokerageRecord {
	b.brokerageRecordDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b brokerageRecord) As(alias string) *brokerageRecord {
	b.brokerageRecordDo.DO = *(b.brokerageRecordDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *brokerageRecord) updateTableName(table string) *brokerageRecord {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewInt64(table, "id")
	b.UserID = field.NewInt64(table, "user_id")
	b.BizID = field.NewString(table, "biz_id")
	b.BizType = field.NewInt(table, "biz_type")
	b.Title = field.NewString(table, "title")
	b.Description = field.NewString(table, "description")
	b.Price = field.NewInt(table, "price")
	b.TotalPrice = field.NewInt(table, "total_price")
	b.Status = field.NewInt(table, "status")
	b.FrozenDays = field.NewInt(table, "frozen_days")
	b.UnfreezeTime = field.NewTime(table, "unfreeze_time")
	b.SourceUserLevel = field.NewInt(table, "source_user_level")
	b.SourceUserID = field.NewInt64(table, "source_user_id")
	b.Creator = field.NewString(table, "creator")
	b.Updater = field.NewString(table, "updater")
	b.CreatedAt = field.NewTime(table, "create_time")
	b.UpdatedAt = field.NewTime(table, "update_time")
	b.DeletedAt = field.NewField(table, "deleted")
	b.Deleted = field.NewBool(table, "deleted")

	b.fillFieldMap()

	return b
}

func (b *brokerageRecord) WithContext(ctx context.Context) IBrokerageRecordDo {
	return b.brokerageRecordDo.WithContext(ctx)
}

func (b brokerageRecord) TableName() string { return b.brokerageRecordDo.TableName() }

func (b brokerageRecord) Alias() string { return b.brokerageRecordDo.Alias() }

func (b brokerageRecord) Columns(cols ...field.Expr) gen.Columns {
	return b.brokerageRecordDo.Columns(cols...)
}

func (b *brokerageRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *brokerageRecord) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 19)
	b.fieldMap["id"] = b.ID
	b.fieldMap["user_id"] = b.UserID
	b.fieldMap["biz_id"] = b.BizID
	b.fieldMap["biz_type"] = b.BizType
	b.fieldMap["title"] = b.Title
	b.fieldMap["description"] = b.Description
	b.fieldMap["price"] = b.Price
	b.fieldMap["total_price"] = b.TotalPrice
	b.fieldMap["status"] = b.Status
	b.fieldMap["frozen_days"] = b.FrozenDays
	b.fieldMap["unfreeze_time"] = b.UnfreezeTime
	b.fieldMap["source_user_level"] = b.SourceUserLevel
	b.fieldMap["source_user_id"] = b.SourceUserID
	b.fieldMap["creator"] = b.Creator
	b.fieldMap["updater"] = b.Updater
	b.fieldMap["create_time"] = b.CreatedAt
	b.fieldMap["update_time"] = b.UpdatedAt
	b.fieldMap["deleted"] = b.DeletedAt
	b.fieldMap["deleted"] = b.Deleted
}

func (b brokerageRecord) clone(db *gorm.DB) brokerageRecord {
	b.brokerageRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b brokerageRecord) replaceDB(db *gorm.DB) brokerageRecord {
	b.brokerageRecordDo.ReplaceDB(db)
	return b
}

type brokerageRecordDo struct{ gen.DO }

type IBrokerageRecordDo interface {
	gen.SubQuery
	Debug() IBrokerageRecordDo
	WithContext(ctx context.Context) IBrokerageRecordDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IBrokerageRecordDo
	WriteDB() IBrokerageRecordDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IBrokerageRecordDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IBrokerageRecordDo
	Not(conds ...gen.Condition) IBrokerageRecordDo
	Or(conds ...gen.Condition) IBrokerageRecordDo
	Select(conds ...field.Expr) IBrokerageRecordDo
	Where(conds ...gen.Condition) IBrokerageRecordDo
	Order(conds ...field.Expr) IBrokerageRecordDo
	Distinct(cols ...field.Expr) IBrokerageRecordDo
	Omit(cols ...field.Expr) IBrokerageRecordDo
	Join(table schema.Tabler, on ...field.Expr) IBrokerageRecordDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IBrokerageRecordDo
	RightJoin(table schema.Tabler, on ...field.Expr) IBrokerageRecordDo
	Group(cols ...field.Expr) IBrokerageRecordDo
	Having(conds ...gen.Condition) IBrokerageRecordDo
	Limit(limit int) IBrokerageRecordDo
	Offset(offset int) IBrokerageRecordDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IBrokerageRecordDo
	Unscoped() IBrokerageRecordDo
	Create(values ...*brokerage.BrokerageRecord) error
	CreateInBatches(values []*brokerage.BrokerageRecord, batchSize int) error
	Save(values ...*brokerage.BrokerageRecord) error
	First() (*brokerage.BrokerageRecord, error)
	Take() (*brokerage.BrokerageRecord, error)
	Last() (*brokerage.BrokerageRecord, error)
	Find() ([]*brokerage.BrokerageRecord, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*brokerage.BrokerageRecord, err error)
	FindInBatches(result *[]*brokerage.BrokerageRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*brokerage.BrokerageRecord) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IBrokerageRecordDo
	Assign(attrs ...field.AssignExpr) IBrokerageRecordDo
	Joins(fields ...field.RelationField) IBrokerageRecordDo
	Preload(fields ...field.RelationField) IBrokerageRecordDo
	FirstOrInit() (*brokerage.BrokerageRecord, error)
	FirstOrCreate() (*brokerage.BrokerageRecord, error)
	FindByPage(offset int, limit int) (result []*brokerage.BrokerageRecord, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IBrokerageRecordDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (b brokerageRecordDo) Debug() IBrokerageRecordDo {
	return b.withDO(b.DO.Debug())
}

func (b brokerageRecordDo) WithContext(ctx context.Context) IBrokerageRecordDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b brokerageRecordDo) ReadDB() IBrokerageRecordDo {
	return b.Clauses(dbresolver.Read)
}

func (b brokerageRecordDo) WriteDB() IBrokerageRecordDo {
	return b.Clauses(dbresolver.Write)
}

func (b brokerageRecordDo) Session(config *gorm.Session) IBrokerageRecordDo {
	return b.withDO(b.DO.Session(config))
}

func (b brokerageRecordDo) Clauses(conds ...clause.Expression) IBrokerageRecordDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b brokerageRecordDo) Returning(value interface{}, columns ...string) IBrokerageRecordDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b brokerageRecordDo) Not(conds ...gen.Condition) IBrokerageRecordDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b brokerageRecordDo) Or(conds ...gen.Condition) IBrokerageRecordDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b brokerageRecordDo) Select(conds ...field.Expr) IBrokerageRecordDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b brokerageRecordDo) Where(conds ...gen.Condition) IBrokerageRecordDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b brokerageRecordDo) Order(conds ...field.Expr) IBrokerageRecordDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b brokerageRecordDo) Distinct(cols ...field.Expr) IBrokerageRecordDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b brokerageRecordDo) Omit(cols ...field.Expr) IBrokerageRecordDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b brokerageRecordDo) Join(table schema.Tabler, on ...field.Expr) IBrokerageRecordDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b brokerageRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) IBrokerageRecordDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b brokerageRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) IBrokerageRecordDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b brokerageRecordDo) Group(cols ...field.Expr) IBrokerageRecordDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b brokerageRecordDo) Having(conds ...gen.Condition) IBrokerageRecordDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b brokerageRecordDo) Limit(limit int) IBrokerageRecordDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b brokerageRecordDo) Offset(offset int) IBrokerageRecordDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b brokerageRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IBrokerageRecordDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b brokerageRecordDo) Unscoped() IBrokerageRecordDo {
	return b.withDO(b.DO.Unscoped())
}

func (b brokerageRecordDo) Create(values ...*brokerage.BrokerageRecord) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b brokerageRecordDo) CreateInBatches(values []*brokerage.BrokerageRecord, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b brokerageRecordDo) Save(values ...*brokerage.BrokerageRecord) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b brokerageRecordDo) First() (*brokerage.BrokerageRecord, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*brokerage.BrokerageRecord), nil
	}
}

func (b brokerageRecordDo) Take() (*brokerage.BrokerageRecord, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*brokerage.BrokerageRecord), nil
	}
}

func (b brokerageRecordDo) Last() (*brokerage.BrokerageRecord, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*brokerage.BrokerageRecord), nil
	}
}

func (b brokerageRecordDo) Find() ([]*brokerage.BrokerageRecord, error) {
	result, err := b.DO.Find()
	return result.([]*brokerage.BrokerageRecord), err
}

func (b brokerageRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*brokerage.BrokerageRecord, err error) {
	buf := make([]*brokerage.BrokerageRecord, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b brokerageRecordDo) FindInBatches(result *[]*brokerage.BrokerageRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b brokerageRecordDo) Attrs(attrs ...field.AssignExpr) IBrokerageRecordDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b brokerageRecordDo) Assign(attrs ...field.AssignExpr) IBrokerageRecordDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b brokerageRecordDo) Joins(fields ...field.RelationField) IBrokerageRecordDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b brokerageRecordDo) Preload(fields ...field.RelationField) IBrokerageRecordDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b brokerageRecordDo) FirstOrInit() (*brokerage.BrokerageRecord, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*brokerage.BrokerageRecord), nil
	}
}

func (b brokerageRecordDo) FirstOrCreate() (*brokerage.BrokerageRecord, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*brokerage.BrokerageRecord), nil
	}
}

func (b brokerageRecordDo) FindByPage(offset int, limit int) (result []*brokerage.BrokerageRecord, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b brokerageRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b brokerageRecordDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b brokerageRecordDo) Delete(models ...*brokerage.BrokerageRecord) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *brokerageRecordDo) withDO(do gen.Dao) *brokerageRecordDo {
	b.DO = *do.(*gen.DO)
	return b
}
