// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend-go/internal/model/trade"
)

func newTradeOrderLog(db *gorm.DB, opts ...gen.DOOption) tradeOrderLog {
	_tradeOrderLog := tradeOrderLog{}

	_tradeOrderLog.tradeOrderLogDo.UseDB(db, opts...)
	_tradeOrderLog.tradeOrderLogDo.UseModel(&trade.TradeOrderLog{})

	tableName := _tradeOrderLog.tradeOrderLogDo.TableName()
	_tradeOrderLog.ALL = field.NewAsterisk(tableName)
	_tradeOrderLog.ID = field.NewInt64(tableName, "id")
	_tradeOrderLog.UserID = field.NewInt64(tableName, "user_id")
	_tradeOrderLog.UserType = field.NewInt(tableName, "user_type")
	_tradeOrderLog.OrderID = field.NewInt64(tableName, "order_id")
	_tradeOrderLog.BeforeStatus = field.NewInt(tableName, "before_status")
	_tradeOrderLog.AfterStatus = field.NewInt(tableName, "after_status")
	_tradeOrderLog.OperateType = field.NewInt(tableName, "operate_type")
	_tradeOrderLog.Content = field.NewString(tableName, "content")
	_tradeOrderLog.Creator = field.NewString(tableName, "creator")
	_tradeOrderLog.Updater = field.NewString(tableName, "updater")
	_tradeOrderLog.CreatedAt = field.NewTime(tableName, "create_time")
	_tradeOrderLog.UpdatedAt = field.NewTime(tableName, "update_time")
	_tradeOrderLog.DeletedAt = field.NewField(tableName, "deleted")
	_tradeOrderLog.Deleted = field.NewBool(tableName, "deleted")

	_tradeOrderLog.fillFieldMap()

	return _tradeOrderLog
}

type tradeOrderLog struct {
	tradeOrderLogDo tradeOrderLogDo

	ALL          field.Asterisk
	ID           field.Int64  // 日志编号
	UserID       field.Int64  // 用户编号
	UserType     field.Int    // 用户类型
	OrderID      field.Int64  // 订单号
	BeforeStatus field.Int    // 操作前状态
	AfterStatus  field.Int    // 操作后状态
	OperateType  field.Int    // 操作类型
	Content      field.String // 订单日志信息
	Creator      field.String // 创建者
	Updater      field.String // 更新者
	CreatedAt    field.Time   // 创建时间
	UpdatedAt    field.Time   // 更新时间
	DeletedAt    field.Field  // 删除时间
	Deleted      field.Bool   // 是否删除

	fieldMap map[string]field.Expr
}

func (t tradeOrderLog) Table(newTableName string) *tradeOrderLog {
	t.tradeOrderLogDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tradeOrderLog) As(alias string) *tradeOrderLog {
	t.tradeOrderLogDo.DO = *(t.tradeOrderLogDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tradeOrderLog) updateTableName(table string) *tradeOrderLog {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.UserID = field.NewInt64(table, "user_id")
	t.UserType = field.NewInt(table, "user_type")
	t.OrderID = field.NewInt64(table, "order_id")
	t.BeforeStatus = field.NewInt(table, "before_status")
	t.AfterStatus = field.NewInt(table, "after_status")
	t.OperateType = field.NewInt(table, "operate_type")
	t.Content = field.NewString(table, "content")
	t.Creator = field.NewString(table, "creator")
	t.Updater = field.NewString(table, "updater")
	t.CreatedAt = field.NewTime(table, "create_time")
	t.UpdatedAt = field.NewTime(table, "update_time")
	t.DeletedAt = field.NewField(table, "deleted")
	t.Deleted = field.NewBool(table, "deleted")

	t.fillFieldMap()

	return t
}

func (t *tradeOrderLog) WithContext(ctx context.Context) ITradeOrderLogDo {
	return t.tradeOrderLogDo.WithContext(ctx)
}

func (t tradeOrderLog) TableName() string { return t.tradeOrderLogDo.TableName() }

func (t tradeOrderLog) Alias() string { return t.tradeOrderLogDo.Alias() }

func (t tradeOrderLog) Columns(cols ...field.Expr) gen.Columns {
	return t.tradeOrderLogDo.Columns(cols...)
}

func (t *tradeOrderLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tradeOrderLog) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 14)
	t.fieldMap["id"] = t.ID
	t.fieldMap["user_id"] = t.UserID
	t.fieldMap["user_type"] = t.UserType
	t.fieldMap["order_id"] = t.OrderID
	t.fieldMap["before_status"] = t.BeforeStatus
	t.fieldMap["after_status"] = t.AfterStatus
	t.fieldMap["operate_type"] = t.OperateType
	t.fieldMap["content"] = t.Content
	t.fieldMap["creator"] = t.Creator
	t.fieldMap["updater"] = t.Updater
	t.fieldMap["create_time"] = t.CreatedAt
	t.fieldMap["update_time"] = t.UpdatedAt
	t.fieldMap["deleted"] = t.DeletedAt
	t.fieldMap["deleted"] = t.Deleted
}

func (t tradeOrderLog) clone(db *gorm.DB) tradeOrderLog {
	t.tradeOrderLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tradeOrderLog) replaceDB(db *gorm.DB) tradeOrderLog {
	t.tradeOrderLogDo.ReplaceDB(db)
	return t
}

type tradeOrderLogDo struct{ gen.DO }

type ITradeOrderLogDo interface {
	gen.SubQuery
	Debug() ITradeOrderLogDo
	WithContext(ctx context.Context) ITradeOrderLogDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITradeOrderLogDo
	WriteDB() ITradeOrderLogDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITradeOrderLogDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITradeOrderLogDo
	Not(conds ...gen.Condition) ITradeOrderLogDo
	Or(conds ...gen.Condition) ITradeOrderLogDo
	Select(conds ...field.Expr) ITradeOrderLogDo
	Where(conds ...gen.Condition) ITradeOrderLogDo
	Order(conds ...field.Expr) ITradeOrderLogDo
	Distinct(cols ...field.Expr) ITradeOrderLogDo
	Omit(cols ...field.Expr) ITradeOrderLogDo
	Join(table schema.Tabler, on ...field.Expr) ITradeOrderLogDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITradeOrderLogDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITradeOrderLogDo
	Group(cols ...field.Expr) ITradeOrderLogDo
	Having(conds ...gen.Condition) ITradeOrderLogDo
	Limit(limit int) ITradeOrderLogDo
	Offset(offset int) ITradeOrderLogDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITradeOrderLogDo
	Unscoped() ITradeOrderLogDo
	Create(values ...*trade.TradeOrderLog) error
	CreateInBatches(values []*trade.TradeOrderLog, batchSize int) error
	Save(values ...*trade.TradeOrderLog) error
	First() (*trade.TradeOrderLog, error)
	Take() (*trade.TradeOrderLog, error)
	Last() (*trade.TradeOrderLog, error)
	Find() ([]*trade.TradeOrderLog, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*trade.TradeOrderLog, err error)
	FindInBatches(result *[]*trade.TradeOrderLog, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*trade.TradeOrderLog) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITradeOrderLogDo
	Assign(attrs ...field.AssignExpr) ITradeOrderLogDo
	Joins(fields ...field.RelationField) ITradeOrderLogDo
	Preload(fields ...field.RelationField) ITradeOrderLogDo
	FirstOrInit() (*trade.TradeOrderLog, error)
	FirstOrCreate() (*trade.TradeOrderLog, error)
	FindByPage(offset int, limit int) (result []*trade.TradeOrderLog, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITradeOrderLogDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tradeOrderLogDo) Debug() ITradeOrderLogDo {
	return t.withDO(t.DO.Debug())
}

func (t tradeOrderLogDo) WithContext(ctx context.Context) ITradeOrderLogDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tradeOrderLogDo) ReadDB() ITradeOrderLogDo {
	return t.Clauses(dbresolver.Read)
}

func (t tradeOrderLogDo) WriteDB() ITradeOrderLogDo {
	return t.Clauses(dbresolver.Write)
}

func (t tradeOrderLogDo) Session(config *gorm.Session) ITradeOrderLogDo {
	return t.withDO(t.DO.Session(config))
}

func (t tradeOrderLogDo) Clauses(conds ...clause.Expression) ITradeOrderLogDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tradeOrderLogDo) Returning(value interface{}, columns ...string) ITradeOrderLogDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tradeOrderLogDo) Not(conds ...gen.Condition) ITradeOrderLogDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tradeOrderLogDo) Or(conds ...gen.Condition) ITradeOrderLogDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tradeOrderLogDo) Select(conds ...field.Expr) ITradeOrderLogDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tradeOrderLogDo) Where(conds ...gen.Condition) ITradeOrderLogDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tradeOrderLogDo) Order(conds ...field.Expr) ITradeOrderLogDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tradeOrderLogDo) Distinct(cols ...field.Expr) ITradeOrderLogDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tradeOrderLogDo) Omit(cols ...field.Expr) ITradeOrderLogDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tradeOrderLogDo) Join(table schema.Tabler, on ...field.Expr) ITradeOrderLogDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tradeOrderLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITradeOrderLogDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tradeOrderLogDo) RightJoin(table schema.Tabler, on ...field.Expr) ITradeOrderLogDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tradeOrderLogDo) Group(cols ...field.Expr) ITradeOrderLogDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tradeOrderLogDo) Having(conds ...gen.Condition) ITradeOrderLogDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tradeOrderLogDo) Limit(limit int) ITradeOrderLogDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tradeOrderLogDo) Offset(offset int) ITradeOrderLogDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tradeOrderLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITradeOrderLogDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tradeOrderLogDo) Unscoped() ITradeOrderLogDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tradeOrderLogDo) Create(values ...*trade.TradeOrderLog) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tradeOrderLogDo) CreateInBatches(values []*trade.TradeOrderLog, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tradeOrderLogDo) Save(values ...*trade.TradeOrderLog) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tradeOrderLogDo) First() (*trade.TradeOrderLog, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*trade.TradeOrderLog), nil
	}
}

func (t tradeOrderLogDo) Take() (*trade.TradeOrderLog, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*trade.TradeOrderLog), nil
	}
}

func (t tradeOrderLogDo) Last() (*trade.TradeOrderLog, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*trade.TradeOrderLog), nil
	}
}

func (t tradeOrderLogDo) Find() ([]*trade.TradeOrderLog, error) {
	result, err := t.DO.Find()
	return result.([]*trade.TradeOrderLog), err
}

func (t tradeOrderLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*trade.TradeOrderLog, err error) {
	buf := make([]*trade.TradeOrderLog, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tradeOrderLogDo) FindInBatches(result *[]*trade.TradeOrderLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tradeOrderLogDo) Attrs(attrs ...field.AssignExpr) ITradeOrderLogDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tradeOrderLogDo) Assign(attrs ...field.AssignExpr) ITradeOrderLogDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tradeOrderLogDo) Joins(fields ...field.RelationField) ITradeOrderLogDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tradeOrderLogDo) Preload(fields ...field.RelationField) ITradeOrderLogDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tradeOrderLogDo) FirstOrInit() (*trade.TradeOrderLog, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*trade.TradeOrderLog), nil
	}
}

func (t tradeOrderLogDo) FirstOrCreate() (*trade.TradeOrderLog, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*trade.TradeOrderLog), nil
	}
}

func (t tradeOrderLogDo) FindByPage(offset int, limit int) (result []*trade.TradeOrderLog, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tradeOrderLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tradeOrderLogDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tradeOrderLogDo) Delete(models ...*trade.TradeOrderLog) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tradeOrderLogDo) withDO(do gen.Dao) *tradeOrderLogDo {
	t.DO = *do.(*gen.DO)
	return t
}
