// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend-go/internal/model/trade"
)

func newTradeDeliveryPickUpStore(db *gorm.DB, opts ...gen.DOOption) tradeDeliveryPickUpStore {
	_tradeDeliveryPickUpStore := tradeDeliveryPickUpStore{}

	_tradeDeliveryPickUpStore.tradeDeliveryPickUpStoreDo.UseDB(db, opts...)
	_tradeDeliveryPickUpStore.tradeDeliveryPickUpStoreDo.UseModel(&trade.TradeDeliveryPickUpStore{})

	tableName := _tradeDeliveryPickUpStore.tradeDeliveryPickUpStoreDo.TableName()
	_tradeDeliveryPickUpStore.ALL = field.NewAsterisk(tableName)
	_tradeDeliveryPickUpStore.ID = field.NewInt64(tableName, "id")
	_tradeDeliveryPickUpStore.Name = field.NewString(tableName, "name")
	_tradeDeliveryPickUpStore.Introduction = field.NewString(tableName, "introduction")
	_tradeDeliveryPickUpStore.Phone = field.NewString(tableName, "phone")
	_tradeDeliveryPickUpStore.AreaID = field.NewInt(tableName, "area_id")
	_tradeDeliveryPickUpStore.DetailAddress = field.NewString(tableName, "detail_address")
	_tradeDeliveryPickUpStore.Logo = field.NewString(tableName, "logo")
	_tradeDeliveryPickUpStore.Latitude = field.NewFloat64(tableName, "latitude")
	_tradeDeliveryPickUpStore.Longitude = field.NewFloat64(tableName, "longitude")
	_tradeDeliveryPickUpStore.Status = field.NewInt(tableName, "status")
	_tradeDeliveryPickUpStore.Sort = field.NewInt(tableName, "sort")
	_tradeDeliveryPickUpStore.Creator = field.NewString(tableName, "creator")
	_tradeDeliveryPickUpStore.Updater = field.NewString(tableName, "updater")
	_tradeDeliveryPickUpStore.CreatedAt = field.NewTime(tableName, "create_time")
	_tradeDeliveryPickUpStore.UpdatedAt = field.NewTime(tableName, "update_time")
	_tradeDeliveryPickUpStore.Deleted = field.NewField(tableName, "deleted")
	_tradeDeliveryPickUpStore.TenantID = field.NewInt64(tableName, "tenant_id")

	_tradeDeliveryPickUpStore.fillFieldMap()

	return _tradeDeliveryPickUpStore
}

type tradeDeliveryPickUpStore struct {
	tradeDeliveryPickUpStoreDo tradeDeliveryPickUpStoreDo

	ALL           field.Asterisk
	ID            field.Int64   // 编号
	Name          field.String  // 门店名称
	Introduction  field.String  // 门店简介
	Phone         field.String  // 联系电话
	AreaID        field.Int     // 区域编号
	DetailAddress field.String  // 详细地址
	Logo          field.String  // 门店Logo
	Latitude      field.Float64 // 纬度
	Longitude     field.Float64 // 经度
	Status        field.Int     // 状态
	Sort          field.Int     // 排序
	Creator       field.String  // 创建者
	Updater       field.String  // 更新者
	CreatedAt     field.Time    // 创建时间
	UpdatedAt     field.Time    // 更新时间
	Deleted       field.Field   // 是否删除
	TenantID      field.Int64   // 租户编号

	fieldMap map[string]field.Expr
}

func (t tradeDeliveryPickUpStore) Table(newTableName string) *tradeDeliveryPickUpStore {
	t.tradeDeliveryPickUpStoreDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tradeDeliveryPickUpStore) As(alias string) *tradeDeliveryPickUpStore {
	t.tradeDeliveryPickUpStoreDo.DO = *(t.tradeDeliveryPickUpStoreDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tradeDeliveryPickUpStore) updateTableName(table string) *tradeDeliveryPickUpStore {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.Name = field.NewString(table, "name")
	t.Introduction = field.NewString(table, "introduction")
	t.Phone = field.NewString(table, "phone")
	t.AreaID = field.NewInt(table, "area_id")
	t.DetailAddress = field.NewString(table, "detail_address")
	t.Logo = field.NewString(table, "logo")
	t.Latitude = field.NewFloat64(table, "latitude")
	t.Longitude = field.NewFloat64(table, "longitude")
	t.Status = field.NewInt(table, "status")
	t.Sort = field.NewInt(table, "sort")
	t.Creator = field.NewString(table, "creator")
	t.Updater = field.NewString(table, "updater")
	t.CreatedAt = field.NewTime(table, "create_time")
	t.UpdatedAt = field.NewTime(table, "update_time")
	t.Deleted = field.NewField(table, "deleted")
	t.TenantID = field.NewInt64(table, "tenant_id")

	t.fillFieldMap()

	return t
}

func (t *tradeDeliveryPickUpStore) WithContext(ctx context.Context) ITradeDeliveryPickUpStoreDo {
	return t.tradeDeliveryPickUpStoreDo.WithContext(ctx)
}

func (t tradeDeliveryPickUpStore) TableName() string { return t.tradeDeliveryPickUpStoreDo.TableName() }

func (t tradeDeliveryPickUpStore) Alias() string { return t.tradeDeliveryPickUpStoreDo.Alias() }

func (t tradeDeliveryPickUpStore) Columns(cols ...field.Expr) gen.Columns {
	return t.tradeDeliveryPickUpStoreDo.Columns(cols...)
}

func (t *tradeDeliveryPickUpStore) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tradeDeliveryPickUpStore) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 17)
	t.fieldMap["id"] = t.ID
	t.fieldMap["name"] = t.Name
	t.fieldMap["introduction"] = t.Introduction
	t.fieldMap["phone"] = t.Phone
	t.fieldMap["area_id"] = t.AreaID
	t.fieldMap["detail_address"] = t.DetailAddress
	t.fieldMap["logo"] = t.Logo
	t.fieldMap["latitude"] = t.Latitude
	t.fieldMap["longitude"] = t.Longitude
	t.fieldMap["status"] = t.Status
	t.fieldMap["sort"] = t.Sort
	t.fieldMap["creator"] = t.Creator
	t.fieldMap["updater"] = t.Updater
	t.fieldMap["create_time"] = t.CreatedAt
	t.fieldMap["update_time"] = t.UpdatedAt
	t.fieldMap["deleted"] = t.Deleted
	t.fieldMap["tenant_id"] = t.TenantID
}

func (t tradeDeliveryPickUpStore) clone(db *gorm.DB) tradeDeliveryPickUpStore {
	t.tradeDeliveryPickUpStoreDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tradeDeliveryPickUpStore) replaceDB(db *gorm.DB) tradeDeliveryPickUpStore {
	t.tradeDeliveryPickUpStoreDo.ReplaceDB(db)
	return t
}

type tradeDeliveryPickUpStoreDo struct{ gen.DO }

type ITradeDeliveryPickUpStoreDo interface {
	gen.SubQuery
	Debug() ITradeDeliveryPickUpStoreDo
	WithContext(ctx context.Context) ITradeDeliveryPickUpStoreDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITradeDeliveryPickUpStoreDo
	WriteDB() ITradeDeliveryPickUpStoreDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITradeDeliveryPickUpStoreDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITradeDeliveryPickUpStoreDo
	Not(conds ...gen.Condition) ITradeDeliveryPickUpStoreDo
	Or(conds ...gen.Condition) ITradeDeliveryPickUpStoreDo
	Select(conds ...field.Expr) ITradeDeliveryPickUpStoreDo
	Where(conds ...gen.Condition) ITradeDeliveryPickUpStoreDo
	Order(conds ...field.Expr) ITradeDeliveryPickUpStoreDo
	Distinct(cols ...field.Expr) ITradeDeliveryPickUpStoreDo
	Omit(cols ...field.Expr) ITradeDeliveryPickUpStoreDo
	Join(table schema.Tabler, on ...field.Expr) ITradeDeliveryPickUpStoreDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITradeDeliveryPickUpStoreDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITradeDeliveryPickUpStoreDo
	Group(cols ...field.Expr) ITradeDeliveryPickUpStoreDo
	Having(conds ...gen.Condition) ITradeDeliveryPickUpStoreDo
	Limit(limit int) ITradeDeliveryPickUpStoreDo
	Offset(offset int) ITradeDeliveryPickUpStoreDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITradeDeliveryPickUpStoreDo
	Unscoped() ITradeDeliveryPickUpStoreDo
	Create(values ...*trade.TradeDeliveryPickUpStore) error
	CreateInBatches(values []*trade.TradeDeliveryPickUpStore, batchSize int) error
	Save(values ...*trade.TradeDeliveryPickUpStore) error
	First() (*trade.TradeDeliveryPickUpStore, error)
	Take() (*trade.TradeDeliveryPickUpStore, error)
	Last() (*trade.TradeDeliveryPickUpStore, error)
	Find() ([]*trade.TradeDeliveryPickUpStore, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*trade.TradeDeliveryPickUpStore, err error)
	FindInBatches(result *[]*trade.TradeDeliveryPickUpStore, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*trade.TradeDeliveryPickUpStore) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITradeDeliveryPickUpStoreDo
	Assign(attrs ...field.AssignExpr) ITradeDeliveryPickUpStoreDo
	Joins(fields ...field.RelationField) ITradeDeliveryPickUpStoreDo
	Preload(fields ...field.RelationField) ITradeDeliveryPickUpStoreDo
	FirstOrInit() (*trade.TradeDeliveryPickUpStore, error)
	FirstOrCreate() (*trade.TradeDeliveryPickUpStore, error)
	FindByPage(offset int, limit int) (result []*trade.TradeDeliveryPickUpStore, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITradeDeliveryPickUpStoreDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tradeDeliveryPickUpStoreDo) Debug() ITradeDeliveryPickUpStoreDo {
	return t.withDO(t.DO.Debug())
}

func (t tradeDeliveryPickUpStoreDo) WithContext(ctx context.Context) ITradeDeliveryPickUpStoreDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tradeDeliveryPickUpStoreDo) ReadDB() ITradeDeliveryPickUpStoreDo {
	return t.Clauses(dbresolver.Read)
}

func (t tradeDeliveryPickUpStoreDo) WriteDB() ITradeDeliveryPickUpStoreDo {
	return t.Clauses(dbresolver.Write)
}

func (t tradeDeliveryPickUpStoreDo) Session(config *gorm.Session) ITradeDeliveryPickUpStoreDo {
	return t.withDO(t.DO.Session(config))
}

func (t tradeDeliveryPickUpStoreDo) Clauses(conds ...clause.Expression) ITradeDeliveryPickUpStoreDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tradeDeliveryPickUpStoreDo) Returning(value interface{}, columns ...string) ITradeDeliveryPickUpStoreDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tradeDeliveryPickUpStoreDo) Not(conds ...gen.Condition) ITradeDeliveryPickUpStoreDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tradeDeliveryPickUpStoreDo) Or(conds ...gen.Condition) ITradeDeliveryPickUpStoreDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tradeDeliveryPickUpStoreDo) Select(conds ...field.Expr) ITradeDeliveryPickUpStoreDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tradeDeliveryPickUpStoreDo) Where(conds ...gen.Condition) ITradeDeliveryPickUpStoreDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tradeDeliveryPickUpStoreDo) Order(conds ...field.Expr) ITradeDeliveryPickUpStoreDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tradeDeliveryPickUpStoreDo) Distinct(cols ...field.Expr) ITradeDeliveryPickUpStoreDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tradeDeliveryPickUpStoreDo) Omit(cols ...field.Expr) ITradeDeliveryPickUpStoreDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tradeDeliveryPickUpStoreDo) Join(table schema.Tabler, on ...field.Expr) ITradeDeliveryPickUpStoreDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tradeDeliveryPickUpStoreDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITradeDeliveryPickUpStoreDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tradeDeliveryPickUpStoreDo) RightJoin(table schema.Tabler, on ...field.Expr) ITradeDeliveryPickUpStoreDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tradeDeliveryPickUpStoreDo) Group(cols ...field.Expr) ITradeDeliveryPickUpStoreDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tradeDeliveryPickUpStoreDo) Having(conds ...gen.Condition) ITradeDeliveryPickUpStoreDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tradeDeliveryPickUpStoreDo) Limit(limit int) ITradeDeliveryPickUpStoreDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tradeDeliveryPickUpStoreDo) Offset(offset int) ITradeDeliveryPickUpStoreDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tradeDeliveryPickUpStoreDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITradeDeliveryPickUpStoreDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tradeDeliveryPickUpStoreDo) Unscoped() ITradeDeliveryPickUpStoreDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tradeDeliveryPickUpStoreDo) Create(values ...*trade.TradeDeliveryPickUpStore) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tradeDeliveryPickUpStoreDo) CreateInBatches(values []*trade.TradeDeliveryPickUpStore, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tradeDeliveryPickUpStoreDo) Save(values ...*trade.TradeDeliveryPickUpStore) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tradeDeliveryPickUpStoreDo) First() (*trade.TradeDeliveryPickUpStore, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*trade.TradeDeliveryPickUpStore), nil
	}
}

func (t tradeDeliveryPickUpStoreDo) Take() (*trade.TradeDeliveryPickUpStore, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*trade.TradeDeliveryPickUpStore), nil
	}
}

func (t tradeDeliveryPickUpStoreDo) Last() (*trade.TradeDeliveryPickUpStore, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*trade.TradeDeliveryPickUpStore), nil
	}
}

func (t tradeDeliveryPickUpStoreDo) Find() ([]*trade.TradeDeliveryPickUpStore, error) {
	result, err := t.DO.Find()
	return result.([]*trade.TradeDeliveryPickUpStore), err
}

func (t tradeDeliveryPickUpStoreDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*trade.TradeDeliveryPickUpStore, err error) {
	buf := make([]*trade.TradeDeliveryPickUpStore, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tradeDeliveryPickUpStoreDo) FindInBatches(result *[]*trade.TradeDeliveryPickUpStore, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tradeDeliveryPickUpStoreDo) Attrs(attrs ...field.AssignExpr) ITradeDeliveryPickUpStoreDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tradeDeliveryPickUpStoreDo) Assign(attrs ...field.AssignExpr) ITradeDeliveryPickUpStoreDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tradeDeliveryPickUpStoreDo) Joins(fields ...field.RelationField) ITradeDeliveryPickUpStoreDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tradeDeliveryPickUpStoreDo) Preload(fields ...field.RelationField) ITradeDeliveryPickUpStoreDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tradeDeliveryPickUpStoreDo) FirstOrInit() (*trade.TradeDeliveryPickUpStore, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*trade.TradeDeliveryPickUpStore), nil
	}
}

func (t tradeDeliveryPickUpStoreDo) FirstOrCreate() (*trade.TradeDeliveryPickUpStore, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*trade.TradeDeliveryPickUpStore), nil
	}
}

func (t tradeDeliveryPickUpStoreDo) FindByPage(offset int, limit int) (result []*trade.TradeDeliveryPickUpStore, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tradeDeliveryPickUpStoreDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tradeDeliveryPickUpStoreDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tradeDeliveryPickUpStoreDo) Delete(models ...*trade.TradeDeliveryPickUpStore) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tradeDeliveryPickUpStoreDo) withDO(do gen.Dao) *tradeDeliveryPickUpStoreDo {
	t.DO = *do.(*gen.DO)
	return t
}
