// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend-go/internal/model/trade"
)

func newTradeDeliveryFreightTemplateFree(db *gorm.DB, opts ...gen.DOOption) tradeDeliveryFreightTemplateFree {
	_tradeDeliveryFreightTemplateFree := tradeDeliveryFreightTemplateFree{}

	_tradeDeliveryFreightTemplateFree.tradeDeliveryFreightTemplateFreeDo.UseDB(db, opts...)
	_tradeDeliveryFreightTemplateFree.tradeDeliveryFreightTemplateFreeDo.UseModel(&trade.TradeDeliveryFreightTemplateFree{})

	tableName := _tradeDeliveryFreightTemplateFree.tradeDeliveryFreightTemplateFreeDo.TableName()
	_tradeDeliveryFreightTemplateFree.ALL = field.NewAsterisk(tableName)
	_tradeDeliveryFreightTemplateFree.ID = field.NewInt64(tableName, "id")
	_tradeDeliveryFreightTemplateFree.TemplateID = field.NewInt64(tableName, "template_id")
	_tradeDeliveryFreightTemplateFree.AreaIDs = field.NewString(tableName, "area_ids")
	_tradeDeliveryFreightTemplateFree.FreePrice = field.NewInt(tableName, "free_price")
	_tradeDeliveryFreightTemplateFree.FreeCount = field.NewFloat64(tableName, "free_count")
	_tradeDeliveryFreightTemplateFree.Creator = field.NewString(tableName, "creator")
	_tradeDeliveryFreightTemplateFree.Updater = field.NewString(tableName, "updater")
	_tradeDeliveryFreightTemplateFree.CreatedAt = field.NewTime(tableName, "create_time")
	_tradeDeliveryFreightTemplateFree.UpdatedAt = field.NewTime(tableName, "update_time")
	_tradeDeliveryFreightTemplateFree.Deleted = field.NewField(tableName, "deleted")

	_tradeDeliveryFreightTemplateFree.fillFieldMap()

	return _tradeDeliveryFreightTemplateFree
}

type tradeDeliveryFreightTemplateFree struct {
	tradeDeliveryFreightTemplateFreeDo tradeDeliveryFreightTemplateFreeDo

	ALL        field.Asterisk
	ID         field.Int64   // 编号
	TemplateID field.Int64   // 模板编号
	AreaIDs    field.String  // 区域编号列表
	FreePrice  field.Int     // 包邮金额(分)
	FreeCount  field.Float64 // 包邮件数/重量/体积
	Creator    field.String  // 创建者
	Updater    field.String  // 更新者
	CreatedAt  field.Time    // 创建时间
	UpdatedAt  field.Time    // 更新时间
	Deleted    field.Field   // 是否删除

	fieldMap map[string]field.Expr
}

func (t tradeDeliveryFreightTemplateFree) Table(newTableName string) *tradeDeliveryFreightTemplateFree {
	t.tradeDeliveryFreightTemplateFreeDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tradeDeliveryFreightTemplateFree) As(alias string) *tradeDeliveryFreightTemplateFree {
	t.tradeDeliveryFreightTemplateFreeDo.DO = *(t.tradeDeliveryFreightTemplateFreeDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tradeDeliveryFreightTemplateFree) updateTableName(table string) *tradeDeliveryFreightTemplateFree {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.TemplateID = field.NewInt64(table, "template_id")
	t.AreaIDs = field.NewString(table, "area_ids")
	t.FreePrice = field.NewInt(table, "free_price")
	t.FreeCount = field.NewFloat64(table, "free_count")
	t.Creator = field.NewString(table, "creator")
	t.Updater = field.NewString(table, "updater")
	t.CreatedAt = field.NewTime(table, "create_time")
	t.UpdatedAt = field.NewTime(table, "update_time")
	t.Deleted = field.NewField(table, "deleted")

	t.fillFieldMap()

	return t
}

func (t *tradeDeliveryFreightTemplateFree) WithContext(ctx context.Context) ITradeDeliveryFreightTemplateFreeDo {
	return t.tradeDeliveryFreightTemplateFreeDo.WithContext(ctx)
}

func (t tradeDeliveryFreightTemplateFree) TableName() string {
	return t.tradeDeliveryFreightTemplateFreeDo.TableName()
}

func (t tradeDeliveryFreightTemplateFree) Alias() string {
	return t.tradeDeliveryFreightTemplateFreeDo.Alias()
}

func (t tradeDeliveryFreightTemplateFree) Columns(cols ...field.Expr) gen.Columns {
	return t.tradeDeliveryFreightTemplateFreeDo.Columns(cols...)
}

func (t *tradeDeliveryFreightTemplateFree) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tradeDeliveryFreightTemplateFree) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 10)
	t.fieldMap["id"] = t.ID
	t.fieldMap["template_id"] = t.TemplateID
	t.fieldMap["area_ids"] = t.AreaIDs
	t.fieldMap["free_price"] = t.FreePrice
	t.fieldMap["free_count"] = t.FreeCount
	t.fieldMap["creator"] = t.Creator
	t.fieldMap["updater"] = t.Updater
	t.fieldMap["create_time"] = t.CreatedAt
	t.fieldMap["update_time"] = t.UpdatedAt
	t.fieldMap["deleted"] = t.Deleted
}

func (t tradeDeliveryFreightTemplateFree) clone(db *gorm.DB) tradeDeliveryFreightTemplateFree {
	t.tradeDeliveryFreightTemplateFreeDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tradeDeliveryFreightTemplateFree) replaceDB(db *gorm.DB) tradeDeliveryFreightTemplateFree {
	t.tradeDeliveryFreightTemplateFreeDo.ReplaceDB(db)
	return t
}

type tradeDeliveryFreightTemplateFreeDo struct{ gen.DO }

type ITradeDeliveryFreightTemplateFreeDo interface {
	gen.SubQuery
	Debug() ITradeDeliveryFreightTemplateFreeDo
	WithContext(ctx context.Context) ITradeDeliveryFreightTemplateFreeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITradeDeliveryFreightTemplateFreeDo
	WriteDB() ITradeDeliveryFreightTemplateFreeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITradeDeliveryFreightTemplateFreeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITradeDeliveryFreightTemplateFreeDo
	Not(conds ...gen.Condition) ITradeDeliveryFreightTemplateFreeDo
	Or(conds ...gen.Condition) ITradeDeliveryFreightTemplateFreeDo
	Select(conds ...field.Expr) ITradeDeliveryFreightTemplateFreeDo
	Where(conds ...gen.Condition) ITradeDeliveryFreightTemplateFreeDo
	Order(conds ...field.Expr) ITradeDeliveryFreightTemplateFreeDo
	Distinct(cols ...field.Expr) ITradeDeliveryFreightTemplateFreeDo
	Omit(cols ...field.Expr) ITradeDeliveryFreightTemplateFreeDo
	Join(table schema.Tabler, on ...field.Expr) ITradeDeliveryFreightTemplateFreeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITradeDeliveryFreightTemplateFreeDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITradeDeliveryFreightTemplateFreeDo
	Group(cols ...field.Expr) ITradeDeliveryFreightTemplateFreeDo
	Having(conds ...gen.Condition) ITradeDeliveryFreightTemplateFreeDo
	Limit(limit int) ITradeDeliveryFreightTemplateFreeDo
	Offset(offset int) ITradeDeliveryFreightTemplateFreeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITradeDeliveryFreightTemplateFreeDo
	Unscoped() ITradeDeliveryFreightTemplateFreeDo
	Create(values ...*trade.TradeDeliveryFreightTemplateFree) error
	CreateInBatches(values []*trade.TradeDeliveryFreightTemplateFree, batchSize int) error
	Save(values ...*trade.TradeDeliveryFreightTemplateFree) error
	First() (*trade.TradeDeliveryFreightTemplateFree, error)
	Take() (*trade.TradeDeliveryFreightTemplateFree, error)
	Last() (*trade.TradeDeliveryFreightTemplateFree, error)
	Find() ([]*trade.TradeDeliveryFreightTemplateFree, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*trade.TradeDeliveryFreightTemplateFree, err error)
	FindInBatches(result *[]*trade.TradeDeliveryFreightTemplateFree, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*trade.TradeDeliveryFreightTemplateFree) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITradeDeliveryFreightTemplateFreeDo
	Assign(attrs ...field.AssignExpr) ITradeDeliveryFreightTemplateFreeDo
	Joins(fields ...field.RelationField) ITradeDeliveryFreightTemplateFreeDo
	Preload(fields ...field.RelationField) ITradeDeliveryFreightTemplateFreeDo
	FirstOrInit() (*trade.TradeDeliveryFreightTemplateFree, error)
	FirstOrCreate() (*trade.TradeDeliveryFreightTemplateFree, error)
	FindByPage(offset int, limit int) (result []*trade.TradeDeliveryFreightTemplateFree, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITradeDeliveryFreightTemplateFreeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tradeDeliveryFreightTemplateFreeDo) Debug() ITradeDeliveryFreightTemplateFreeDo {
	return t.withDO(t.DO.Debug())
}

func (t tradeDeliveryFreightTemplateFreeDo) WithContext(ctx context.Context) ITradeDeliveryFreightTemplateFreeDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tradeDeliveryFreightTemplateFreeDo) ReadDB() ITradeDeliveryFreightTemplateFreeDo {
	return t.Clauses(dbresolver.Read)
}

func (t tradeDeliveryFreightTemplateFreeDo) WriteDB() ITradeDeliveryFreightTemplateFreeDo {
	return t.Clauses(dbresolver.Write)
}

func (t tradeDeliveryFreightTemplateFreeDo) Session(config *gorm.Session) ITradeDeliveryFreightTemplateFreeDo {
	return t.withDO(t.DO.Session(config))
}

func (t tradeDeliveryFreightTemplateFreeDo) Clauses(conds ...clause.Expression) ITradeDeliveryFreightTemplateFreeDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tradeDeliveryFreightTemplateFreeDo) Returning(value interface{}, columns ...string) ITradeDeliveryFreightTemplateFreeDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tradeDeliveryFreightTemplateFreeDo) Not(conds ...gen.Condition) ITradeDeliveryFreightTemplateFreeDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tradeDeliveryFreightTemplateFreeDo) Or(conds ...gen.Condition) ITradeDeliveryFreightTemplateFreeDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tradeDeliveryFreightTemplateFreeDo) Select(conds ...field.Expr) ITradeDeliveryFreightTemplateFreeDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tradeDeliveryFreightTemplateFreeDo) Where(conds ...gen.Condition) ITradeDeliveryFreightTemplateFreeDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tradeDeliveryFreightTemplateFreeDo) Order(conds ...field.Expr) ITradeDeliveryFreightTemplateFreeDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tradeDeliveryFreightTemplateFreeDo) Distinct(cols ...field.Expr) ITradeDeliveryFreightTemplateFreeDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tradeDeliveryFreightTemplateFreeDo) Omit(cols ...field.Expr) ITradeDeliveryFreightTemplateFreeDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tradeDeliveryFreightTemplateFreeDo) Join(table schema.Tabler, on ...field.Expr) ITradeDeliveryFreightTemplateFreeDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tradeDeliveryFreightTemplateFreeDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITradeDeliveryFreightTemplateFreeDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tradeDeliveryFreightTemplateFreeDo) RightJoin(table schema.Tabler, on ...field.Expr) ITradeDeliveryFreightTemplateFreeDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tradeDeliveryFreightTemplateFreeDo) Group(cols ...field.Expr) ITradeDeliveryFreightTemplateFreeDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tradeDeliveryFreightTemplateFreeDo) Having(conds ...gen.Condition) ITradeDeliveryFreightTemplateFreeDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tradeDeliveryFreightTemplateFreeDo) Limit(limit int) ITradeDeliveryFreightTemplateFreeDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tradeDeliveryFreightTemplateFreeDo) Offset(offset int) ITradeDeliveryFreightTemplateFreeDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tradeDeliveryFreightTemplateFreeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITradeDeliveryFreightTemplateFreeDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tradeDeliveryFreightTemplateFreeDo) Unscoped() ITradeDeliveryFreightTemplateFreeDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tradeDeliveryFreightTemplateFreeDo) Create(values ...*trade.TradeDeliveryFreightTemplateFree) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tradeDeliveryFreightTemplateFreeDo) CreateInBatches(values []*trade.TradeDeliveryFreightTemplateFree, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tradeDeliveryFreightTemplateFreeDo) Save(values ...*trade.TradeDeliveryFreightTemplateFree) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tradeDeliveryFreightTemplateFreeDo) First() (*trade.TradeDeliveryFreightTemplateFree, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*trade.TradeDeliveryFreightTemplateFree), nil
	}
}

func (t tradeDeliveryFreightTemplateFreeDo) Take() (*trade.TradeDeliveryFreightTemplateFree, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*trade.TradeDeliveryFreightTemplateFree), nil
	}
}

func (t tradeDeliveryFreightTemplateFreeDo) Last() (*trade.TradeDeliveryFreightTemplateFree, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*trade.TradeDeliveryFreightTemplateFree), nil
	}
}

func (t tradeDeliveryFreightTemplateFreeDo) Find() ([]*trade.TradeDeliveryFreightTemplateFree, error) {
	result, err := t.DO.Find()
	return result.([]*trade.TradeDeliveryFreightTemplateFree), err
}

func (t tradeDeliveryFreightTemplateFreeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*trade.TradeDeliveryFreightTemplateFree, err error) {
	buf := make([]*trade.TradeDeliveryFreightTemplateFree, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tradeDeliveryFreightTemplateFreeDo) FindInBatches(result *[]*trade.TradeDeliveryFreightTemplateFree, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tradeDeliveryFreightTemplateFreeDo) Attrs(attrs ...field.AssignExpr) ITradeDeliveryFreightTemplateFreeDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tradeDeliveryFreightTemplateFreeDo) Assign(attrs ...field.AssignExpr) ITradeDeliveryFreightTemplateFreeDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tradeDeliveryFreightTemplateFreeDo) Joins(fields ...field.RelationField) ITradeDeliveryFreightTemplateFreeDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tradeDeliveryFreightTemplateFreeDo) Preload(fields ...field.RelationField) ITradeDeliveryFreightTemplateFreeDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tradeDeliveryFreightTemplateFreeDo) FirstOrInit() (*trade.TradeDeliveryFreightTemplateFree, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*trade.TradeDeliveryFreightTemplateFree), nil
	}
}

func (t tradeDeliveryFreightTemplateFreeDo) FirstOrCreate() (*trade.TradeDeliveryFreightTemplateFree, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*trade.TradeDeliveryFreightTemplateFree), nil
	}
}

func (t tradeDeliveryFreightTemplateFreeDo) FindByPage(offset int, limit int) (result []*trade.TradeDeliveryFreightTemplateFree, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tradeDeliveryFreightTemplateFreeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tradeDeliveryFreightTemplateFreeDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tradeDeliveryFreightTemplateFreeDo) Delete(models ...*trade.TradeDeliveryFreightTemplateFree) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tradeDeliveryFreightTemplateFreeDo) withDO(do gen.Dao) *tradeDeliveryFreightTemplateFreeDo {
	t.DO = *do.(*gen.DO)
	return t
}
