// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend-go/internal/model/trade"
)

func newTradeOrderItem(db *gorm.DB, opts ...gen.DOOption) tradeOrderItem {
	_tradeOrderItem := tradeOrderItem{}

	_tradeOrderItem.tradeOrderItemDo.UseDB(db, opts...)
	_tradeOrderItem.tradeOrderItemDo.UseModel(&trade.TradeOrderItem{})

	tableName := _tradeOrderItem.tradeOrderItemDo.TableName()
	_tradeOrderItem.ALL = field.NewAsterisk(tableName)
	_tradeOrderItem.ID = field.NewInt64(tableName, "id")
	_tradeOrderItem.UserID = field.NewInt64(tableName, "user_id")
	_tradeOrderItem.OrderID = field.NewInt64(tableName, "order_id")
	_tradeOrderItem.CartID = field.NewInt64(tableName, "cart_id")
	_tradeOrderItem.SpuID = field.NewInt64(tableName, "spu_id")
	_tradeOrderItem.SpuName = field.NewString(tableName, "spu_name")
	_tradeOrderItem.SkuID = field.NewInt64(tableName, "sku_id")
	_tradeOrderItem.Properties = field.NewField(tableName, "properties")
	_tradeOrderItem.PicURL = field.NewString(tableName, "pic_url")
	_tradeOrderItem.Count = field.NewInt(tableName, "count")
	_tradeOrderItem.CommentStatus = field.NewBool(tableName, "comment_status")
	_tradeOrderItem.Price = field.NewInt(tableName, "price")
	_tradeOrderItem.DiscountPrice = field.NewInt(tableName, "discount_price")
	_tradeOrderItem.DeliveryPrice = field.NewInt(tableName, "delivery_price")
	_tradeOrderItem.AdjustPrice = field.NewInt(tableName, "adjust_price")
	_tradeOrderItem.PayPrice = field.NewInt(tableName, "pay_price")
	_tradeOrderItem.CouponPrice = field.NewInt(tableName, "coupon_price")
	_tradeOrderItem.PointPrice = field.NewInt(tableName, "point_price")
	_tradeOrderItem.UsePoint = field.NewInt(tableName, "use_point")
	_tradeOrderItem.GivePoint = field.NewInt(tableName, "give_point")
	_tradeOrderItem.VipPrice = field.NewInt(tableName, "vip_price")
	_tradeOrderItem.AfterSaleID = field.NewInt64(tableName, "after_sale_id")
	_tradeOrderItem.AfterSaleStatus = field.NewInt(tableName, "after_sale_status")
	_tradeOrderItem.Creator = field.NewString(tableName, "creator")
	_tradeOrderItem.Updater = field.NewString(tableName, "updater")
	_tradeOrderItem.CreatedAt = field.NewTime(tableName, "create_time")
	_tradeOrderItem.UpdatedAt = field.NewTime(tableName, "update_time")
	_tradeOrderItem.DeletedAt = field.NewField(tableName, "deleted")
	_tradeOrderItem.Deleted = field.NewBool(tableName, "deleted")

	_tradeOrderItem.fillFieldMap()

	return _tradeOrderItem
}

type tradeOrderItem struct {
	tradeOrderItemDo tradeOrderItemDo

	ALL             field.Asterisk
	ID              field.Int64  // 订单项编号
	UserID          field.Int64  // 用户编号
	OrderID         field.Int64  // 订单编号
	CartID          field.Int64  // 购物车项编号
	SpuID           field.Int64  // 商品 SPU 编号
	SpuName         field.String // 商品 SPU 名称
	SkuID           field.Int64  // 商品 SKU 编号
	Properties      field.Field  // 属性数组
	PicURL          field.String // 商品图片
	Count           field.Int    // 购买数量
	CommentStatus   field.Bool   // 是否评价
	Price           field.Int    // 商品原价
	DiscountPrice   field.Int    // 优惠金额
	DeliveryPrice   field.Int    // 运费金额
	AdjustPrice     field.Int    // 订单调价
	PayPrice        field.Int    // 应付金额
	CouponPrice     field.Int    // 优惠劵减免金额
	PointPrice      field.Int    // 积分抵扣的金额
	UsePoint        field.Int    // 使用的积分
	GivePoint       field.Int    // 赠送的积分
	VipPrice        field.Int    // VIP 减免金额
	AfterSaleID     field.Int64  // 售后单编号
	AfterSaleStatus field.Int    // 售后状态
	Creator         field.String // 创建者
	Updater         field.String // 更新者
	CreatedAt       field.Time   // 创建时间
	UpdatedAt       field.Time   // 更新时间
	DeletedAt       field.Field  // 删除时间
	Deleted         field.Bool   // 是否删除

	fieldMap map[string]field.Expr
}

func (t tradeOrderItem) Table(newTableName string) *tradeOrderItem {
	t.tradeOrderItemDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tradeOrderItem) As(alias string) *tradeOrderItem {
	t.tradeOrderItemDo.DO = *(t.tradeOrderItemDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tradeOrderItem) updateTableName(table string) *tradeOrderItem {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.UserID = field.NewInt64(table, "user_id")
	t.OrderID = field.NewInt64(table, "order_id")
	t.CartID = field.NewInt64(table, "cart_id")
	t.SpuID = field.NewInt64(table, "spu_id")
	t.SpuName = field.NewString(table, "spu_name")
	t.SkuID = field.NewInt64(table, "sku_id")
	t.Properties = field.NewField(table, "properties")
	t.PicURL = field.NewString(table, "pic_url")
	t.Count = field.NewInt(table, "count")
	t.CommentStatus = field.NewBool(table, "comment_status")
	t.Price = field.NewInt(table, "price")
	t.DiscountPrice = field.NewInt(table, "discount_price")
	t.DeliveryPrice = field.NewInt(table, "delivery_price")
	t.AdjustPrice = field.NewInt(table, "adjust_price")
	t.PayPrice = field.NewInt(table, "pay_price")
	t.CouponPrice = field.NewInt(table, "coupon_price")
	t.PointPrice = field.NewInt(table, "point_price")
	t.UsePoint = field.NewInt(table, "use_point")
	t.GivePoint = field.NewInt(table, "give_point")
	t.VipPrice = field.NewInt(table, "vip_price")
	t.AfterSaleID = field.NewInt64(table, "after_sale_id")
	t.AfterSaleStatus = field.NewInt(table, "after_sale_status")
	t.Creator = field.NewString(table, "creator")
	t.Updater = field.NewString(table, "updater")
	t.CreatedAt = field.NewTime(table, "create_time")
	t.UpdatedAt = field.NewTime(table, "update_time")
	t.DeletedAt = field.NewField(table, "deleted")
	t.Deleted = field.NewBool(table, "deleted")

	t.fillFieldMap()

	return t
}

func (t *tradeOrderItem) WithContext(ctx context.Context) ITradeOrderItemDo {
	return t.tradeOrderItemDo.WithContext(ctx)
}

func (t tradeOrderItem) TableName() string { return t.tradeOrderItemDo.TableName() }

func (t tradeOrderItem) Alias() string { return t.tradeOrderItemDo.Alias() }

func (t tradeOrderItem) Columns(cols ...field.Expr) gen.Columns {
	return t.tradeOrderItemDo.Columns(cols...)
}

func (t *tradeOrderItem) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tradeOrderItem) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 29)
	t.fieldMap["id"] = t.ID
	t.fieldMap["user_id"] = t.UserID
	t.fieldMap["order_id"] = t.OrderID
	t.fieldMap["cart_id"] = t.CartID
	t.fieldMap["spu_id"] = t.SpuID
	t.fieldMap["spu_name"] = t.SpuName
	t.fieldMap["sku_id"] = t.SkuID
	t.fieldMap["properties"] = t.Properties
	t.fieldMap["pic_url"] = t.PicURL
	t.fieldMap["count"] = t.Count
	t.fieldMap["comment_status"] = t.CommentStatus
	t.fieldMap["price"] = t.Price
	t.fieldMap["discount_price"] = t.DiscountPrice
	t.fieldMap["delivery_price"] = t.DeliveryPrice
	t.fieldMap["adjust_price"] = t.AdjustPrice
	t.fieldMap["pay_price"] = t.PayPrice
	t.fieldMap["coupon_price"] = t.CouponPrice
	t.fieldMap["point_price"] = t.PointPrice
	t.fieldMap["use_point"] = t.UsePoint
	t.fieldMap["give_point"] = t.GivePoint
	t.fieldMap["vip_price"] = t.VipPrice
	t.fieldMap["after_sale_id"] = t.AfterSaleID
	t.fieldMap["after_sale_status"] = t.AfterSaleStatus
	t.fieldMap["creator"] = t.Creator
	t.fieldMap["updater"] = t.Updater
	t.fieldMap["create_time"] = t.CreatedAt
	t.fieldMap["update_time"] = t.UpdatedAt
	t.fieldMap["deleted"] = t.DeletedAt
	t.fieldMap["deleted"] = t.Deleted
}

func (t tradeOrderItem) clone(db *gorm.DB) tradeOrderItem {
	t.tradeOrderItemDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tradeOrderItem) replaceDB(db *gorm.DB) tradeOrderItem {
	t.tradeOrderItemDo.ReplaceDB(db)
	return t
}

type tradeOrderItemDo struct{ gen.DO }

type ITradeOrderItemDo interface {
	gen.SubQuery
	Debug() ITradeOrderItemDo
	WithContext(ctx context.Context) ITradeOrderItemDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITradeOrderItemDo
	WriteDB() ITradeOrderItemDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITradeOrderItemDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITradeOrderItemDo
	Not(conds ...gen.Condition) ITradeOrderItemDo
	Or(conds ...gen.Condition) ITradeOrderItemDo
	Select(conds ...field.Expr) ITradeOrderItemDo
	Where(conds ...gen.Condition) ITradeOrderItemDo
	Order(conds ...field.Expr) ITradeOrderItemDo
	Distinct(cols ...field.Expr) ITradeOrderItemDo
	Omit(cols ...field.Expr) ITradeOrderItemDo
	Join(table schema.Tabler, on ...field.Expr) ITradeOrderItemDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITradeOrderItemDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITradeOrderItemDo
	Group(cols ...field.Expr) ITradeOrderItemDo
	Having(conds ...gen.Condition) ITradeOrderItemDo
	Limit(limit int) ITradeOrderItemDo
	Offset(offset int) ITradeOrderItemDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITradeOrderItemDo
	Unscoped() ITradeOrderItemDo
	Create(values ...*trade.TradeOrderItem) error
	CreateInBatches(values []*trade.TradeOrderItem, batchSize int) error
	Save(values ...*trade.TradeOrderItem) error
	First() (*trade.TradeOrderItem, error)
	Take() (*trade.TradeOrderItem, error)
	Last() (*trade.TradeOrderItem, error)
	Find() ([]*trade.TradeOrderItem, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*trade.TradeOrderItem, err error)
	FindInBatches(result *[]*trade.TradeOrderItem, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*trade.TradeOrderItem) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITradeOrderItemDo
	Assign(attrs ...field.AssignExpr) ITradeOrderItemDo
	Joins(fields ...field.RelationField) ITradeOrderItemDo
	Preload(fields ...field.RelationField) ITradeOrderItemDo
	FirstOrInit() (*trade.TradeOrderItem, error)
	FirstOrCreate() (*trade.TradeOrderItem, error)
	FindByPage(offset int, limit int) (result []*trade.TradeOrderItem, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITradeOrderItemDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tradeOrderItemDo) Debug() ITradeOrderItemDo {
	return t.withDO(t.DO.Debug())
}

func (t tradeOrderItemDo) WithContext(ctx context.Context) ITradeOrderItemDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tradeOrderItemDo) ReadDB() ITradeOrderItemDo {
	return t.Clauses(dbresolver.Read)
}

func (t tradeOrderItemDo) WriteDB() ITradeOrderItemDo {
	return t.Clauses(dbresolver.Write)
}

func (t tradeOrderItemDo) Session(config *gorm.Session) ITradeOrderItemDo {
	return t.withDO(t.DO.Session(config))
}

func (t tradeOrderItemDo) Clauses(conds ...clause.Expression) ITradeOrderItemDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tradeOrderItemDo) Returning(value interface{}, columns ...string) ITradeOrderItemDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tradeOrderItemDo) Not(conds ...gen.Condition) ITradeOrderItemDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tradeOrderItemDo) Or(conds ...gen.Condition) ITradeOrderItemDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tradeOrderItemDo) Select(conds ...field.Expr) ITradeOrderItemDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tradeOrderItemDo) Where(conds ...gen.Condition) ITradeOrderItemDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tradeOrderItemDo) Order(conds ...field.Expr) ITradeOrderItemDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tradeOrderItemDo) Distinct(cols ...field.Expr) ITradeOrderItemDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tradeOrderItemDo) Omit(cols ...field.Expr) ITradeOrderItemDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tradeOrderItemDo) Join(table schema.Tabler, on ...field.Expr) ITradeOrderItemDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tradeOrderItemDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITradeOrderItemDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tradeOrderItemDo) RightJoin(table schema.Tabler, on ...field.Expr) ITradeOrderItemDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tradeOrderItemDo) Group(cols ...field.Expr) ITradeOrderItemDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tradeOrderItemDo) Having(conds ...gen.Condition) ITradeOrderItemDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tradeOrderItemDo) Limit(limit int) ITradeOrderItemDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tradeOrderItemDo) Offset(offset int) ITradeOrderItemDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tradeOrderItemDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITradeOrderItemDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tradeOrderItemDo) Unscoped() ITradeOrderItemDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tradeOrderItemDo) Create(values ...*trade.TradeOrderItem) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tradeOrderItemDo) CreateInBatches(values []*trade.TradeOrderItem, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tradeOrderItemDo) Save(values ...*trade.TradeOrderItem) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tradeOrderItemDo) First() (*trade.TradeOrderItem, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*trade.TradeOrderItem), nil
	}
}

func (t tradeOrderItemDo) Take() (*trade.TradeOrderItem, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*trade.TradeOrderItem), nil
	}
}

func (t tradeOrderItemDo) Last() (*trade.TradeOrderItem, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*trade.TradeOrderItem), nil
	}
}

func (t tradeOrderItemDo) Find() ([]*trade.TradeOrderItem, error) {
	result, err := t.DO.Find()
	return result.([]*trade.TradeOrderItem), err
}

func (t tradeOrderItemDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*trade.TradeOrderItem, err error) {
	buf := make([]*trade.TradeOrderItem, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tradeOrderItemDo) FindInBatches(result *[]*trade.TradeOrderItem, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tradeOrderItemDo) Attrs(attrs ...field.AssignExpr) ITradeOrderItemDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tradeOrderItemDo) Assign(attrs ...field.AssignExpr) ITradeOrderItemDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tradeOrderItemDo) Joins(fields ...field.RelationField) ITradeOrderItemDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tradeOrderItemDo) Preload(fields ...field.RelationField) ITradeOrderItemDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tradeOrderItemDo) FirstOrInit() (*trade.TradeOrderItem, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*trade.TradeOrderItem), nil
	}
}

func (t tradeOrderItemDo) FirstOrCreate() (*trade.TradeOrderItem, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*trade.TradeOrderItem), nil
	}
}

func (t tradeOrderItemDo) FindByPage(offset int, limit int) (result []*trade.TradeOrderItem, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tradeOrderItemDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tradeOrderItemDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tradeOrderItemDo) Delete(models ...*trade.TradeOrderItem) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tradeOrderItemDo) withDO(do gen.Dao) *tradeOrderItemDo {
	t.DO = *do.(*gen.DO)
	return t
}
