// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend-go/internal/model/trade"
)

func newTradeDeliveryFreightTemplateCharge(db *gorm.DB, opts ...gen.DOOption) tradeDeliveryFreightTemplateCharge {
	_tradeDeliveryFreightTemplateCharge := tradeDeliveryFreightTemplateCharge{}

	_tradeDeliveryFreightTemplateCharge.tradeDeliveryFreightTemplateChargeDo.UseDB(db, opts...)
	_tradeDeliveryFreightTemplateCharge.tradeDeliveryFreightTemplateChargeDo.UseModel(&trade.TradeDeliveryFreightTemplateCharge{})

	tableName := _tradeDeliveryFreightTemplateCharge.tradeDeliveryFreightTemplateChargeDo.TableName()
	_tradeDeliveryFreightTemplateCharge.ALL = field.NewAsterisk(tableName)
	_tradeDeliveryFreightTemplateCharge.ID = field.NewInt64(tableName, "id")
	_tradeDeliveryFreightTemplateCharge.TemplateID = field.NewInt64(tableName, "template_id")
	_tradeDeliveryFreightTemplateCharge.AreaIDs = field.NewString(tableName, "area_ids")
	_tradeDeliveryFreightTemplateCharge.StartCount = field.NewFloat64(tableName, "start_count")
	_tradeDeliveryFreightTemplateCharge.StartPrice = field.NewInt(tableName, "start_price")
	_tradeDeliveryFreightTemplateCharge.ExtraCount = field.NewFloat64(tableName, "extra_count")
	_tradeDeliveryFreightTemplateCharge.ExtraPrice = field.NewInt(tableName, "extra_price")
	_tradeDeliveryFreightTemplateCharge.Creator = field.NewString(tableName, "creator")
	_tradeDeliveryFreightTemplateCharge.Updater = field.NewString(tableName, "updater")
	_tradeDeliveryFreightTemplateCharge.CreatedAt = field.NewTime(tableName, "create_time")
	_tradeDeliveryFreightTemplateCharge.UpdatedAt = field.NewTime(tableName, "update_time")
	_tradeDeliveryFreightTemplateCharge.Deleted = field.NewField(tableName, "deleted")

	_tradeDeliveryFreightTemplateCharge.fillFieldMap()

	return _tradeDeliveryFreightTemplateCharge
}

type tradeDeliveryFreightTemplateCharge struct {
	tradeDeliveryFreightTemplateChargeDo tradeDeliveryFreightTemplateChargeDo

	ALL        field.Asterisk
	ID         field.Int64   // 编号
	TemplateID field.Int64   // 模板编号
	AreaIDs    field.String  // 区域编号列表
	StartCount field.Float64 // 首件/首重/首体积
	StartPrice field.Int     // 首费(分)
	ExtraCount field.Float64 // 续件/续重/续体积
	ExtraPrice field.Int     // 续费(分)
	Creator    field.String  // 创建者
	Updater    field.String  // 更新者
	CreatedAt  field.Time    // 创建时间
	UpdatedAt  field.Time    // 更新时间
	Deleted    field.Field   // 是否删除

	fieldMap map[string]field.Expr
}

func (t tradeDeliveryFreightTemplateCharge) Table(newTableName string) *tradeDeliveryFreightTemplateCharge {
	t.tradeDeliveryFreightTemplateChargeDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tradeDeliveryFreightTemplateCharge) As(alias string) *tradeDeliveryFreightTemplateCharge {
	t.tradeDeliveryFreightTemplateChargeDo.DO = *(t.tradeDeliveryFreightTemplateChargeDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tradeDeliveryFreightTemplateCharge) updateTableName(table string) *tradeDeliveryFreightTemplateCharge {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.TemplateID = field.NewInt64(table, "template_id")
	t.AreaIDs = field.NewString(table, "area_ids")
	t.StartCount = field.NewFloat64(table, "start_count")
	t.StartPrice = field.NewInt(table, "start_price")
	t.ExtraCount = field.NewFloat64(table, "extra_count")
	t.ExtraPrice = field.NewInt(table, "extra_price")
	t.Creator = field.NewString(table, "creator")
	t.Updater = field.NewString(table, "updater")
	t.CreatedAt = field.NewTime(table, "create_time")
	t.UpdatedAt = field.NewTime(table, "update_time")
	t.Deleted = field.NewField(table, "deleted")

	t.fillFieldMap()

	return t
}

func (t *tradeDeliveryFreightTemplateCharge) WithContext(ctx context.Context) ITradeDeliveryFreightTemplateChargeDo {
	return t.tradeDeliveryFreightTemplateChargeDo.WithContext(ctx)
}

func (t tradeDeliveryFreightTemplateCharge) TableName() string {
	return t.tradeDeliveryFreightTemplateChargeDo.TableName()
}

func (t tradeDeliveryFreightTemplateCharge) Alias() string {
	return t.tradeDeliveryFreightTemplateChargeDo.Alias()
}

func (t tradeDeliveryFreightTemplateCharge) Columns(cols ...field.Expr) gen.Columns {
	return t.tradeDeliveryFreightTemplateChargeDo.Columns(cols...)
}

func (t *tradeDeliveryFreightTemplateCharge) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tradeDeliveryFreightTemplateCharge) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 12)
	t.fieldMap["id"] = t.ID
	t.fieldMap["template_id"] = t.TemplateID
	t.fieldMap["area_ids"] = t.AreaIDs
	t.fieldMap["start_count"] = t.StartCount
	t.fieldMap["start_price"] = t.StartPrice
	t.fieldMap["extra_count"] = t.ExtraCount
	t.fieldMap["extra_price"] = t.ExtraPrice
	t.fieldMap["creator"] = t.Creator
	t.fieldMap["updater"] = t.Updater
	t.fieldMap["create_time"] = t.CreatedAt
	t.fieldMap["update_time"] = t.UpdatedAt
	t.fieldMap["deleted"] = t.Deleted
}

func (t tradeDeliveryFreightTemplateCharge) clone(db *gorm.DB) tradeDeliveryFreightTemplateCharge {
	t.tradeDeliveryFreightTemplateChargeDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tradeDeliveryFreightTemplateCharge) replaceDB(db *gorm.DB) tradeDeliveryFreightTemplateCharge {
	t.tradeDeliveryFreightTemplateChargeDo.ReplaceDB(db)
	return t
}

type tradeDeliveryFreightTemplateChargeDo struct{ gen.DO }

type ITradeDeliveryFreightTemplateChargeDo interface {
	gen.SubQuery
	Debug() ITradeDeliveryFreightTemplateChargeDo
	WithContext(ctx context.Context) ITradeDeliveryFreightTemplateChargeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITradeDeliveryFreightTemplateChargeDo
	WriteDB() ITradeDeliveryFreightTemplateChargeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITradeDeliveryFreightTemplateChargeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITradeDeliveryFreightTemplateChargeDo
	Not(conds ...gen.Condition) ITradeDeliveryFreightTemplateChargeDo
	Or(conds ...gen.Condition) ITradeDeliveryFreightTemplateChargeDo
	Select(conds ...field.Expr) ITradeDeliveryFreightTemplateChargeDo
	Where(conds ...gen.Condition) ITradeDeliveryFreightTemplateChargeDo
	Order(conds ...field.Expr) ITradeDeliveryFreightTemplateChargeDo
	Distinct(cols ...field.Expr) ITradeDeliveryFreightTemplateChargeDo
	Omit(cols ...field.Expr) ITradeDeliveryFreightTemplateChargeDo
	Join(table schema.Tabler, on ...field.Expr) ITradeDeliveryFreightTemplateChargeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITradeDeliveryFreightTemplateChargeDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITradeDeliveryFreightTemplateChargeDo
	Group(cols ...field.Expr) ITradeDeliveryFreightTemplateChargeDo
	Having(conds ...gen.Condition) ITradeDeliveryFreightTemplateChargeDo
	Limit(limit int) ITradeDeliveryFreightTemplateChargeDo
	Offset(offset int) ITradeDeliveryFreightTemplateChargeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITradeDeliveryFreightTemplateChargeDo
	Unscoped() ITradeDeliveryFreightTemplateChargeDo
	Create(values ...*trade.TradeDeliveryFreightTemplateCharge) error
	CreateInBatches(values []*trade.TradeDeliveryFreightTemplateCharge, batchSize int) error
	Save(values ...*trade.TradeDeliveryFreightTemplateCharge) error
	First() (*trade.TradeDeliveryFreightTemplateCharge, error)
	Take() (*trade.TradeDeliveryFreightTemplateCharge, error)
	Last() (*trade.TradeDeliveryFreightTemplateCharge, error)
	Find() ([]*trade.TradeDeliveryFreightTemplateCharge, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*trade.TradeDeliveryFreightTemplateCharge, err error)
	FindInBatches(result *[]*trade.TradeDeliveryFreightTemplateCharge, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*trade.TradeDeliveryFreightTemplateCharge) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITradeDeliveryFreightTemplateChargeDo
	Assign(attrs ...field.AssignExpr) ITradeDeliveryFreightTemplateChargeDo
	Joins(fields ...field.RelationField) ITradeDeliveryFreightTemplateChargeDo
	Preload(fields ...field.RelationField) ITradeDeliveryFreightTemplateChargeDo
	FirstOrInit() (*trade.TradeDeliveryFreightTemplateCharge, error)
	FirstOrCreate() (*trade.TradeDeliveryFreightTemplateCharge, error)
	FindByPage(offset int, limit int) (result []*trade.TradeDeliveryFreightTemplateCharge, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITradeDeliveryFreightTemplateChargeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tradeDeliveryFreightTemplateChargeDo) Debug() ITradeDeliveryFreightTemplateChargeDo {
	return t.withDO(t.DO.Debug())
}

func (t tradeDeliveryFreightTemplateChargeDo) WithContext(ctx context.Context) ITradeDeliveryFreightTemplateChargeDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tradeDeliveryFreightTemplateChargeDo) ReadDB() ITradeDeliveryFreightTemplateChargeDo {
	return t.Clauses(dbresolver.Read)
}

func (t tradeDeliveryFreightTemplateChargeDo) WriteDB() ITradeDeliveryFreightTemplateChargeDo {
	return t.Clauses(dbresolver.Write)
}

func (t tradeDeliveryFreightTemplateChargeDo) Session(config *gorm.Session) ITradeDeliveryFreightTemplateChargeDo {
	return t.withDO(t.DO.Session(config))
}

func (t tradeDeliveryFreightTemplateChargeDo) Clauses(conds ...clause.Expression) ITradeDeliveryFreightTemplateChargeDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tradeDeliveryFreightTemplateChargeDo) Returning(value interface{}, columns ...string) ITradeDeliveryFreightTemplateChargeDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tradeDeliveryFreightTemplateChargeDo) Not(conds ...gen.Condition) ITradeDeliveryFreightTemplateChargeDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tradeDeliveryFreightTemplateChargeDo) Or(conds ...gen.Condition) ITradeDeliveryFreightTemplateChargeDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tradeDeliveryFreightTemplateChargeDo) Select(conds ...field.Expr) ITradeDeliveryFreightTemplateChargeDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tradeDeliveryFreightTemplateChargeDo) Where(conds ...gen.Condition) ITradeDeliveryFreightTemplateChargeDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tradeDeliveryFreightTemplateChargeDo) Order(conds ...field.Expr) ITradeDeliveryFreightTemplateChargeDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tradeDeliveryFreightTemplateChargeDo) Distinct(cols ...field.Expr) ITradeDeliveryFreightTemplateChargeDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tradeDeliveryFreightTemplateChargeDo) Omit(cols ...field.Expr) ITradeDeliveryFreightTemplateChargeDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tradeDeliveryFreightTemplateChargeDo) Join(table schema.Tabler, on ...field.Expr) ITradeDeliveryFreightTemplateChargeDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tradeDeliveryFreightTemplateChargeDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITradeDeliveryFreightTemplateChargeDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tradeDeliveryFreightTemplateChargeDo) RightJoin(table schema.Tabler, on ...field.Expr) ITradeDeliveryFreightTemplateChargeDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tradeDeliveryFreightTemplateChargeDo) Group(cols ...field.Expr) ITradeDeliveryFreightTemplateChargeDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tradeDeliveryFreightTemplateChargeDo) Having(conds ...gen.Condition) ITradeDeliveryFreightTemplateChargeDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tradeDeliveryFreightTemplateChargeDo) Limit(limit int) ITradeDeliveryFreightTemplateChargeDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tradeDeliveryFreightTemplateChargeDo) Offset(offset int) ITradeDeliveryFreightTemplateChargeDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tradeDeliveryFreightTemplateChargeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITradeDeliveryFreightTemplateChargeDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tradeDeliveryFreightTemplateChargeDo) Unscoped() ITradeDeliveryFreightTemplateChargeDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tradeDeliveryFreightTemplateChargeDo) Create(values ...*trade.TradeDeliveryFreightTemplateCharge) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tradeDeliveryFreightTemplateChargeDo) CreateInBatches(values []*trade.TradeDeliveryFreightTemplateCharge, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tradeDeliveryFreightTemplateChargeDo) Save(values ...*trade.TradeDeliveryFreightTemplateCharge) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tradeDeliveryFreightTemplateChargeDo) First() (*trade.TradeDeliveryFreightTemplateCharge, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*trade.TradeDeliveryFreightTemplateCharge), nil
	}
}

func (t tradeDeliveryFreightTemplateChargeDo) Take() (*trade.TradeDeliveryFreightTemplateCharge, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*trade.TradeDeliveryFreightTemplateCharge), nil
	}
}

func (t tradeDeliveryFreightTemplateChargeDo) Last() (*trade.TradeDeliveryFreightTemplateCharge, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*trade.TradeDeliveryFreightTemplateCharge), nil
	}
}

func (t tradeDeliveryFreightTemplateChargeDo) Find() ([]*trade.TradeDeliveryFreightTemplateCharge, error) {
	result, err := t.DO.Find()
	return result.([]*trade.TradeDeliveryFreightTemplateCharge), err
}

func (t tradeDeliveryFreightTemplateChargeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*trade.TradeDeliveryFreightTemplateCharge, err error) {
	buf := make([]*trade.TradeDeliveryFreightTemplateCharge, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tradeDeliveryFreightTemplateChargeDo) FindInBatches(result *[]*trade.TradeDeliveryFreightTemplateCharge, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tradeDeliveryFreightTemplateChargeDo) Attrs(attrs ...field.AssignExpr) ITradeDeliveryFreightTemplateChargeDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tradeDeliveryFreightTemplateChargeDo) Assign(attrs ...field.AssignExpr) ITradeDeliveryFreightTemplateChargeDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tradeDeliveryFreightTemplateChargeDo) Joins(fields ...field.RelationField) ITradeDeliveryFreightTemplateChargeDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tradeDeliveryFreightTemplateChargeDo) Preload(fields ...field.RelationField) ITradeDeliveryFreightTemplateChargeDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tradeDeliveryFreightTemplateChargeDo) FirstOrInit() (*trade.TradeDeliveryFreightTemplateCharge, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*trade.TradeDeliveryFreightTemplateCharge), nil
	}
}

func (t tradeDeliveryFreightTemplateChargeDo) FirstOrCreate() (*trade.TradeDeliveryFreightTemplateCharge, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*trade.TradeDeliveryFreightTemplateCharge), nil
	}
}

func (t tradeDeliveryFreightTemplateChargeDo) FindByPage(offset int, limit int) (result []*trade.TradeDeliveryFreightTemplateCharge, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tradeDeliveryFreightTemplateChargeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tradeDeliveryFreightTemplateChargeDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tradeDeliveryFreightTemplateChargeDo) Delete(models ...*trade.TradeDeliveryFreightTemplateCharge) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tradeDeliveryFreightTemplateChargeDo) withDO(do gen.Dao) *tradeDeliveryFreightTemplateChargeDo {
	t.DO = *do.(*gen.DO)
	return t
}
