// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend-go/internal/model/trade"
)

func newAfterSale(db *gorm.DB, opts ...gen.DOOption) afterSale {
	_afterSale := afterSale{}

	_afterSale.afterSaleDo.UseDB(db, opts...)
	_afterSale.afterSaleDo.UseModel(&trade.AfterSale{})

	tableName := _afterSale.afterSaleDo.TableName()
	_afterSale.ALL = field.NewAsterisk(tableName)
	_afterSale.ID = field.NewInt64(tableName, "id")
	_afterSale.Creator = field.NewString(tableName, "creator")
	_afterSale.Updater = field.NewString(tableName, "updater")
	_afterSale.CreatedAt = field.NewTime(tableName, "create_time")
	_afterSale.UpdatedAt = field.NewTime(tableName, "update_time")
	_afterSale.DeletedAt = field.NewTime(tableName, "deleted")
	_afterSale.Deleted = field.NewBool(tableName, "deleted")
	_afterSale.No = field.NewString(tableName, "no")
	_afterSale.Status = field.NewInt(tableName, "status")
	_afterSale.Way = field.NewInt(tableName, "way")
	_afterSale.Type = field.NewInt(tableName, "type")
	_afterSale.UserID = field.NewInt64(tableName, "user_id")
	_afterSale.ApplyReason = field.NewString(tableName, "apply_reason")
	_afterSale.ApplyDescription = field.NewString(tableName, "apply_description")
	_afterSale.ApplyPicURLs = field.NewString(tableName, "apply_pic_urls")
	_afterSale.OrderID = field.NewInt64(tableName, "order_id")
	_afterSale.OrderNo = field.NewString(tableName, "order_no")
	_afterSale.OrderItemID = field.NewInt64(tableName, "order_item_id")
	_afterSale.SpuID = field.NewInt64(tableName, "spu_id")
	_afterSale.SpuName = field.NewString(tableName, "spu_name")
	_afterSale.SkuID = field.NewInt64(tableName, "sku_id")
	_afterSale.Properties = field.NewString(tableName, "properties")
	_afterSale.PicURL = field.NewString(tableName, "pic_url")
	_afterSale.Count = field.NewInt(tableName, "count")
	_afterSale.AuditTime = field.NewTime(tableName, "audit_time")
	_afterSale.AuditUserID = field.NewInt64(tableName, "audit_user_id")
	_afterSale.AuditReason = field.NewString(tableName, "audit_reason")
	_afterSale.RefundPrice = field.NewInt(tableName, "refund_price")
	_afterSale.PayRefundID = field.NewInt64(tableName, "pay_refund_id")
	_afterSale.RefundTime = field.NewTime(tableName, "refund_time")
	_afterSale.LogisticsID = field.NewInt64(tableName, "logistics_id")
	_afterSale.LogisticsNo = field.NewString(tableName, "logistics_no")
	_afterSale.DeliveryTime = field.NewTime(tableName, "delivery_time")
	_afterSale.ReceiveTime = field.NewTime(tableName, "receive_time")
	_afterSale.ReceiveReason = field.NewString(tableName, "receive_reason")

	_afterSale.fillFieldMap()

	return _afterSale
}

type afterSale struct {
	afterSaleDo afterSaleDo

	ALL              field.Asterisk
	ID               field.Int64
	Creator          field.String
	Updater          field.String
	CreatedAt        field.Time
	UpdatedAt        field.Time
	DeletedAt        field.Time
	Deleted          field.Bool
	No               field.String
	Status           field.Int
	Way              field.Int
	Type             field.Int
	UserID           field.Int64
	ApplyReason      field.String
	ApplyDescription field.String
	ApplyPicURLs     field.String
	OrderID          field.Int64
	OrderNo          field.String
	OrderItemID      field.Int64
	SpuID            field.Int64
	SpuName          field.String
	SkuID            field.Int64
	Properties       field.String
	PicURL           field.String
	Count            field.Int
	AuditTime        field.Time
	AuditUserID      field.Int64
	AuditReason      field.String
	RefundPrice      field.Int
	PayRefundID      field.Int64
	RefundTime       field.Time
	LogisticsID      field.Int64
	LogisticsNo      field.String
	DeliveryTime     field.Time
	ReceiveTime      field.Time
	ReceiveReason    field.String

	fieldMap map[string]field.Expr
}

func (a afterSale) Table(newTableName string) *afterSale {
	a.afterSaleDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a afterSale) As(alias string) *afterSale {
	a.afterSaleDo.DO = *(a.afterSaleDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *afterSale) updateTableName(table string) *afterSale {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt64(table, "id")
	a.Creator = field.NewString(table, "creator")
	a.Updater = field.NewString(table, "updater")
	a.CreatedAt = field.NewTime(table, "create_time")
	a.UpdatedAt = field.NewTime(table, "update_time")
	a.DeletedAt = field.NewTime(table, "deleted")
	a.Deleted = field.NewBool(table, "deleted")
	a.No = field.NewString(table, "no")
	a.Status = field.NewInt(table, "status")
	a.Way = field.NewInt(table, "way")
	a.Type = field.NewInt(table, "type")
	a.UserID = field.NewInt64(table, "user_id")
	a.ApplyReason = field.NewString(table, "apply_reason")
	a.ApplyDescription = field.NewString(table, "apply_description")
	a.ApplyPicURLs = field.NewString(table, "apply_pic_urls")
	a.OrderID = field.NewInt64(table, "order_id")
	a.OrderNo = field.NewString(table, "order_no")
	a.OrderItemID = field.NewInt64(table, "order_item_id")
	a.SpuID = field.NewInt64(table, "spu_id")
	a.SpuName = field.NewString(table, "spu_name")
	a.SkuID = field.NewInt64(table, "sku_id")
	a.Properties = field.NewString(table, "properties")
	a.PicURL = field.NewString(table, "pic_url")
	a.Count = field.NewInt(table, "count")
	a.AuditTime = field.NewTime(table, "audit_time")
	a.AuditUserID = field.NewInt64(table, "audit_user_id")
	a.AuditReason = field.NewString(table, "audit_reason")
	a.RefundPrice = field.NewInt(table, "refund_price")
	a.PayRefundID = field.NewInt64(table, "pay_refund_id")
	a.RefundTime = field.NewTime(table, "refund_time")
	a.LogisticsID = field.NewInt64(table, "logistics_id")
	a.LogisticsNo = field.NewString(table, "logistics_no")
	a.DeliveryTime = field.NewTime(table, "delivery_time")
	a.ReceiveTime = field.NewTime(table, "receive_time")
	a.ReceiveReason = field.NewString(table, "receive_reason")

	a.fillFieldMap()

	return a
}

func (a *afterSale) WithContext(ctx context.Context) IAfterSaleDo {
	return a.afterSaleDo.WithContext(ctx)
}

func (a afterSale) TableName() string { return a.afterSaleDo.TableName() }

func (a afterSale) Alias() string { return a.afterSaleDo.Alias() }

func (a afterSale) Columns(cols ...field.Expr) gen.Columns { return a.afterSaleDo.Columns(cols...) }

func (a *afterSale) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *afterSale) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 35)
	a.fieldMap["id"] = a.ID
	a.fieldMap["creator"] = a.Creator
	a.fieldMap["updater"] = a.Updater
	a.fieldMap["create_time"] = a.CreatedAt
	a.fieldMap["update_time"] = a.UpdatedAt
	a.fieldMap["deleted"] = a.DeletedAt
	a.fieldMap["deleted"] = a.Deleted
	a.fieldMap["no"] = a.No
	a.fieldMap["status"] = a.Status
	a.fieldMap["way"] = a.Way
	a.fieldMap["type"] = a.Type
	a.fieldMap["user_id"] = a.UserID
	a.fieldMap["apply_reason"] = a.ApplyReason
	a.fieldMap["apply_description"] = a.ApplyDescription
	a.fieldMap["apply_pic_urls"] = a.ApplyPicURLs
	a.fieldMap["order_id"] = a.OrderID
	a.fieldMap["order_no"] = a.OrderNo
	a.fieldMap["order_item_id"] = a.OrderItemID
	a.fieldMap["spu_id"] = a.SpuID
	a.fieldMap["spu_name"] = a.SpuName
	a.fieldMap["sku_id"] = a.SkuID
	a.fieldMap["properties"] = a.Properties
	a.fieldMap["pic_url"] = a.PicURL
	a.fieldMap["count"] = a.Count
	a.fieldMap["audit_time"] = a.AuditTime
	a.fieldMap["audit_user_id"] = a.AuditUserID
	a.fieldMap["audit_reason"] = a.AuditReason
	a.fieldMap["refund_price"] = a.RefundPrice
	a.fieldMap["pay_refund_id"] = a.PayRefundID
	a.fieldMap["refund_time"] = a.RefundTime
	a.fieldMap["logistics_id"] = a.LogisticsID
	a.fieldMap["logistics_no"] = a.LogisticsNo
	a.fieldMap["delivery_time"] = a.DeliveryTime
	a.fieldMap["receive_time"] = a.ReceiveTime
	a.fieldMap["receive_reason"] = a.ReceiveReason
}

func (a afterSale) clone(db *gorm.DB) afterSale {
	a.afterSaleDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a afterSale) replaceDB(db *gorm.DB) afterSale {
	a.afterSaleDo.ReplaceDB(db)
	return a
}

type afterSaleDo struct{ gen.DO }

type IAfterSaleDo interface {
	gen.SubQuery
	Debug() IAfterSaleDo
	WithContext(ctx context.Context) IAfterSaleDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAfterSaleDo
	WriteDB() IAfterSaleDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAfterSaleDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAfterSaleDo
	Not(conds ...gen.Condition) IAfterSaleDo
	Or(conds ...gen.Condition) IAfterSaleDo
	Select(conds ...field.Expr) IAfterSaleDo
	Where(conds ...gen.Condition) IAfterSaleDo
	Order(conds ...field.Expr) IAfterSaleDo
	Distinct(cols ...field.Expr) IAfterSaleDo
	Omit(cols ...field.Expr) IAfterSaleDo
	Join(table schema.Tabler, on ...field.Expr) IAfterSaleDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAfterSaleDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAfterSaleDo
	Group(cols ...field.Expr) IAfterSaleDo
	Having(conds ...gen.Condition) IAfterSaleDo
	Limit(limit int) IAfterSaleDo
	Offset(offset int) IAfterSaleDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAfterSaleDo
	Unscoped() IAfterSaleDo
	Create(values ...*trade.AfterSale) error
	CreateInBatches(values []*trade.AfterSale, batchSize int) error
	Save(values ...*trade.AfterSale) error
	First() (*trade.AfterSale, error)
	Take() (*trade.AfterSale, error)
	Last() (*trade.AfterSale, error)
	Find() ([]*trade.AfterSale, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*trade.AfterSale, err error)
	FindInBatches(result *[]*trade.AfterSale, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*trade.AfterSale) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAfterSaleDo
	Assign(attrs ...field.AssignExpr) IAfterSaleDo
	Joins(fields ...field.RelationField) IAfterSaleDo
	Preload(fields ...field.RelationField) IAfterSaleDo
	FirstOrInit() (*trade.AfterSale, error)
	FirstOrCreate() (*trade.AfterSale, error)
	FindByPage(offset int, limit int) (result []*trade.AfterSale, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAfterSaleDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a afterSaleDo) Debug() IAfterSaleDo {
	return a.withDO(a.DO.Debug())
}

func (a afterSaleDo) WithContext(ctx context.Context) IAfterSaleDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a afterSaleDo) ReadDB() IAfterSaleDo {
	return a.Clauses(dbresolver.Read)
}

func (a afterSaleDo) WriteDB() IAfterSaleDo {
	return a.Clauses(dbresolver.Write)
}

func (a afterSaleDo) Session(config *gorm.Session) IAfterSaleDo {
	return a.withDO(a.DO.Session(config))
}

func (a afterSaleDo) Clauses(conds ...clause.Expression) IAfterSaleDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a afterSaleDo) Returning(value interface{}, columns ...string) IAfterSaleDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a afterSaleDo) Not(conds ...gen.Condition) IAfterSaleDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a afterSaleDo) Or(conds ...gen.Condition) IAfterSaleDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a afterSaleDo) Select(conds ...field.Expr) IAfterSaleDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a afterSaleDo) Where(conds ...gen.Condition) IAfterSaleDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a afterSaleDo) Order(conds ...field.Expr) IAfterSaleDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a afterSaleDo) Distinct(cols ...field.Expr) IAfterSaleDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a afterSaleDo) Omit(cols ...field.Expr) IAfterSaleDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a afterSaleDo) Join(table schema.Tabler, on ...field.Expr) IAfterSaleDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a afterSaleDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAfterSaleDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a afterSaleDo) RightJoin(table schema.Tabler, on ...field.Expr) IAfterSaleDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a afterSaleDo) Group(cols ...field.Expr) IAfterSaleDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a afterSaleDo) Having(conds ...gen.Condition) IAfterSaleDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a afterSaleDo) Limit(limit int) IAfterSaleDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a afterSaleDo) Offset(offset int) IAfterSaleDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a afterSaleDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAfterSaleDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a afterSaleDo) Unscoped() IAfterSaleDo {
	return a.withDO(a.DO.Unscoped())
}

func (a afterSaleDo) Create(values ...*trade.AfterSale) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a afterSaleDo) CreateInBatches(values []*trade.AfterSale, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a afterSaleDo) Save(values ...*trade.AfterSale) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a afterSaleDo) First() (*trade.AfterSale, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*trade.AfterSale), nil
	}
}

func (a afterSaleDo) Take() (*trade.AfterSale, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*trade.AfterSale), nil
	}
}

func (a afterSaleDo) Last() (*trade.AfterSale, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*trade.AfterSale), nil
	}
}

func (a afterSaleDo) Find() ([]*trade.AfterSale, error) {
	result, err := a.DO.Find()
	return result.([]*trade.AfterSale), err
}

func (a afterSaleDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*trade.AfterSale, err error) {
	buf := make([]*trade.AfterSale, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a afterSaleDo) FindInBatches(result *[]*trade.AfterSale, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a afterSaleDo) Attrs(attrs ...field.AssignExpr) IAfterSaleDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a afterSaleDo) Assign(attrs ...field.AssignExpr) IAfterSaleDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a afterSaleDo) Joins(fields ...field.RelationField) IAfterSaleDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a afterSaleDo) Preload(fields ...field.RelationField) IAfterSaleDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a afterSaleDo) FirstOrInit() (*trade.AfterSale, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*trade.AfterSale), nil
	}
}

func (a afterSaleDo) FirstOrCreate() (*trade.AfterSale, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*trade.AfterSale), nil
	}
}

func (a afterSaleDo) FindByPage(offset int, limit int) (result []*trade.AfterSale, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a afterSaleDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a afterSaleDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a afterSaleDo) Delete(models ...*trade.AfterSale) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *afterSaleDo) withDO(do gen.Dao) *afterSaleDo {
	a.DO = *do.(*gen.DO)
	return a
}
